### ISSUE TITLE
Bedrock support to use Claude Models? 

### ISSUE THREAD

**Issue by jay2610** [saoudrizwan/claude-dev#10]
First of all, this is great work. 
Any plan to add AWS bedrock support for Claude models?

**Comment by saoudrizwan** [comment]
Thank you! Yes, Bedrock support is on the roadmap.

**Comment by shannonlal** [comment]
@saoudrizwan I have access to Claude Bedrock at work.  Would you be okay if I take this on?

**Comment by saoudrizwan** [comment]
@shannonlal thank you for the offer! I just released v1.0.9 with OpenRouter and AWS Bedrock support 🎉 (hit the settings button in the top menu bar > API Provider > OpenRouter)
