### ISSUE TITLE
Extension does not load on VS Code on Win Server 2022

### ISSUE THREAD

**Issue by joeyg6393** [saoudrizwan/claude-dev#101]
I have tried to both install through the extension marketplace as through building it through Git, but once everything is downloaded and installed the placeholder of the icon just stays blank with a little blue clock next to it. 

I have tried older versions (all of them actually) and they all produce the same issue. Not sure if I am missing another extension or if the server is messing with it, but any help would be greatly appreciated.

![image](https://github.com/user-attachments/assets/ec709968-1b22-4d73-999f-c988b7a7aa17)

**Comment by saoudrizwan** [comment]
Is this only happening for you on WIn Server 2022, or are you seeing this in other environments as well?

**Comment by joeyg6393** [comment]
I only have VS code on the one environment. I'll install it on a different computer tomorrow to try and see if the problem replicates off the server.

**Comment by joeyg6393** [comment]
This works well on the version of VS code I spun up on a regular desktop so It is something server-side, that is causing the issue.

I will look to see if I can fix it, but any suggestions would be welcome. Thanks for taking the time to look at this.

**Comment by saoudrizwan** [comment]
It's likely the version of vscode you were using was outdated, you need to be on at least 1.9 for claude dev to work as expected. Closing but feel free to re-open if it still doesn't work after updating to the latest.
