### ISSUE TITLE
Feature Request: Web Search

### ISSUE THREAD

**Issue by jkristoph** [saoudrizwan/claude-dev#102]
Ive noticed that when building applications with claude-dev, often that not, outdated library versions are used due to the knowledge cut-off with the llm. A web search will be a great way to use updated information important to its process.

**Comment by CiberNin** [comment]
For coding purposes, it might be best to give access to git repos specifically using the existing tools.

**Comment by arunkr93** [comment]
Need browsing capabilities for updated libraries/dependencies etc

**Comment by saoudrizwan** [comment]
Possibly on the roadmap, closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/57
