### ISSUE TITLE
Enable Prompt Caching when using Anthropic API

### ISSUE THREAD

**Issue by nebw** [saoudrizwan/claude-dev#105]
The recently announced prompt caching beta feature for the Anthropic API should reduce cost and latency significantly when interacting with Claude Dev:

https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

**Comment by lars67** [comment]
That indeed would be a huge improvement, still in beta though, and the pricing priciples of Antrophic gets even more complex.
I normally work 20 minutes then my daily ration of tokens are used :-(

**Comment by saoudrizwan** [comment]
Prompt Caching is now available in v1.2.0 🎉 This is a gamechanger for Claude Dev, costs down by ~90% + response time down by at least half. Make sure you're using Anthropic API with either Claude 3.5 Sonnet or Claude 3.0 Haiku. You'll now notice a "Prompt Cache" tracker in the task card, which keeps count of tokens written to Anthropic's cache -> tokens read from cache.
