### ISSUE TITLE
Hitting the token limit

### ISSUE THREAD

**Issue by SamPink** [saoudrizwan/claude-dev#106]
![image](https://github.com/user-attachments/assets/86bf12b2-74b1-4850-a019-2b2d92e03b65)

Im not sure if this is something that can be solved by truncating the context slightly or if its just a limitation of Claude

**Comment by CiberNin** [comment]
Once prompt exceeds x% (90?) we should have Claude do some sort of automatic cleanup / summarization process.

Actually, may be worth keeping track of a task stack. A task can spawn new tasks. Once the task and all its sub tasks are complete, you have Claude do a summarize of what the issue and solution was.

That way you don't get in the circle where claude does something wrong over and over and now is in a "space" where it can make mistakes.

**Comment by SamPink** [comment]
![image](https://github.com/user-attachments/assets/2c822053-d9f2-400b-9775-6b1c34df7f8b)

im on the latest version v1.4.16 that has the fix for rolling context window but i still managed to max it out!

**Comment by saoudrizwan** [comment]
v1.5.16 now has sliding window context management that lets you keep conversations going indefinitely
