### ISSUE TITLE
Using RAG for a coding?

### ISSUE THREAD

**Issue by windy31** [saoudrizwan/claude-dev#110]
Here's an idea - to use RAG systems for making the coding more comfortable, since all the functions will be in context of rag, lessering the tokens needed to work with Claude DEV.

Also, all the love to the creator of this plugin, thank you very much!

**Comment by CiberNin** [comment]
Please provide a more complete description of what using a RAG system entails.

**Comment by saoudrizwan** [comment]
Please see https://github.com/saoudrizwan/claude-dev/issues/68#issuecomment-2325012621
