### ISSUE TITLE
Caching problem

### ISSUE THREAD

**Issue by windy31** [saoudrizwan/claude-dev#111]
I don't know if that's the same for you guys, but after the caching got implemented i've got MORE tokens, than less and hit a limit of 1 mil VERY quickly, even tho i didn't change anything in my workflow.
What i've been doing - i was just giving the app to read my main.py and everything it needed to(as i was previously) and now it hits 1 minute limit all the time.
Am i doing something wrong?
P.S. i don't have much in custom instructions, only this:
"When writing code never skip previous parts of a content with "previous content" or anything like that - only write the whole code."
If that's needed.

**Comment by lars67** [comment]
I have good experieces so far - I get a very high level of Cache hits.
I start with asking CD to read all the open files. Ahead of this I have opened all files I find relevant to whatever I am working with.

**Comment by windy31** [comment]
So, i should explicitly ask cache to read the files? How to control this, maybe that's an issue in my workflow.

**Comment by mkearl** [comment]
@lars67 can you share an example of one of your prompts?

**Comment by saoudrizwan** [comment]
You don't have to tell claude to read from the prompt cache, that's done automatically. There's nothing different with prompt caching that would result in more tokens being used, I think you might be mistaking the new UI for more tokens being used but the Cache row represents tokens written to cache -> tokens read from cache, it's not unusual for these numbers to get really high the further along a conversaion you go
