### ISSUE TITLE
API request failed: 401 {"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"}}

### ISSUE THREAD

**Issue by nop1984** [saoudrizwan/claude-dev#12]
No idea what it that, Just installed it today and used first time

![image](https://github.com/user-attachments/assets/e4d6ede8-aa14-4203-b246-099014d4dc91)

**Comment by kurttu4** [comment]
![image](https://github.com/user-attachments/assets/e699bb47-f034-4c2c-bf3c-6b310a13994f)

**Comment by saoudrizwan** [comment]
Thank you for the image @kurttu4–if using a valid API key is still resulting in that error, please lmk and I will reopen this issue.

**Comment by nop1984** [comment]
> Thank you for the image @kurttu4–if using a valid API key is still resulting in that error, please lmk and I will reopen this issue.

yes, sorry to bother, I confused API key prompt with command prompt. Expected that API key somewhwere in setting. All good now, thanks.
