### ISSUE TITLE
Execute Command fails： Error executing command: (0 , rk.addAbortListener) is not a function

### ISSUE THREAD

**Issue by ybalbert001** [saoudrizwan/claude-dev#120]
<img width="276" alt="Screenshot 2024-08-17 at 14 55 59" src="https://github.com/user-attachments/assets/3e34e51c-48e0-4751-9301-9eb0a94a462f">

As claude-dev already know to execute this command, why it throw exception on executing? 

I can run 'git diff --staged' on my terminal.

**Comment by saoudrizwan** [comment]
Are you guys still seeing this issue in the latest 1.5.16?

**Comment by tinoargentino** [comment]
I'm seeing this issue on v1.5.26

```
Error
Error executing command:
(0 , coe.addAbortListener) is not a function
```

**Comment by saoudrizwan** [comment]
@tinoargentino what OS/vscode version are you using?

**Comment by saoudrizwan** [comment]
It looks like according to https://github.com/sindresorhus/execa/issues/1064#issuecomment-2116506926 you need to be using at least Node 20.5.0. Can you see what version you're using?

**Comment by tinoargentino** [comment]
hmmm strange situation:
- I'm using vs code Version: 1.87.2
- I initially was testing connected to another computer via ssh that CANT run Node 20.5.0

However, then I tried to run the extension locally, checking I'm using Node v20.5.0 and still facing the same error

**Comment by saoudrizwan** [comment]
I think the larger issue is you're using vscode 1.87.2, I'm surprised it's even opening for you on that version! I really should update my package.json engine version, but not sure what exact version things stop working. Pls try updating to the latest vscode and see if that helps

**Comment by saoudrizwan** [comment]
Oh also, I removed execa and now commands run right in your terminal, this should work for you now but for claude to see the command's output it requires vscode v1.93. Closing as this should be fixed, but pls report back if you're still running into problems

**Comment by tinoargentino** [comment]
thanks @saoudrizwan ! it def works!!! and as said, it can't read output. Thanks a lot!

**Comment by saoudrizwan** [comment]
That error's probably happening because it's trying to set its cwd to your desktop which seems to not exist. If you open claude dev in an existing project it should work as expected! I'll add a check to ensure desktop exists before trying to use it as cwd, any suggestions for a good fallback?
