### ISSUE TITLE
Proposal: New project name?

### ISSUE THREAD

**Issue by bglgwyng** [saoudrizwan/claude-dev#121]
Thank you for creating this excellent project.
Initially, I thought this extension only supported Claude, so I considered forking it to implement my own backend or create a backend-agnostic version. However, I was pleasantly surprised to discover that it already supports other LLM backends as well!
I suspect that other users might be similarly misled, as I was. Have you considered renaming the project? Alternatively, providing a more comprehensive description or updating the README could be an effective solution.

**Comment by saoudrizwan** [comment]
If you have any suggestions I'd love to hear them! I personally think anthropic is going to keep leading agentic coding benchmarks so "claude" dev might turn out to be the most appropriate name after all

**Comment by kiranmaya** [comment]
nope, it deserves a new name. 
i suggest "OpenCoder"

**Comment by ybalbert001** [comment]
There are too many names like AICoder out there. It lacks distinctiveness. claude-dev is better

**Comment by saoudrizwan** [comment]
Closing bc no plans to change name for now

**Comment by narmaku** [comment]
I propose Mike-dev.

Question: Why?
Answer: Why not?
