### ISSUE TITLE
Trigger save versioning in VS Code

### ISSUE THREAD

**Issue by ironwill9698** [saoudrizwan/claude-dev#123]
When I manually write code and save the file it creates a "version history" checkpoint so that I can revert to prior versions of that code.  It looks like when this extension makes changes to the code no version history is created so I can't easily revert back a few versions when the AI has gone down a rabbit trail and caused a lot of issues.  Is it possible to somehow create those save checkpoints like occur when you manually save a file in VS Code?

**Comment by saoudrizwan** [comment]
Add this to Custom Instructions (in settings) to keep git history as Claude works: "After completing a task or making significant changes, automatically run `git add . && git commit -m` with a message summarizing the recent updates." This way you can keep track of his work in git and easily revert the changes he makes.
