### ISSUE TITLE
Number of request tokens has exceeded

### ISSUE THREAD

**Issue by LeonMatch** [saoudrizwan/claude-dev#124]
I am getting this error often during development: "Number of request tokens has exceeded your daily rate limit".
How is it possible to reduce request tokens in communication with Claude Dev? Is there caching or something?
What am I missing?

Also Claude Dev produces a lot of unnecessary text, like "Task Completed" summary for example, even when the task is not being completed yet. I might be testing last changes in code and may come back with a bug. Is reducing that would help with "Number of request tokens has exceeded" error?

I got the following limits in Anthropic:
Claude 3.5 Sonnet | 50 requests per minute ( I am not using that much) | 40,000 tokens per minute  | 1,000,000 tokens per day
Claude 3 Sonnet    | 50 requests per minute | 40,000 tokens per minute | tokens per day 1,000,000
Claude 3 Haiku      | 50 requests per minute | 50,000  tokens per minute | tokens per day 5,000,000 

It is Claude 3.5 Sonnet I am using in Claude Dev now.
If I change it to Claude 3 Haiku, which has greater limits, will it reduce the quality of Claude Dev performance?

**Comment by ichoosetoaccept** [comment]
I came here to open an issue about avoiding this type of message:
API Request Failed

429 {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}

It feels like this should be avoidable. Either grab the current user's per-minute (and other types of limits) rate limits and make sure the extension abides by them (perhaps even telling the user something like "waiting to avoid Anthropic rate limiting" or, if Anthropic's API does not support reading out these limits, ask the user to check them manually in their Anthropic account and provide a way to enter them in extension settings. Then ensure the extension respects those limits.

I feel my issue is similar enough to this issue that opening a new one was not warranted.

**Comment by fry69** [comment]
Showing how many tokes are left until the rate limits hit would be helpful but also a bit hard to implement. These rate limits can change, as can the interval where they apply or when they get reset.

An alternative is to use a different front end/proxy to access Anthropic's API as the [documentation](https://aider.chat/docs/llms/anthropic.html) recommends:

---
Anthropic has very low rate limits. You can access all the Anthropic models via [OpenRouter](https://aider.chat/docs/llms/openrouter.html) or [Google Vertex AI](https://aider.chat/docs/llms/vertex.html) with more generous rate limits."

---

**Comment by danividalg** [comment]
Hi @saoudrizwan  :)
It could be great if you can add a configuration field for the rate limits, so Claude Dev can wait if needed to avoid overpass this limit and get this type of errors.
What do you think ? :)

**Comment by saoudrizwan** [comment]
I suggest using OpenRouter to get around these rate limit issues--they are working on adding prompt caching which would make them the best api option to use. Adding rate limit information is on the roadmap https://github.com/saoudrizwan/claude-dev/issues/54
