### ISSUE TITLE
Feature Request: Custom instruction for entire project/file

### ISSUE THREAD

**Issue by jegan221724** [saoudrizwan/claude-dev#128]
Thank you for the great extension. It works great and is helpful for a non-tech guy like me. Can custom instructions be included that Claude Dev can use throughout the project? This is in line with Claude's Project feature, where I can give custom instructions and Claude refers them throughout the project chats.

Use Case: Let's consider I'm trying to enhance the UI/UX of the web application I have built. Now, to achieve this task I have to give expectiation of mine in the prompt always and Claude Dev changes it in every file.  After adding more screens, now again I have to do this. I feel more tokens are getting wasted because of this. But if I have a custom instruction set for my entire project, it will be easy for Claude dev to reuse/adopt to recent changes quickly than running through the entire code base.

Not sure how much of the expectation is possible. But itd be great if this is possible. Cheers :)

**Comment by mkearl** [comment]
When you first bring up the extension from the sidebar of tools you will see a gear icon in the upper right.  There you can make settings changes and there is a custom instructions area there.
![Screenshot 2024-08-18 at 8 07 35 AM](https://github.com/user-attachments/assets/9480affa-6872-4d25-9e03-16b2adc9cdf7)

**Comment by jegan221724** [comment]
Great, i will play around with it. Thank you so much!

**Comment by jegan221724** [comment]
I dont see any option to upload images for references. Does it not support uploading images/docs?

**Comment by mkearl** [comment]
Where you type in your prompt over to the right there is a camera button that allows you to attach an image.

**Comment by jegan221724** [comment]
Yes, Im aware of this, but I was referring to the image in the custom instructions. Sorry for not being clear in my previous question. Appreciate your response!

**Comment by jtac** [comment]
out of curiosity, what kind of custom instruction would you want to do using an image?

**Comment by jegan221724** [comment]
To use UI/UX screenshots as reference

**Comment by saoudrizwan** [comment]
It's not possible adding images to the system prompt. Maybe you can ask claude to give a detailed description of the images and add that to custom instructions?
