### ISSUE TITLE
can not paste text to the coder input box.

### ISSUE THREAD

**Issue by mehdifanai** [saoudrizwan/claude-dev#129]
When the open router is selected and either mistral-large or deep seek-coder is selected, Command+V or right-click -> paste does not work for any (simple) text. my text is for example: "simple". It does work for anthropic sonnet 3.5 and some others.
![CleanShot 2024-08-18 at 21 22 48@2x](https://github.com/user-attachments/assets/ef1dc105-c9ff-42c4-a232-a7ccc6a5ebbe)

**Comment by soulforsoup** [comment]
Having the same issue here.

**Comment by HugoFang** [comment]
+100

**Comment by saoudrizwan** [comment]
Fixed in v1.5.1
