### ISSUE TITLE
Super product, shitty tokens/min

### ISSUE THREAD

**Issue by lars67** [saoudrizwan/claude-dev#130]
Claude Dev. is such a cool and efficient product, I absolutely love this - but the extreme limitations from Antropic on both total rates and the god damn **429 {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit**  is an absolute killer. Normally 10-15 minutes then I hit the wall and continue on ChatGpt
I find myself joggling between ChatGPT, Mistral and Claude dev in the cooling period. and ClaudeDev has to read the changes

Ooohh, I look so forward to more realistic per minute rates that will reflect the workstyle. (A la ChatGpt).
(I work on very small python and react projects)

**Comment by ChristianWeyer** [comment]
Couldn't we add an option where we can provide several API keys that point to several accounts? And when we hit the 429, Claude-Dev automatically swaps the key @saoudrizwan ?

**Comment by ChristianWeyer** [comment]
> > Couldn't we add an option where we can provide several API keys that point to several accounts ?
> 
> I do that since a week but manually 😇

Exactly...

**Comment by SamPink** [comment]
I dont understand why you would need to do this, when you can just move to a higher tier on Anthropic.

**Comment by 720pixel** [comment]
I hope ClaudeDEV will soon support local LLMs like DeepSeek Coder V2.

Absolutely love ClaudeDEV, however I ended up spending nearly $30 on a single project through OpenRouter last night. I know I could save a lot using Antropic's API but the limits imposed by Anthropic are a joke.

**Comment by kiranmaya** [comment]
@720pixel 
deepSeek Coder v2 dont have tool use /function calling inbuilt into model ,with prompt engineering ,we can do with some extend.

 you can use deepseek Coder v2 with LmStudio and openRouter
see here https://github.com/saoudrizwan/claude-dev/issues/122

**Comment by saoudrizwan** [comment]
@720pixel local models are on the roadmap friend (ollama doesn't support tool calling for rest servers out of the box yet)

**Comment by saoudrizwan** [comment]
For people running into rate limit issues I highly recommend switching to OpenRouter, I've been working with them to fix some issues on their end and it's become a lot more stable with larger files. They've also mentioned they're working on adding prompt caching, and I'll update claude dev as soon as I can with that.

**Comment by saoudrizwan** [comment]
Leaving this issue open as a place to talk about rate limits + getting token usage lower. Both areas I'm actively trying to address and will update on progress here

**Comment by pietz** [comment]
AWS Bedrock also has much higher rate limits or is the box.

**Comment by ChristianWeyer** [comment]
> For people running into rate limit issues I highly recommend switching to OpenRouter, I've been working with them to fix some issues on their end and it's become a lot more stable with larger files. They've also mentioned they're working on adding prompt caching, and I'll update claude dev as soon as I can with that.

Do you have some instructions on how to do this @saoudrizwan? Thanks!

**Comment by 720pixel** [comment]
>  They've also mentioned they're working on adding prompt caching, and I'll update claude dev as soon as I can with that.

Great news. Looking forward to that.

**Comment by drcggray** [comment]
@saoudrizwan Thanks so much for trying to improve the token limits. I've fallen in love with your amazing Claude Dev product!! It's enabled me to do things that were just not possible for me before. I don't have coding training; I am a medical doctor. But your amazing Claude Dev tool is helping me build health sector solutions that I couldn't before. Thanks so much! You're an absolute legend! Thanks everyone for posting here! I am hitting the token limit barrier too!!

**Comment by drcggray** [comment]
Hi everyone. Just letting you know that I implemented the OpenRouter solution that @saoudrizwan suggested and it is working well. I'm building myself a personal goals tracker!

**Comment by saoudrizwan** [comment]
@drcggray we'd love to see your project in the discord! https://discord.gg/claudedev
