### ISSUE TITLE
How to set a system prompt?

### ISSUE THREAD

**Issue by joegiglio** [saoudrizwan/claude-dev#135]
I would ask this question in a Github discussion but I don't see such an option...

Question about the system prompt.  I see a section for "Custom Instructions" but nothing for "System Prompt".

Anthropic's help says to set the system prompt in the code.  Does Claude-Dev support this?

I also asked on Twitter but never received a reply: https://x.com/ChiefRemote/status/1824531914612461663

**Comment by fry69** [comment]
Is this what you are looking for -> https://github.com/saoudrizwan/claude-dev/issues/128#issuecomment-2295277395

**Comment by joegiglio** [comment]
If that setting adds to the system prompt, and the system prompt is not set, will this setting become the system prompt?  If so, then yes... this would work.
