### ISSUE TITLE
Blank screen on http://localhost:3000/

### ISSUE THREAD

**Issue by iCloudsPWASaaS** [saoudrizwan/claude-dev#138]
Blank screen on http://localhost:3000/ After cd webview-ui && npm run start

**Comment by fry69** [comment]
Claude Dev is a VSCode extension, the webview-ui is meant to run inside VSCode, not standalone.

**Comment by iCloudsPWASaaS** [comment]
Hi, if i run from vscode and press F5 on terminal, its just show build finish and extension also did not load.

**Comment by fry69** [comment]
Check the terminals for error, probably something went wrong (can happen when you run a development version).

**Comment by iCloudsPWASaaS** [comment]
It dose not work with GROQ baseURL: "https://api.groq.com/openai/v1", but always shows Making API Request...
<tool_use>{"tool_calls":[{"id":"call_pending","type":"function","function":{"name":"attempt_completion"},"parameters":{"result":"Task completed successfully."}}]}</tool-use> and at end Claude Dev has reached the maximum number of requests for this task. Would you like to reset the count and allow him to proceed?

**Comment by saoudrizwan** [comment]
GROQ support is on the roadmap https://github.com/saoudrizwan/claude-dev/issues/47
