### ISSUE TITLE
Will this be available for VSCodium?

### ISSUE THREAD

**Issue by sunilodedra** [saoudrizwan/claude-dev#140]
Hi Saoud! The project looks amazing, I'd love to try it but honestly would rather swallow a grenade than install VSCode (MS is evil!) :joy:  Opensource VSCodium is a great platform but looks like they don't have Claude-Dev in their extensions marketplace. Are there any plans to publish to (https://open-vsx.org) ??  

Some [more info here](https://github.com/VSCodium/vscodium?tab=readme-ov-file#extensions-and-the-marketplace)  on steps needed

Thanks,:)
Sunny

**Comment by pydevcs** [comment]
Follow instructions to build Claude Dev locally and then build a .visx file to install in vscodium

git clone https://github.com/saoudrizwan/claude-dev.git

cd claude-dev

npm run install:all

npm install -g vsce

vsce package

Install from VSIX...

**Comment by saoudrizwan** [comment]
Just published to Open VSX, give that a try! https://open-vsx.org/extension/saoudrizwan/claude-dev

**Comment by SunnyOd** [comment]
> Just published to Open VSX, give that a try! https://open-vsx.org/extension/saoudrizwan/claude-dev

Yess!! Thank you Saoud! :smile_cat:

**Comment by SunnyOd** [comment]
Hi Saoud. Is it possible to make the openvsx repo sync with the main vscode repo? Looks like the extension is out of date :thinking:

**Comment by saoudrizwan** [comment]
@SunnyOd yes my bad, I will upload the next update to open vsx!

**Comment by SunnyOd** [comment]
Sorry to be a pita :blush:  I'm not sure if this is of any use but I think it might be possible to use github actions to automate publishing of vscode extensions across multiple repos. I found this, but tbh don't fully understand it:

https://dev.to/sourishkrout/the-github-action-you-need-to-publish-vs-code-extensions-1n8 

Thanks so much. Looking forward to trying the new features, they look **insane** :heart_eyes:

**Comment by saoudrizwan** [comment]
No not a pita at all, thank you for being so kind about me neglecting the vscodium users. I will try to be more ontop of it moving forward! BTW v1.5.20 is now available with features like ollama support, edit claude's suggestions in the diff view, new regex search file tool to help claude find TODOs/FIXMEs, and more!

**Comment by SunnyOd** [comment]
You're such a ledge dude! Thanks, I already see 250+ downloads on VSCodium :) Thanks for supporting FOSS! :heart:

**Comment by bernardgut** [comment]
Man this is great! Thanks. 

Quick question @saoudrizwan : I see this in vscodium:

![Image](https://github.com/user-attachments/assets/a82106b4-45c2-43f9-a99b-1f3a42b109ba)
