### ISSUE TITLE
Add better prompts against lazy coding to avoid placeholder comments

### ISSUE THREAD

**Issue by mrkmirca** [saoudrizwan/claude-dev#141]
![image](https://github.com/user-attachments/assets/050d689c-f320-4a1f-9e13-e1b8906884b9)

like the title says...

**Comment by 720pixel** [comment]
Faced the exact same issue. 

`  {/* ... (other form fields remain unchanged) ... */}`

Faced this multiple times today. Instead of adding new changes and merging, it tried to replace everything. 

I've seen a lot of posts on r/ClaudeAI/ regarding recent Claude behavior. But I don't know if this has anything to do with it.

**Comment by jmchat** [comment]
I also have this issue with the fact that it only changes a part and add the rest stays unchanged but then deleting everthing else 👎 
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/31a4dd50-3cf4-4035-836b-d0ac0a90718b">

**Comment by saoudrizwan** [comment]
I just tweaked the tool prompts a bit in v1.3.41, can you please give that a try and see if you're still dealing with this issue?

**Comment by 720pixel** [comment]
![2024-08-22_21-20](https://github.com/user-attachments/assets/8e8abfe4-6ef0-4014-a747-59e05e7a6822)

@saoudrizwan Updated the extension. Still facing this randomly.

**Comment by gfsysa** [comment]
Been adding the following to the custom instructions:

> Handling Non-Relevant Code — Never Delete Code to Bypass It: Avoid removing code even if it’s temporarily irrelevant. The existing code may provide valuable context, comments, or serve as a future reference. Focus only on modifying the lines required.

For sessions with a lot of requests, when the context drifts a bit, you can brute force it... don't approve, don't reject, just reprompt with that message 3 times or so, usually does the trick.

**Comment by brianschroeter** [comment]
This unfortunately has gotten so much worse. It doesn't seem to happen on Anthropic's API, but does on Bedrock and OpenRouter now and I never really had this issue before. I tried your suggested prompt @gfsysa just now and it _does_ seem to have corrected itself. Thank you.

**Comment by 720pixel** [comment]
> It doesn't seem to happen on Anthropic's API,

Well, it does for me. But I've noticed it only happens on big files. Like in my case, this happens only when it tries to modify homepage.js which is 531 lines.

**Comment by brianschroeter** [comment]
I spoke too soon. It's happening there now too.

**Comment by IncreaseWebDev** [comment]
Yup... this issue was apparent before with anthropic.com with pro account only sometimes. I would ask for the whole file, and it would correct. Now it's not. 

UGH.

**Comment by aaronbferrell** [comment]
Same issue

**Comment by Pgz1975** [comment]
this works for me :

You must NEVER replace any existing code with placeholders of the type " // ... (previous code remains unchanged)" or " // ... (other functions remain unchanged)" or " // ... (rest of the code remains unchanged)" or variants. 
Instead, you must only modify the specific functions that need to be updated or add new ones.

**Comment by brianschroeter** [comment]
@Pgz1975 I tried this prompt instruction as well, but it doesn't seem to be working on my end. :/ It might work if I push it multiple times - but at two times so far (plus custom instructions), it's still trying to remove the whole file.

**Comment by brianschroeter** [comment]
Thank you so much for continuing to update the extension. I was *so* excited to see that this is being addressed. Unfortunately, I still see it happening on my end. :(

**Comment by saoudrizwan** [comment]
v1.5.6 now let's you edit Claude's changes before accepting! When he edits or creates a file, you can modify his changes directly in the right side of the diff view. You can even hover over a 'Revert Block' arrow button in the center to undo `// rest of code here` shenanigans when he deletes a bunch of code.

**Comment by markmircea** [comment]
> Been adding the following to the custom instructions:
> 
> > Handling Non-Relevant Code — Never Delete Code to Bypass It: Avoid removing code even if it’s temporarily irrelevant. The existing code may provide valuable context, comments, or serve as a future reference. Focus only on modifying the lines required.
> 
> For sessions with a lot of requests, when the context drifts a bit, you can brute force it... don't approve, don't reject, just reprompt with that message 3 times or so, usually does the trick.

and spend a quarter with each reply, ive specifically told it not do delete my code but it does it anyway. I have to manually copy and paste the modified code many times, when there are alot of changes it becomes frustrating

**Comment by workingwheel** [comment]
Is there a fix for this...I kind of started to like Claude Dev. Especially since it has been saving me lots of time, but when it decides to delete 300+ lines of code it does take me for a ride. =)

**Comment by saoudrizwan** [comment]
I've just created a wiki guide to help work around this issue, I hope this helps! https://github.com/saoudrizwan/claude-dev/wiki/Troubleshooting-%E2%80%90-Claude-Deleting-Code-with-%22rest-of-code-here%22-Comments
