### ISSUE TITLE
Unable to connect to the aws bedrock from the IDE plugin

### ISSUE THREAD

**Issue by Rockstarravo** [saoudrizwan/claude-dev#142]
when i'm trying to establish the connection by feeding my aws keys with required permissions, it is unable to set the connection in, addition prompting this below issue. Kindly assist me on this pls.

Suspecting that AWS keys creation  & feeding isn't enough yet, i might be missing some thing from AWS console.

<img width="387" alt="image" src="https://github.com/user-attachments/assets/8f958764-0abf-444b-b38b-19a3f9e3b3d1">

**Comment by freiit** [comment]
you need to activate the model in Bedrock first. go to aws website and enable the model. 3.5 is only available in us-east

**Comment by BlackDahlia313** [comment]
> you need to activate the model in Bedrock first. go to aws website and enable the model. 3.5 is only available in us-east

this was my issue as well ty. I was on us-east-2 and the bedrock page didnt have the get started part. ty
