### ISSUE TITLE
Deepseek caching capabilities

### ISSUE THREAD

**Issue by epireve** [saoudrizwan/claude-dev#144]
It has come to the community's attention that DeepSeek has announced their support for caching, similar to the capabilities offered by Claude. More details can be found in their announcement here - https://platform.deepseek.com/api-docs/news/news0802/.

Any plan or information on regarding the possibility of implementing caching support for OpenRouter/DeepSeek with the current architecture?

Best,
FA

**Comment by saoudrizwan** [comment]
DeepSeek is on the roadmap! Closing as duplicate https://github.com/saoudrizwan/claude-dev/issues/119
