### ISSUE TITLE
Prompt token length is larger than limit (199999), are there ways to delete old conversations in the contexts?

### ISSUE THREAD

**Issue by jxonexuan** [saoudrizwan/claude-dev#145]
Just want to keep the current conversation moving forward, some older conversations or context might not valuable anymore, are there way to delete the prompt context so that I can keep using the same conversation?

I try save the conversation and ask the agent to read it again to regain context, but the agent will stuck in infinitely loop from time to time..

**Comment by truetrev** [comment]
+1 this would be great

**Comment by lars67** [comment]
Ditto - that´s a killer

**Comment by saoudrizwan** [comment]
v1.5 now has sliding window context management to let you keep tasks going indefinitely!
