### ISSUE TITLE
Feature Request: Foldable Task Panel

### ISSUE THREAD

**Issue by btiger** [saoudrizwan/claude-dev#147]
Can the task panel be made foldable to reduce its large size, which currently covers 1/3 of the height?  Just like this
![Snipaste_2024-08-22_08-34-03](https://github.com/user-attachments/assets/6b41b3ab-2656-4d23-b47d-db85890b4263)

**Comment by saoudrizwan** [comment]
This is a great suggestion! Thank you

**Comment by btiger** [comment]
> This is a great suggestion! Thank you

you are welcome

**Comment by saoudrizwan** [comment]
Closing as it's now added in the latest version!
