### ISSUE TITLE
Extension for Visual Studio 2022 (not VS Code)

### ISSUE THREAD

**Issue by AllyourBaseBelongToUs** [saoudrizwan/claude-dev#149]
Is it a lot of trouble to release this as an extension for Visual Studio 2022 ?

Or is the difference between VS Code and the Bigger IDE too big?

**Comment by saoudrizwan** [comment]
It's a much different process making extensions for vs2022. Although it's not on the roadmap for now, if there's enough of a demand for it I will definitely look into it! Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/63
