### ISSUE TITLE
Extension Hangs when Hitting Rate Limit

### ISSUE THREAD

**Issue by mikecfisher** [saoudrizwan/claude-dev#15]
The extension is pretty cool but I'm having 2 issues. 

1. I'm hitting claude per minute pretty quickly and easily. 
2. When I hit the rate limit the extension freezes and I'm unable to enter new prompts. 

Unfortunately until this is addressed the extension is more or less unusable for me. 
Very cool concept though!

**Comment by mkearl** [comment]
Yes once this happens I lose all context and there is no way to retrieve or continue.

**Comment by iHopist** [comment]
Yup, the same. It becomes unusable, so the only way to use it again it to restart vscode.

**Comment by saoudrizwan** [comment]
v1.0.4 now has the ability to retry failed requests + many memory optimizations that should fix the freezing issues during long conversations. Please feel free to re-open if you continue to face any of these issues.
