### ISSUE TITLE
Keeps crashing during interactions

### ISSUE THREAD

**Issue by dsjacobsen** [saoudrizwan/claude-dev#150]
# Claude.dev VS Code Extension Crashing and Losing Chat History

## Description
I've been experiencing issues with the Claude.dev extension in VS Code. The extension frequently crashes during chat interactions and "restarts" itself without saving any history. This results in having to start over with the conversation from scratch because Claude.dev forgets all the previous context.

## Steps to Reproduce
1. Open VS Code
2. Start a conversation with Claude.dev extension
3. Engage in chat for a period of time (exact duration varies)
4. Extension crashes and restarts

## Expected Behavior
The extension should maintain stability during chat interactions and preserve conversation history even if a crash occurs.

## Actual Behavior
The extension crashes unexpectedly, and upon restart, all previous conversation history is lost.

## Environment
- VS Code version: 1.92.2
- Claude.dev extension version: [v1.3.41 
- Operating System: MacOS 14.6.1 (23G93) on M1 MAX
- Anthropic API (PRO subscription)

## Additional Information
- Frequency of crashes: Approximately every 2-3 minutes of use.
- Any error messages observed: Clears the chat, reloads the tab and history is not saved. 

## Impact
This issue significantly hampers productivity as it requires restarting conversations and re-explaining context to the AI assistant repeatedly so though its generally impressive, its useless for real productivity boosts.

**Comment by saoudrizwan** [comment]
I have not seen this happen before! Could you please provide a screenrecording eg with loom so I can get a better idea of what's going on?

**Comment by dsjacobsen** [comment]
@saoudrizwan I haven't been able to record the error happening today, I tried few times but the reload didn't happen while recording. I will re-open and send you a recording if I am able to catch it while recording.
