### ISSUE TITLE
Suggestion: allow disabling each tool if it's not needed

### ISSUE THREAD

**Issue by looeee** [saoudrizwan/claude-dev#152]
I found that the ability to allow the model to run console commands was quite cool, but in practice not that useful. 
For example, if whenever I needed to enter a y/n or other data, it would fail and waste an api request. So I quickly started denying the requests to run commands and ran them manually instead. 

I would find it useful to just be able to turn off the tool and have the model suggest commands for me to run.

**Comment by saoudrizwan** [comment]
I just made some improvements to executing commands where you can interact with a terminal emulator directly in chat, please try it out in v1.5.16 and let me know if it works any better for you
