### ISSUE TITLE
Anthropic API Connection Request Failed on VS Code

### ISSUE THREAD

**Issue by latitudeki5223** [saoudrizwan/claude-dev#154]
I keep getting a 401 {"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"}}  I have uninstalled, reinstalled multiple times.  I have changed my api-key 3 times. There is credit on the account.  Im not have any luck, any suggestions.  I was using Calude-dev last week, but as my chain length got to long I stopped, because it was not handling the long chain well.  But I got through that prob and now wish to use it again, but I am not able to?  Have you any suggestions.

**Comment by saoudrizwan** [comment]
Hey sorry you're dealing with that. Can you try using openrouter? (Settings > API Provider > OpenRouter). If you're still seeing the same issue, this might be more than an api error and could be something wrong in the extension.

**Comment by latitudeki5223** [comment]
Hi. I'll give that a go and report back. Great product. Bit quick to chew the tokens. But really handy. CheersTony Get Outlook for AndroidFrom: Saoud Rizwan ***@***.***>Sent: Friday, August 23, 2024 5:03:18 pmTo: saoudrizwan/claude-dev ***@***.***>Cc: latitudeki5223 ***@***.***>; Author ***@***.***>Subject: Re: [saoudrizwan/claude-dev] Anthropic API Connection Request Failed on VS Code (Issue #154)
Hey sorry you're dealing with that. Can you try using openrouter? (Settings > API Provider > OpenRouter). If you're still seeing the same issue, this might be more than an api error and could be something wrong in the extension.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/saoudrizwan/claude-dev/issues/154#issuecomment-2306473816",
"url": "https://github.com/saoudrizwan/claude-dev/issues/154#issuecomment-2306473816",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by danghieuan** [comment]
@saoudrizwan Hello, do you any updates? I'm waiting to fix this issue.

**Comment by latitudeki5223** [comment]
Hi. Sorry. Won't be back at it to the morning  I'll update you then.CheersTonyGet Outlook for AndroidFrom: An Dang-Hieu ***@***.***>Sent: Friday, August 23, 2024 8:52:36 pmTo: saoudrizwan/claude-dev ***@***.***>Cc: latitudeki5223 ***@***.***>; Author ***@***.***>Subject: Re: [saoudrizwan/claude-dev] Anthropic API Connection Request Failed on VS Code (Issue #154)
@saoudrizwan Hello, do you any updates? I'm waiting to fix this issue.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/saoudrizwan/claude-dev/issues/154#issuecomment-2306882738",
"url": "https://github.com/saoudrizwan/claude-dev/issues/154#issuecomment-2306882738",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by latitudeki5223** [comment]
Hi, Im just trying again now for you… I just tried anthropic in openrouter and got API Request Failed

401 Missing Authentication header or invalid API key…This is the error just straight in claude-dev…API Request Failed

401 {"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"}}

**Comment by latitudeki5223** [comment]
I tried my open ai key in open router and that didn’t work either.

**Comment by saoudrizwan** [comment]
You need to use an openrouter api key https://openrouter.ai/
