### ISSUE TITLE
Extension does not load - TypeError: Cannot destructure property 'selectedModelInfo' of '(0 , a.useMemo)(...)' as it is undefined.

### ISSUE THREAD

**Issue by sammcj** [saoudrizwan/claude-dev#155]
After installing the extension and click on the Claude Dev icon an empty window pane is all that is displayed.

There are no errors in the UI.

- VSCode 1.92.2
- macOS

Looking at the developer console I see a few errors from the extension:

<img width="2495" alt="image" src="https://github.com/user-attachments/assets/a7a34191-156f-4fe7-805e-5aa46c5af9a4">

```
TypeError: Cannot destructure property 'selectedModelInfo' of '(0 , a.useMemo)(...)' as it is undefined.
    at Gb (main.js:2:1373227)
    at mi (main.js:2:77627)
    at Cs (main.js:2:91853)
    at wl (main.js:2:138161)
    at vc (main.js:2:126384)
    at bc (main.js:2:126312)
    at mc (main.js:2:126175)
    at ac (main.js:2:122955)
    at rc (main.js:2:121506)
    at E (main.js:2:755529)
ds @ main.js:2
n.callback @ main.js:2
$a @ main.js:2
Sl @ main.js:2
vl @ main.js:2
yl @ main.js:2
(anonymous) @ main.js:2
kc @ main.js:2
rc @ main.js:2
E @ main.js:2
_ @ main.js:2
main.js:2 Uncaught TypeError: Cannot destructure property 'selectedModelInfo' of '(0 , a.useMemo)(...)' as it is undefined.
```

**Comment by saoudrizwan** [comment]
Did you use another branch that used a different model? This should only happen if your local state had a provider that wasn't the 3 claude dev offers. If not then I'll need to investigate further

**Comment by sammcj** [comment]
I did! I first tried a fork to see if I could get it working with Ollama / any OpenAI compatible endpoint.

I thought removing the extension, restarting vscode would have been enough?
