### ISSUE TITLE
Add Model Hermes 3 405B Instruct from OpenRouter Provider or/and Custom Model Configurations

### ISSUE THREAD

**Issue by instocky** [saoudrizwan/claude-dev#156]
All available models are listed in the selected provider's list. 
Please add a new model **Nous: Hermes 3 405B Instruct**. 

### Addition
Models appear quickly. Access to a json file with customizations and the ability to add them yourself would be a good solution.

**Comment by saoudrizwan** [comment]
Hey thanks for the suggestion! Not every model works in claude dev bc openrouter sometimes doesnt map toolcalling properly, or the models themselves arent great at understanding complex tool schemas/autonomous loop execution. I've personally tested every one of openrouter's models that support tool calling and claude & gpt4o were the only models worth a dime. That said, I'd be more than happy to add more models but will probably need to add a disclaimer to expect them to not perform as expected.

**Comment by instocky** [comment]
Understood the reason for Hermes' absence. Thanks for the quick reply.

**Comment by danividalg** [comment]
Hi @saoudrizwan, anyway, it could be great to be able to write a custom model for OpenRouter, with a disclaimer if needed, but at least be able to test it, thanks :)

**Comment by saoudrizwan** [comment]
@danividalg you can still test it! Just use Settings > OpenAI compatible and input the openrouter details manually

**Comment by danividalg** [comment]
Hi @saoudrizwan, I can't get openrouter to work using the OpenAI Compatible option :(
I set Base URL to https://openrouter.ai/api/v1 and Model ID to nousresearch/hermes-3-llama-3.1-405b:free
Where is the problem ?
Thanks for your help :)

**Comment by smailsw** [comment]
> Hi @saoudrizwan, I can't get openrouter to work using the OpenAI Compatible option :( I set Base URL to https://openrouter.ai/api/v1 and Model ID to nousresearch/hermes-3-llama-3.1-405b:free Where is the problem ? Thanks for your help :)

same here

**Comment by danividalg** [comment]
I think that the problem is the model, because it does not support tools
with other models it works
