### ISSUE TITLE
OpenAI compatible API support

### ISSUE THREAD

**Issue by zyzhang1130** [saoudrizwan/claude-dev#159]
From my own testing sonnet 3.5 now is worse than gpt-4o. Can I request to make gpt-4o available on claude dev as well?

**Comment by danghieuan** [comment]
@zyzhang1130 You can use API Provider with OpenRouter for GPT-4o.

**Comment by zyzhang1130** [comment]
@danghieuan I only have OpenAI API key. Can you make directly querying from OpenAI an option?

**Comment by danghieuan** [comment]
@zyzhang1130  It integrated in Claude-dev. Pls check setting of extension.

**Comment by zyzhang1130** [comment]
> @zyzhang1130 It integrated in Claude-dev. Pls check setting of extension.

Only OpenRouter  has option for OpenAI model (unless I missed something), and it does not accept OpenAI API.

**Comment by saoudrizwan** [comment]
OpenAI + custom base URLs are coming

**Comment by candalfigomoro** [comment]
@saoudrizwan Is this available in v1.4.0 Preview?

**Comment by juancarlosm** [comment]
> OpenAI + custom base URLs are coming

Great! That will support LiteLLM! So new models and local ollama will be available :)

**Comment by saoudrizwan** [comment]
OpenAI compatible APIs are now supported in v1.5.19, this is very much experimental especially for ollama so please try it out and let me know how it goes!

**Comment by candalfigomoro** [comment]
@saoudrizwan For the "sliding window context management", are you considering the fact that these models have a context length lower than 200k (eg. 128k for gpt-4o)?

**Comment by ctwhome** [comment]
Which url for openai can we use? it looks like `https://api.openai.com` is ont working for me.
<img width="903" alt="image" src="https://github.com/user-attachments/assets/7875f869-98d7-4206-9625-c7f9c598e7d6">



<img width="822" alt="image" src="https://github.com/user-attachments/assets/b8dfa102-cad8-4cb6-8a80-aedcd3fc3bf6">

**Comment by BartNetJS** [comment]
Use https://api.openai.com/v1
