### ISSUE TITLE
Caching + Changing the Api Key

### ISSUE THREAD

**Issue by windy31** [saoudrizwan/claude-dev#160]
Hello, that's more of a question than a problem.
If i'm using caching and change the api key, as far as i understand, the claude backend thinks that it's a different chat(i might be wrong, sorry if i am).
Hence the caching system breaks once i change the api key, since it "stays" with previous chat and api key in the backend of claude ai?

Let's say i work with API1, give the code to cache and everything.
Then i change to API2(since i've used more than 1mil tokens)
All the previous caching is still intact and system uses its correctly, or there's some reason to not do that?

==End of the main question==

Also, a real newbie question, would be great if somebody would answer this aswell - i've seen some good changes in pull requests, is it hard to use them in my version of claude-dev so i might do some testing for those pulls? Cause there're some features which i've really wanted.

**Comment by saoudrizwan** [comment]
Hello! You're right about caching being tied to the account/api key, so in your case it will not be able to reuse caches.  
As for the PRs, you just need to git clone them, follow the instructions in the readme (under Contribution) and you can run it in a debugger or use vsce package to create a vsix that you can download (similar to an update).
