### ISSUE TITLE
The recursive search does not seem to work in files in hidden directories

### ISSUE THREAD

**Issue by paj80paj** [saoudrizwan/claude-dev#164]
Description - created by Claude. dev - Great extension by the way!!

The AI assistant was unable to locate the user-specific Talon configuration file, specifically the 'foam.talon' file, despite multiple attempts using various file search and read operations.

Steps to Reproduce:

User requested to add a new Talon command to the Foam VSCode configuration.
AI attempted to locate the file using the following methods:
Searched in /Users/paulj/.talon/user/knausj_talon/apps/vscode
Searched in /Users/paulj/.talon/user/knausj_talon/apps
Attempted to create a new file in /Users/paulj/.talon/user/
Searched in /Users/paulj/.talon
AI was unable to find or access the correct file until the user provided the exact path.
Expected Behavior:
The AI should be able to locate user-specific Talon configuration files, especially those related to frequently used applications like VSCode.

Actual Behavior:
The AI was unable to find the 'foam.talon' file and had to rely on the user to provide the exact file path.

Additional Context:

The correct file path was: /Users/paulj/.talon/user/MyTalonConfig/foam.talon
The AI has permission to read and write files in the user's Talon configuration directory.
The issue may be related to incomplete or incorrect information about the user's Talon directory structure.
Possible Solutions:

Improve the AI's knowledge of common Talon configuration directory structures.
Implement a more robust file search algorithm that can traverse user-specific directories.
Add a capability for the AI to ask for specific directory information when dealing with Talon configurations.
This ticket should help the developers understand the issue and work on improving the AI's ability to locate and work with user-specific Talon configuration files.

**Comment by saoudrizwan** [comment]
Ah so it isnt that claude couldnt view contents of hidden directories but just that it didn't know how to look for your talon config files. This is an interesting gap in claude's knowledge, but you could paste in talon docs in 'Custom Instructions' if you do a lot of tasks related to it.
