### ISSUE TITLE
Error: Invalid problemMatcher reference: $esbuild-watch

### ISSUE THREAD

**Issue by vladstudio** [saoudrizwan/claude-dev#169]
Cannot really contribute anything: local repo does not start debugging. Here's the video:

https://github.com/user-attachments/assets/06320ed9-976c-4196-9c85-86e43591df93

**Comment by saoudrizwan** [comment]
Can you try installing this extension and see if it fixes the issue https://marketplace.visualstudio.com/items?itemName=connor4312.esbuild-problem-matchers

**Comment by vladstudio** [comment]
woo-hoo! that helped, no more error, and a new VSCode window opens successfully. Thanks! I would never guess to fix this with an extension. 

If this extension is required for contributing, perhaps it makes sense to add a note in readme.md (that's where I looked up the setup instructions).

Thanks again.

**Comment by saoudrizwan** [comment]
Done! https://github.com/saoudrizwan/claude-dev/commit/43e30d3f7671686fef0927e816321fb4b4464141
