### ISSUE TITLE
Hang on NPM library install when confirmation required

### ISSUE THREAD

**Issue by BigMucho** [saoudrizwan/claude-dev#17]
When the agent runs an NPM install that requires the user to confirm a step or make a selection there doesn't appear to be a way to interact with the console/terminal for the user to respond. See below:

<img width="361" alt="confirmation" src="https://github.com/user-attachments/assets/73377518-9c0b-4a23-8eae-3b81d804642a">

**Comment by shannonlal** [comment]
@BigMucho do you have an example prompt or description so we can properly test.  Also can you confirm the following:
- VS Code Version
- OS Version

**Comment by saoudrizwan** [comment]
Just released v1.0.6 that now has support for interactive and long running CLI commands. When a command expects input, you can send a message like normal and it will be streamed to the subprocess's stdin. For long-running processes or non-returning commands, there is now an 'Exit Command' button as well.
