### ISSUE TITLE
Feature request: editable change

### ISSUE THREAD

**Issue by zyzhang1130** [saoudrizwan/claude-dev#174]
I find it a bit annoying when Claude Dev attempts to modify my existing script and most of its change is good, except maybe a few lines are problematic; because in this case, I cannot edit those lines. When I accepted the change, I lost track of the changes. Therefore, I'd appreciate it if the changes made by Claude Dev were editable as opposed to read-only (I tried to do it myself but ran into strange issues and unfortunately could not run the extension locally).

**Comment by looeee** [comment]
Is this actually possible? I think it uses the built in VSCode diffing mechanism and I think that doesn't allow edits.

**Comment by zyzhang1130** [comment]
> Is this actually possible? I think it uses the built in VSCode diffing mechanism and I think that doesn't allow edits.

I'm thinking of using the same way when you compare different versions of commits to do it. Not sure if it is feasible as I have not tried it yet.

**Comment by saoudrizwan** [comment]
This is now possible in v1.5.16! Demo of this in action: https://x.com/sdrzn/status/1829873616441278915

**Comment by zyzhang1130** [comment]
Fantastic!
