### ISSUE TITLE
TOOL: Add "receive all imports"

### ISSUE THREAD

**Issue by windy31** [saoudrizwan/claude-dev#179]
Right now i get alot of errors because claude doesn't consider all the files that use the file i'm editing as an import. That's because to receive all files like that it needs to read all the files.
Maybe create a simple tool that would search for all the imports in the project and let claude dev to use this info to fix the mistakes with imports?
Or create simple "search and replace" so it would programmatically, without mistakes replace the names for functions or packages?

**Comment by saoudrizwan** [comment]
v1.5 adds a new `search_files` tool that lets Claude perform regex searches in your project, making it easy for him to refactor code, address TODOs and FIXMEs, remove dead code, and more!
