### ISSUE TITLE
Claude Dev use shortcuts and suggested edits would destroy code base in many instances. This frequent Code suggestion creates inefficient token consumption

### ISSUE THREAD

**Issue by m-marinucci** [saoudrizwan/claude-dev#182]
In many instances Claude dev is lazy and suggests to edit existing code file with placeholders like

` # ... (other methods remain unchanged)`
 
 instead of entire well functioning code blocks 
 
 No kidding I caught this misbehaviour so many times and this is so annoying since consumes tokens unnecessarily!!
 
 Despite giving the system prompt this entry "DO NOT USE CODE SHORTCUTS like.... in your suggestion" Claude keeps this stupid behaviour. 
 
 Any hint how to mitigate this??

**Comment by dancingmadkefka** [comment]
This is what made me realize that it is actually rewriting the entire file each time it edits. I wonder if there is a way to have claude only provide the required code snippets and then claude-dev can intelligently place them into the files? This would be amazing.

**Comment by CiberNin** [comment]
> This is what made me realize that it is actually rewriting the entire file each time it edits. I wonder if there is a way to have claude only provide the required code snippets and then claude-dev can intelligently place them into the files? This would be amazing.

Not doing this is a very explicit decision. Papers have come out showing that strategy results in lower quality code, and dev time is better spent on other features that won't just automatically get better and cheaper when new models come out.

**Comment by dancingmadkefka** [comment]
> Not doing this is a very explicit decision. Papers have come out showing that strategy results in lower quality code, and dev time is better spent on other features that won't just automatically get better and cheaper when new models come out.

Fair enough. Got a link to those papers by any chance, am curious to read.

**Comment by looeee** [comment]
The best solution I have found (not just for Claude but all LLMs) is to make sure your code consists of small and focused modules. It's mostly when the file goes beyond a few hundred lines that it starts truncating. 

I also *think* it's more likely to do this when a file does several different things, in which case it will truncate unrelated functionality with a `this section unchanged` type comment.

**Comment by CiberNin** [comment]
Yeah. Some of the most impressive stuff I've seen done involved working on code with a single file per function almost.
https://gist.github.com/VictorTaelin/ea437a1bcdcbe026c61c434114ce7b34

**Comment by saoudrizwan** [comment]
v1.5.6 now let's you edit Claude's changes before accepting! When he edits or creates a file, you can modify his changes directly in the right side of the diff view. You can even hover over a 'Revert Block' arrow button in the center to undo `// rest of code here` shenanigans when he deletes a bunch of code. Demo here: https://x.com/sdrzn/status/1829873616441278915

**Comment by dancingmadkefka** [comment]
> v1.5.6 now let's you edit Claude's changes before accepting! When he edits or creates a file, you can modify his changes directly in the right side of the diff view. You can even hover over a 'Revert Block' arrow button in the center to undo `// rest of code here` shenanigans when he deletes a bunch of code. Demo here: https://x.com/sdrzn/status/1829873616441278915

Ah that's nice, thanks for the heads up :)

**Comment by dancingmadkefka** [comment]
> The best solution I have found (not just for Claude but all LLMs) is to make sure your code consists of small and focused modules. It's mostly when the file goes beyond a few hundred lines that it starts truncating.
> 
> I also _think_ it's more likely to do this when a file does several different things, in which case it will truncate unrelated functionality with a `this section unchanged` type comment.

That's the case for me too actually.
