### ISSUE TITLE
Local Inference Option???  We need to save money please !

### ISSUE THREAD

**Issue by m-marinucci** [saoudrizwan/claude-dev#183]
One should be able to select local inference LLM through LM studio for instance or directly with Ollama

Thanks!

**Comment by ajnart** [comment]
@m-marinucci  I believe the following PR will address just that: https://github.com/saoudrizwan/claude-dev/pull/162

**Comment by saoudrizwan** [comment]
Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/95
