### ISSUE TITLE
Where to change the API?

### ISSUE THREAD

**Issue by MaximPro** [saoudrizwan/claude-dev#187]
Hi, I was using the 5$ API Anthropic gave me, however I have now a new account with more credits.

But I can't find, where the API is right now on the VSCode Extension and on the mac.

Please let me know and also make it more obvious.

Thanks and have a great Day ;)

**Comment by DeletedByAccident** [comment]
> Hi, I was using the 5$ API Anthropic gave me, however I have now a new account with more credits.
> 
> But I can't find, where the API is right now on the VSCode Extension and on the mac.
> 
> Please let me know and also make it more obvious.
> 
> Thanks and have a great Day ;)

<img width="800" alt="Code_25KwFDxjXq" src="https://github.com/user-attachments/assets/6f3b6b82-6e8d-4bb3-ac3b-ae477c468beb">
<img width="800" alt="Code_01oN1ufqZP" src="https://github.com/user-attachments/assets/734fcbed-1176-40e4-8e3c-d3827b942cf0">
<img width="800" alt="Code_7hre8ZzCmY" src="https://github.com/user-attachments/assets/b5cf9a96-ec30-44a2-9188-de8fccd3abfe">

**Comment by DeletedByAccident** [comment]
<img width="800" alt="Code_NdB8eeoV2Z" src="https://github.com/user-attachments/assets/4e291404-a538-4287-9b90-6c4e16f040d4">

**Comment by MaximPro** [comment]
Awesome, thank you! :)

**Comment by saoudrizwan** [comment]
Thank you @DeletedByAccident
