### ISSUE TITLE
Prompt caching write grows much more than expected

### ISSUE THREAD

**Issue by ClaudiuHNS** [saoudrizwan/claude-dev#190]
Cache writes increases way more than expected. After doing the task of creating a file (tokens count of the file's content is 1489), the total prompt **Output** grows by aprox. **1700** tokens which is fine (from 20146 to 21913), but the Prompt **caching write** grows by aprox. **38000** tokens (from 155615 to 193972).

Before prompt
![before-prompt](https://github.com/user-attachments/assets/e4edd7df-9b37-429b-a4ee-7a13c3f91fee)
After receiving response
![after-response](https://github.com/user-attachments/assets/4af19b1a-67e3-40e9-a0bb-f4e7602ce303)

I did ask in the first prompt to read project structure and the content of all files. 

Is it caching again existing files it already cached?

I measured the token amount of the codebase before starting and it was around 25000 tokens

**Comment by CiberNin** [comment]
note that per claude docs cache currently always expires after 5 min.

https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

**Comment by saoudrizwan** [comment]
Thank you @CiberNin, and also worth noting that adding images to the chat will reset the prompt cache as well.

**Comment by ClaudiuHNS** [comment]
Maybe this could be implemented in ClaudeDev too.

Aider v0.53.0 can **keep your prompt cache from expiring**. It can ping the Anthropic every 5min to keep the cache warm with --cache-keepalive-pings.

Preventing cache expiration
Aider can ping the provider to keep your prompt cache warm and prevent it from expiring. By default, Anthropic keeps your cache for 5 minutes. Use --cache-keepalive-pings N to tell aider to ping every 5 minutes to keep the cache warm. Aider will ping up to N times over a period of N*5 minutes after each message you send.
