### ISSUE TITLE
Feature Request - Use a git repository to track changes

### ISSUE THREAD

**Issue by jakenuts** [saoudrizwan/claude-dev#191]
When a coding project begins it would be really helpful if Claude-Dev optionally did this:

1.) Initialize a git repository or create a new branch if one already exists
2.) Commit each substantive file change to git with a brief comment describing what changed
3.) Remove these commands/outputs from the message context so they don't replace real work
4.) Possibly include the git commit messages as an history of the operations which might assist in planning and avoidance of repeating tasks that failed too long back to appear in the context.

I totally understand this is not something you have time to do, but I just wanted to note it down here in case someone (or I) do so in the future. 

Thanks so much!

**Comment by CiberNin** [comment]
I do think there is potential in having the "write file" tool explicitly as for a commit message to go with the file edit. Even if its not actually committed. Could be use for context window summarization.

**Comment by saoudrizwan** [comment]
You can do this with Custom Instructions, e.g. "After completing a task or making significant changes, automatically run `git add . && git commit -m` with a message summarizing the recent updates."

I've thought about making this its own option in settings "Enable automatic git commits" but figured people have their own tastes for how they want claude to do this, ie how often to commit, how to structure commit messages, etc.

**Comment by saoudrizwan** [comment]
Closing for now, please re-open if you think there's a better solution here
