### ISSUE TITLE
WebView UI Toolkit sunsetting

### ISSUE THREAD

**Issue by DaveSanders** [saoudrizwan/claude-dev#195]
Please kill this if this is already known or on another issue, but: I just (re)found this project and extension today and was looking through the source and noted the use of vscode-webview-ui-toolkit.  Since I have not built any VSC extensions, I went down a quick rabbit hole to understand what this is doing for my own knowledge, and stumbled across this:

https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561

It appears Microsoft is sunsetting the ui library you are using and you might need to swap it out / upgrade it.  They talk about various options, and it looks like the community is working to replace it.

Just wanted to put it on your radar in case it wasn't already.

**Comment by saoudrizwan** [comment]
Thanks, I saw this earlier and was sad! It looks like other devs are building their own community version, and facebook has their own react library too https://github.com/facebook/sapling/tree/main/addons/components

**Comment by atljoseph** [comment]
https://github.com/vscode-elements/elements, if you haven't seen it.

**Comment by superlazyname** [comment]
Any updates on this? It looks like vscode-webview-ui is still being used in the project, but it's been sunset since January of this year.

Is there a plan to replace this library with something else?

**Comment by entrepeneur4lyf** [comment]
> Any updates on this? It looks like vscode-webview-ui is still being used in the project, but it's been sunset since January of this year.
> 
> Is there a plan to replace this library with something else?

I just thought I would share this.

https://github.com/vscode-elements/elements
