### ISSUE TITLE
Add Theming and Style Customization Options

### ISSUE THREAD

**Issue by vsvito420** [saoudrizwan/claude-dev#197]
hello i want to change the font size in claude dev with CTRL - / CTRL + or with buttons. maybe also add changable fonts ;).
i would love if the tool could download fonts like jetbrains automaticly if wanted

**Comment by saoudrizwan** [comment]
ATM claude dev tries to match your vscode theme as closely as possible. No plans to have customizable styling but if there's something in particular you'd like that you can't do with changing your theme pls lmk.
