### ISSUE TITLE
Web ui has import issues

### ISSUE THREAD

**Issue by Cally99** [saoudrizwan/claude-dev#198]
Hi, 
Great extension actually. Kind of mind blowing you can use it on a large stack and it follows your design pattern around your project helping you in many ways.

I've got an issue as I'm trying to add a few more LLM api's since the ones listed I've trialled even with paid subscriptions break down with rate limiting. 

I've added Llama three but it won't take my api key from the provider. I've never worked with vscode extensions before and I had to create a visc file and manually add my fork to test. Is the web ui for debugging? It's got some import errors due to two src folders and I don't know much about vs code plugins. 

Can you update the documentation of how to debug the vscode ui?
Thanks,

**Comment by saoudrizwan** [comment]
You'll need to run `npm run install:all` to install all the dependencies including in the webview-ui. There's instructions you can look at under the Contribute secton on the readme for more specifics. 
What API are you trying to add? If you're running into rate limits I suggest open router, they should have prompt caching soon which will significantly reduce costs.

**Comment by AnsonLai** [comment]
I had the same issues running it locally on Windows 11.  I just resorted to copying the shared folder over and redoing the imports.  Not ideal but it's an easy fix.

**Comment by saoudrizwan** [comment]
Ah I see my webpack script wasn't working for you guys on windows. I just updated it, pls pull the latest and let me know if you still run into issues
https://github.com/saoudrizwan/claude-dev/commit/81fa5a67a45e289dc66cdc93aaf7982a78d89a97

**Comment by AnsonLai** [comment]
That didn't really fix it hahaha

**Comment by AnsonLai** [comment]
I think the webpack is working now.  Still having some trouble on Windows though.
Activating extension 'saoudrizwan.claude-dev' failed: Cannot find module 'c:\Users\Phara\Desktop\Projects [Current]\[Completed]\YouTube Projects\claude-dev-legal\1.5.6\claude-dev\dist\extension.js' Require stack: - c:\Users\Phara\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

**Comment by AnsonLai** [comment]
Seems like it should work, I'm not sure why I'm still running into issues.  That said, instead of moving things around with the shared folder, I am able to fix it just by running "npm run build:webview" manually once, which your code clearly does.  Maybe it's out of order.  Weird, but if anyone is running into the same issue, try building it independently.

**Comment by jernejpregelj** [comment]
> Ah I see my webpack script wasn't working for you guys on windows. I just updated it, pls pull the latest and let me know if you still run into issues [81fa5a6](https://github.com/cline/cline/commit/81fa5a67a45e289dc66cdc93aaf7982a78d89a97)

This issue is still present in latest main. Tested it on Win and Mac. Running "npm run build:webview" does not solve the problem. Is there symlink that I'm missing?

**Comment by chi-cat** [comment]
Yes; I also noticed that this issue has not been resolved; I tried the following solutions:
1. Directly using "Start Debugging" to launch the plugin cannot debug webview-ui (breakpoints in webview-ui all indicate they are unbound), so I looked for related issues in [vscode issue 145292](https://github.com/microsoft/vscode/issues/145292); I tried enabling the inline-source-map option in tsconfig.json, but it still generated "*.js.map" files.
2. Directly using the external "start:webview" and internal "start" commands; both prompted Failed to compile.
```Translated Text:```
Module not found: Error: You attempted to import ../../../../src/shared/combineCommandSequences which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
ERROR in ./src/components/chat/ChatRow.tsx 10:0-111
Module not found: Error: You attempted to import ../../../../src/shared/combineCommandSequences which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

ERROR in ./src/components/chat/ChatTextArea.tsx 7:0-91
Module not found: Error: You attempted to import ../../../../src/shared/context-mentions which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

ERROR in ./src/components/chat/ChatView.tsx 11:0-56
Module not found: Error: You attempted to import ../../../../src/shared/array which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

ERROR in ./src/components/chat/ChatView.tsx 12:0-79
Module not found: Error: You attempted to import ../../../../src/shared/combineApiRequests which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
```Translated Text:```


Is there anything I have missed; please point it out

**Comment by chi-cat** [comment]
> Yes; I also noticed that this issue has not been resolved; I tried the following solutions:
> 
> 1. Directly using "Start Debugging" to launch the plugin cannot debug webview-ui (breakpoints in webview-ui all indicate they are unbound), so I looked for related issues in [vscode issue 145292](https://github.com/microsoft/vscode/issues/145292); I tried enabling the inline-source-map option in tsconfig.json, but it still generated "*.js.map" files.
> 2. Directly using the external "start:webview" and internal "start" commands; both prompted Failed to compile.
> 
> ```
> Module not found: Error: You attempted to import ../../../../src/shared/combineCommandSequences which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> You can either move it inside src/, or add a symlink to it from project's node_modules/.
> ERROR in ./src/components/chat/ChatRow.tsx 10:0-111
> Module not found: Error: You attempted to import ../../../../src/shared/combineCommandSequences which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> You can either move it inside src/, or add a symlink to it from project's node_modules/.
> 
> ERROR in ./src/components/chat/ChatTextArea.tsx 7:0-91
> Module not found: Error: You attempted to import ../../../../src/shared/context-mentions which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> You can either move it inside src/, or add a symlink to it from project's node_modules/.
> 
> ERROR in ./src/components/chat/ChatView.tsx 11:0-56
> Module not found: Error: You attempted to import ../../../../src/shared/array which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> You can either move it inside src/, or add a symlink to it from project's node_modules/.
> 
> ERROR in ./src/components/chat/ChatView.tsx 12:0-79
> Module not found: Error: You attempted to import ../../../../src/shared/combineApiRequests which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> You can either move it inside src/, or add a symlink to it from project's node_modules/.
> ```
> 
> Is there anything I have missed; please point it out

If you, like me, need to debug webview-ui, you need to add the following code.

https://github.com/cline/cline/blob/main/webview-ui/scripts/build-react-no-split.js#L116

```javascript

config.devtool = 'inline-source-map';

```

Then, after running the extension (F5), you can debug through the source code panel of the developer tools by pressing Ctrl+Shift+I. I hope this can help those who come after (but I still haven't found a way to directly debug webview-ui with breakpoints in VS Code; all breakpoints within webview-ui prompt as unbound in VS Code)
