### ISSUE TITLE
It would be nice to have the option to maybe log a conversation so that if you needed it you could get all of the information

### ISSUE THREAD

**Issue by mkearl** [saoudrizwan/claude-dev#20]
In the event that something crashes or there is a problem it would be nice to have a log of some type.  Maybe in the settings give the user an option to log chats.

**Comment by saoudrizwan** [comment]
Task history is on the roadmap, although I have considered the idea of creating an export button to create a markdown file for example.

**Comment by saoudrizwan** [comment]
v1.0.6 now has the ability to export tasks to markdown. This can be useful as context for future conversations, and you have the freedom to strip out anything irrelevant or summarize certain sections to keep token count low.
