### ISSUE TITLE
Feature Request: use Task completed summary as git commit message

### ISSUE THREAD

**Issue by chrisdumler** [saoudrizwan/claude-dev#200]
It would be incredible to more easily move the "Task Completed" summary to the git commit message. Currently this seems unusually hard to copy/paste long summaries.

**Comment by saoudrizwan** [comment]
You can do this with Settings > Custom Instructions, and adding something like "After completing a task or making significant changes, automatically run `git add . && git commit -m` with a message summarizing the recent updates."
