### ISSUE TITLE
Changing Api Key

### ISSUE THREAD

**Issue by Ahmedkhmi** [saoudrizwan/claude-dev#202]
Thanks Saoud for this awesome extension. 
Im trying to use several Claude Api Keys, but once i use a key i could not change it.
I tried uninstalling and reinstalling the extension but it didn't work.
I don't know if i missed something, but it would be nice if someone can help me out.

**Comment by saoudrizwan** [comment]
Hi Ahmed, please see this comment https://github.com/saoudrizwan/claude-dev/issues/199#issuecomment-2320340922
