### ISSUE TITLE
[Feature Request] Add toggle to give blanket permission to read files

### ISSUE THREAD

**Issue by 1200bps** [saoudrizwan/claude-dev#205]
Just as in the title—I'm not working with a private codebase, so having to give approval to the bot each time it needs to read a file (especially a file that I've already given it permission to read in the context of the current task) is a little annoying.

Thank you all very much for your work on this—I've been test-driving Claude Dev alongside Cursor.sh, and I've found that I prefer it!

**Comment by emshvac** [comment]
If you have one of the newer versions please click your settings button and check "Always allow read-only operations"


![image](https://github.com/user-attachments/assets/965ac978-2404-4797-9725-37488e2b7a4a)
