### ISSUE TITLE
use cheap claude haiku to start and prefill a new task

### ISSUE THREAD

**Issue by gkrawiec** [saoudrizwan/claude-dev#208]
When debugging something, sometimes it takes several attempts to fix something. Often the full context of the task includes a lot of useless information, such as the previous unsuccessful attempts to fix the issue. 
In order to save money, maybe you could implement a feature that uses Haiku to analyzes the thread and extract and summarize only the useful information from the thread and create a new task including this summary with each new attempt at fixing the problem. This might reduce the cost. 
Using the cache is great, but still could be optimized. I often find myself with a cache in the hundreds of thousands of tokens simply debugging a previous task.

**Comment by saoudrizwan** [comment]
I talk a bit about the design philosophy behind claude dev [here](https://github.com/saoudrizwan/claude-dev?tab=readme-ov-file#contribution) and something I think is important is to not add stopgaps that will be rendered pointless when a new cheaper/better model comes out. If you want to create a summary of a task using haiku, I suggest using the claude web interface and pasting in the 'export .md' file there.

**Comment by saoudrizwan** [comment]
Actually your suggestion made me thing of an interesting custom instruction - "At the end of each task, create a ./task-summary.md. At the beginning of each new task look for a ./task-summary.md file to read to get context about the last task done in this project."
