### ISSUE TITLE
Temporary files created when Claude creates/edits files are appearing in Recent Files list

### ISSUE THREAD

**Issue by cosmix** [saoudrizwan/claude-dev#209]
With the new changes in 1.5.6 which allow editing of Claude Dev modified files, a side effect is a slew of temporary files cluttering the 'open file' dialog, which makes it hard to open the right file, especially after a reasonably long 'clauding' session.

**Comment by saoudrizwan** [comment]
Can you show a screenshot of what you mean? When you approve/deny an edit, it should automatically close the diff view.

**Comment by cosmix** [comment]
Hey. "I apologise for the oversight" etc., my description was somewhat vague. So, the problem is in the inherent way vs.code handles recently opened files. I cannot provide a shot right now, but here are the steps to reproduce:

1. Open a workspace with your files.
2. Use claude.dev to perform one or more tasks that involve a few of the files in the workspace.
3. Press Ctrl/Cmd-P to switch to another file in your workspace. Let's say you want to open `fourier.rs`.

Expected Behaviour:

I'd expect to see the files in the workspace that fuzzy match `fourier.rs`

Actual Behaviour:

I see a list of files including several versions of `fourier.rs` located in `/tmp/<claude dev random temp directory`, along with `fourier.rs`

The problem is that if you have used Claude Dev for a little while, the number of spurious `fourier.rs` files can be overwhelming, slowing you down when you want to switch to a file in your workspace.

Workaround: Clear the recently opened files, either through Ctrl,Cmd-Shift-P -> File: Clear recently opened... or from the file menu.

It'd be nice if this didn't happen in the first place. Perhaps there is a programmatic way for you to achieve this from within Claude Dev.

**Comment by saoudrizwan** [comment]
Thank you for explaining this in so much detail, I see what the problem is now. It looks like vscode offers a `workbench.action.clearRecentFiles` command that would clear the list of recently opened files from the Quick Open menu and the "File" > "Open Recent" menu. But this seems like it actually defeats the purpose of you wanting to open recent files without having to see all the temp files claude dev created. I'm gonna leave this issue open as an enhancement, and if anybody has any suggestions for this I'd love to hear them.

**Comment by cosmix** [comment]
Hello, my pleasure and thanks for your response. When you use the {Ctrl, Cmd}-P shortcut most commonly you’re not interested in recent files, but in files in your workspace. Currently this functionality is impaired due to the way Claude Dev creates/opens temporary files. Clearing the recents, while it may affect some users that are _indeed_ interested in opening a recently opened file, won’t negatively affect those that want to quickly open a file in their workspace. One solution—I’m not sure it’s feasible as I haven’t spent any time looking at the VS code API—might be to not register the temporary files Claude is creating/opening with VS.Code (maybe an option while opening/creating the file?)

**Comment by saoudrizwan** [comment]
Hey friend, I figured out a way to create claude's edits as an in-memory doc to avoid polluting the workspace with a bunch of temp files! Pls update to v1.5.19 and lmk how you like it!

**Comment by cosmix** [comment]
Thanks a bunch @saoudrizwan, appreciate the effort and speed.
