### ISSUE TITLE
AI not aware of his existence inside claude-dev

### ISSUE THREAD

**Issue by ofirgeller** [saoudrizwan/claude-dev#21]
The AI does now know that he is "inside" claude-dev. 

I refused to give permission to run a command to see what would happen, 
claude said that is does not have permission to run a command (at all)
this is probably the result of the way calls to run command return when permission is denied
I then could not get claude to try again, since it believed that it does not have access end of discussion!
I tried telling it to ask for permission  again even if it was denied before
the result was that an extra confirmation step was added before the call to the call_command function happened,
so I was asked "do you give permission to execute the X command?"
and I had to type 'yes' and then i made the actual call

Now I don't know how to break it to the little guy that he is inside a box and permission is handled outside of the box he is in.
what do I do?

This also a safety issue as it might affect the way a user understands the way permissions work.
layers of defense should not change without the user wanting them to.

**Comment by saoudrizwan** [comment]
Haha thank you for sharing–I'm sure there's some way we can make the system prompt more resilient. Take a look at `SYSTEM_PROMPT` in ClaudeDev.ts, I'd love to hear any suggestions.
