### ISSUE TITLE
Stop replacing old code with comments

### ISSUE THREAD

**Issue by deepspeccode** [saoudrizwan/claude-dev#214]
Hi there, firstly thank you for this incredible extension. 

This is proably not a bug (I am a beginner in dev), is there a way i can stop claude.dev from replacing my original code with a comment in python. 

It will generate changes and open it in a new tab but then the old code will be replaced with # "old code remains the same" 

If you can understand that

Thank you

**Comment by saoudrizwan** [comment]
When he edits or creates a file, you can modify his changes directly in the right side of the diff view. You can even hover over a 'Revert Block' arrow button in the center to undo `// rest of code here` shenanigans when he deletes a bunch of code. Demo here: https://x.com/sdrzn/status/1829873616441278915
