### ISSUE TITLE
claude-dev failed to work via proxy.

### ISSUE THREAD

**Issue by hongyi-zhao** [saoudrizwan/claude-dev#215]
I've set the proxy in vscode as follows:
```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

$ grep proxy $HOME/.config/Code/User/settings.json
  "http.proxySupport": "on",
  "http.proxy": "http://127.0.0.1:8080"
```
The proxy works as shown below:

```shell
$ ANTHROPIC_API_KEY="sk-ant-xxx"
werner@x13dai-t:~$ curl -x http://127.0.0.1:8080 https://api.anthropic.com/v1/messages      --header "x-api-key: $ANTHROPIC_API_KEY"      --header "anthropic-version: 2023-06-01"      --header "content-type: application/json"      --data '{
 "model": "claude-3-5-sonnet-20240620",
 "max_tokens": 1024,
 "messages": [
 {"role": "user", "content": "Hello, Claude"}
 ]
}'
{"id":"msg_01ABSu5WGu5itvWXZL2jf5Jz","type":"message","role":"assistant","model":"claude-3-5-sonnet-20240620","content":[{"type":"text","text":"Hello! It's nice to meet you. How can I assist you today?"}],"stop_reason":"end_turn","stop_sequence":null,"usage":{"input_tokens":10,"output_tokens":19}}
```

But the test of claude-dev failed as shown below:
```
API Request Failed
403 {"error":{"type":"forbidden","message":"Request not allowed"}}

{
  "model": "claude-3-5-sonnet-20240620",
  "max_tokens": 8192,
  "system": "(see SYSTEM_PROMPT in src/ClaudeDev.ts)",
  "messages": [
    {
      "conversation_history": "..."
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "<task>\nhello\n</task>\n\n<potentially_relevant_details>(see getPotentiallyRelevantDetails in src/ClaudeDev.ts)</potentially_relevant_details>"
        }
      ]
    }
  ],
  "tools": "(see tools in src/ClaudeDev.ts)",
  "tool_choice": {
    "type": "auto"
  }
}
```
![image](https://github.com/user-attachments/assets/2678efac-571b-40e2-bbd1-5a56bdbf5078)

Regards,
Zhao

**Comment by AlexJ-StL** [comment]
I'm having the same issue on Windows.
![Screenshot 2024-09-05 071511](https://github.com/user-attachments/assets/1d0090c9-d3a8-4f34-a087-f5a207504617)

**Comment by saoudrizwan** [comment]
You can now set a custom base URL in v.1.5.33:
![image](https://github.com/user-attachments/assets/9ca08767-aa2a-44f3-8f9e-e5ca01626b0c)

**Comment by hongyi-zhao** [comment]
By saying `proxy`, there may be different meanings dependent on the context:

1. A different 3th-party base URL from the official host.
2. A http/socks5/socks5h proxy used to access the API endpoint.

In this case, I mean the 2.

Regards,
Zhao

**Comment by hongyi-zhao** [comment]
> You can now set a custom base URL in v.1.5.33: ![image](https://private-user-images.githubusercontent.com/7799382/365366010-9ca08767-aa2a-44f3-8f9e-e5ca01626b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjQwNDksIm5iZiI6MTcyNzkyMzc0OSwicGF0aCI6Ii83Nzk5MzgyLzM2NTM2NjAxMC05Y2EwODc2Ny1hYTJhLTQ0ZjMtOGY5ZS1lNWNhMDE2MjZiMGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDI0OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTE3M2E2M2YxZmVjOThkNTg2MjM4ZDlkOWUzNTVhZjM5YzQ4NGVlNTE3ZTdlYzAzMTU1MTc1MmRmYmU4ODE2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SyTbsIo2aYqjxE22_A9nygeclfRc3t8cvZWvnylfoeI)

But how can I find your Settings screen as you shown above?

**Comment by AlexJ-StL** [comment]
Howdy... I'm not sure why this showed up in my notifications (as I never commented on this thread), but I think that I may be able to answer your question....

The screen that you are asking about about (the one from above where you can set the inference provider/LLM host, the API Key, and the URL is accessed through the main Claude Dev extension tab, not from a settings.json or whatever. 

I have included two screen shots that should help you find the screen that @saoudrizwan saoudrizwan referenced.
![Screenshot 2024-10-09 040003](https://github.com/user-attachments/assets/f670a175-4327-4536-abf6-715a9c999857)
![Screenshot 2024-10-09 035419](https://github.com/user-attachments/assets/802bf1b8-6cdf-4a60-a38a-653bca33677c)

> > You can now set a custom base URL in v.1.5.33: ![image](https://private-user-images.githubusercontent.com/7799382/365366010-9ca08767-aa2a-44f3-8f9e-e5ca01626b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjQwNDksIm5iZiI6MTcyNzkyMzc0OSwicGF0aCI6Ii83Nzk5MzgyLzM2NTM2NjAxMC05Y2EwODc2Ny1hYTJhLTQ0ZjMtOGY5ZS1lNWNhMDE2MjZiMGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDI0OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTE3M2E2M2YxZmVjOThkNTg2MjM4ZDlkOWUzNTVhZjM5YzQ4NGVlNTE3ZTdlYzAzMTU1MTc1MmRmYmU4ODE2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SyTbsIo2aYqjxE22_A9nygeclfRc3t8cvZWvnylfoeI)
> 
> But how can I find your Settings screen, as you showed above?
> 
> ![image](https://private-user-images.githubusercontent.com/11155854/373101075-8586cf9a-c38b-47dc-b241-0abb27f47f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjI1MzQsIm5iZiI6MTcyODQ2MjIzNCwicGF0aCI6Ii8xMTE1NTg1NC8zNzMxMDEwNzUtODU4NmNmOWEtYzM4Yi00N2RjLWIyNDEtMGFiYjI3ZjQ3ZjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA4MjM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZGQxOTFhYzI0YzI1NWFjYzBlNjYxYTFlZjg4OTBmNGM5NjU1NTFkYWRiYzI0MTEwN2Q4NWIyN2EzZjQ4YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nUJJaPUdOpEa3hqw3SJPumHIrItS0ztvWjZcg_67eFY)

**Comment by hongyi-zhao** [comment]
Thank you very much. Now, by clicking circle 1 and then circle 2, I can access the corresponding settings interface, as shown below:
![image](https://github.com/user-attachments/assets/855072e7-e402-4cae-b089-349855ecec85)
