### ISSUE TITLE
How to change the baseurl of api

### ISSUE THREAD

**Issue by koob1018** [saoudrizwan/claude-dev#22]
Due to regional restrictions, I cannot use Claude's official API and can only use a proxy API. Can I change the baseURL of claude-dev by configuring the settings?

**Comment by koob1018** [comment]
Due to regional restrictions, I cannot use Claude's official API and can only use a proxy API. Can I change the baseURL of claude-dev by configuring the settings?

**Comment by saoudrizwan** [comment]
Not currently, but I do plan on adding openrouter support in the future. Closing as there are other tickets to follow that update.

**Comment by saoudrizwan** [comment]
You can now set a custom base URL for the Anthropic API in v.1.5.33:
![image](https://github.com/user-attachments/assets/9ca08767-aa2a-44f3-8f9e-e5ca01626b0c)
