### ISSUE TITLE
LM studio support

### ISSUE THREAD

**Issue by Shehab-Ecstasyandfire** [saoudrizwan/claude-dev#224]
The tool does not support lm studio api.

**Comment by saoudrizwan** [comment]
You can use LM studio by setting your API provider to 'OpenAI Compatible' and then input the values in this guide https://lmstudio.ai/docs/local-server

**Comment by Arnaud3013** [comment]
If stuck with api key with lmstudio, use "noop" as api key. It work.

**Comment by Shehab-Ecstasyandfire** [comment]
i tried still no luck i fill out the api key, base url and the id 
it displays this err 
Cannot read properties of undefined (reading '0')
and this is the server err @ lmstudio
2024-09-12 12:44:00 [ERROR] Unexpected endpoint or method. (POST /chat/completions). Returning 200 anyway
2024-09-12 12:44:28 [ERROR] Unexpected endpoint or method. (POST /chat/completions). Returning 200 anyway

**Comment by Arnaud3013** [comment]
Have you change the port in lm-studio? By default it's 1234, but claude-dev use another.

**Comment by Shehab-Ecstasyandfire** [comment]
yeah, i know how the model id should be like
it would be super helpful if you just post screenshots of your setup so that i can replicate it

**Comment by Arnaud3013** [comment]
![image](https://github.com/user-attachments/assets/7ce92c03-7518-48d7-a485-8f0ef3caeaad)
![image](https://github.com/user-attachments/assets/4ffb03ef-2cf4-42e7-86c4-4eb44edd2fea)
Previously (1.5.x version) i was having results, now i got only 
2024-09-12 15:17:51 [ERROR] Unknown exception during inferencing.. Error Data: n/a, Additional Data: n/a
or
400 "<LM Studio error> Only user and assistant roles are supported!. Error Data: n/a, Additional Data: n/a"
Depending of model.
Hope it help you. On my side, i'm using Continue, it cannot generate project, but i'm more in need of an assistant that a tool doing all by itself.

**Comment by Shehab-Ecstasyandfire** [comment]
it did help, it's working thanks 👌
