### ISSUE TITLE
API Error while using deepseek-coder-v2:16b with Ollama Provider

### ISSUE THREAD

**Issue by Humayun-nisar** [saoudrizwan/claude-dev#231]
I am trying to use Ollama with deepseek-coder-v2:16b. I get a status 400 error when I make an API request against the model. I also tested codegemma:7b-instruct-v1.1-q8_0, and am getting the same error with it as well.

ERROR:

API Request Failed:
400 codegemma:7b-instruct-v1.1-q8_0 does not support tools

**Comment by rushter777** [comment]
It does not appear to like dashes (-) or colons (:) - typing the right one that it understands is difficult.

**Comment by Humayun-nisar** [comment]
Tested it with model id deepseek-coder-v2; still getting the same response:

API Request Failed
400 deepseek-coder-v2 does not support tools

I am assuming it is related to the way the request object is being created for ollama. It works with llama3.1 but have been getting errors similar to this on multiple other models.

**Comment by eiddor** [comment]
See this blurb from the Ollama configuration page:

>Ollama allows you to run models locally on your computer. For instructions on how to get started with Ollama, see their quickstart guide. **You can use any models that support tool use** (Note: Claude Dev uses complex prompts, so less capable models may not work as expected.)

"**You can use any models that support tool use**"

The thing that is confusing me is that I am able to use models like deepseek-coder, codestral, etc. with a different extension and the same back-end Ollama setup, so I'm not sure why the limitation exists, but I suspect it'll be fixed at some point.

**Comment by rushter777** [comment]
And if you click that link, a bunch of models appear that support tool use. I tried the qwen that was there but the model runs with a slash in its name, so that did not work. But it is also a very small model, that could be the issue as well. The only one I have seen that will load in for me was either llama3 or llama3.1 without using the :8b at the end of it. I hope, with all the recent cool updates they have done, this gets looked at a little more.

**Comment by eiddor** [comment]
> I tried the qwen that was there but the model runs with a slash in its name, so that did not work.

So, funny story - On a whim, I decided to test a model with a slash in the name to see if I could fix the code.  It worked for me.

But... I went to the model/tool list again to search for qwen to see if I could figure out what you were seeing, and then I realized that a lot of the more popular models have tool variants.  

I just used `MFDoom/deepseek-coder-v2-tool-calling` and it works like a charm!

**Comment by xiaojichao** [comment]
I use MFDoom/deepseek-coder-v2-tool-calling, and running "Ollama run MFDoom/deepseek-coder-v2-tool-calling", then set in VScode like:
![image](https://github.com/user-attachments/assets/7e4c2a4a-965f-490b-8642-a19269659ce1)

but when I start a new task, it appear " API Request Faild, Connection error"
![image](https://github.com/user-attachments/assets/2c2de771-5f1b-41f8-86fa-726450273a5a)

**Comment by saoudrizwan** [comment]
@xiaojichao were you able to get this working? This is strange, can you pls update to the latest version 1.6.3 and see if a list of ollama models show up in claude dev for you to choose from? If not then something's blocking it from connecting to your local endpoint, hmm

**Comment by saoudrizwan** [comment]
Please see https://github.com/saoudrizwan/claude-dev/issues/230#issuecomment-2340575426
