### ISSUE TITLE
Title: 400 Error when Connecting Claude Dev VS Extension to Local Ollama on Model: deepseek-coder-v2:16b

### ISSUE THREAD

**Issue by qazimuneeb** [saoudrizwan/claude-dev#232]
Issue:

I am encountering a 400 Bad Request error when attempting to connect the Claude Dev VS Code extension to the local Ollama server using the deepseek-coder-v2:16b model. The error prevents the extension from functioning properly when using this specific model.
Steps to Reproduce:

    Install and configure the Claude Dev extension in VS Code.
    Set up the local Ollama server and ensure it is running.
    Select the deepseek-coder-v2:16b model within the Claude Dev extension.
    Attempt to connect to the local Ollama server.

Expected Behavior:

The Claude Dev extension should connect to the local Ollama server and allow interaction with the deepseek-coder-v2:16b model without error.
Actual Behavior:

The extension returns a 400 Bad Request error, preventing successful interaction with the model.

**Comment by rushter777** [comment]
Take off the :16b at the end and try again. I did that with llama3.1:8b, just removed it and it worked. 
But it is so sensitive to the names of the models. I wish it could find your ollama models and list them like Continue does. Devs?

**Comment by ilovebamboo** [comment]
> Take off the :16b at the end and try again. I did that with llama3.1:8b, just removed it and it worked. But it is so sensitive to the names of the models. I wish it could find your ollama models and list them like Continue does. Devs?
https://github.com/saoudrizwan/claude-dev/issues/248
same model,but my project tips
Claude is having trouble...
This may indicate a failure in his thought process or inability to use a tool properly, which can be mitigated with some user guidance (e.g. "let's try breaking this large file down into smaller files").

**Comment by saoudrizwan** [comment]
@rushter777 claude dev now lists models underneath the model id textfield, pls lmk if it works for you!

**Comment by waiwong614** [comment]
Running v1.7.0, I am also encountering a 400 Bad Request error when attempting to connect the Claude Dev VS Code extension to the a Ollama server on the networking using any models. It does display all my models underneath the model id textfield. So, obviously it is able to connect to the server and found all the models. But selecting any models, ex: llama3.1:latest or llama3.1, I get: 400 llama3.1:latest does not support tools.

**Comment by saoudrizwan** [comment]
@waiwong614 will look into this ASAP https://github.com/saoudrizwan/claude-dev/issues/330

**Comment by shivamshayar** [comment]
I am facing the same issue; it's not working with the Ollama local model.

![Screenshot 2024-09-24 162101](https://github.com/user-attachments/assets/21f06821-43c6-4c9b-992b-2f791c815c1e)
