### ISSUE TITLE
Clearing of VS Code recently opened

### ISSUE THREAD

**Issue by emshvac** [saoudrizwan/claude-dev#233]
As the title suggests tmp files created by the extension remain in the search.  Need to clear this for ui/ux reason.

![image](https://github.com/user-attachments/assets/4c59c67f-4d43-4531-8b5b-16ff5aff4eaa)

**Comment by emshvac** [comment]
this occurs after a reload of vs code as well.

**Comment by saoudrizwan** [comment]
Hi please update to the latest v1.5.31, this should prevent this from happening. Please play around with this version as there was a lot of refactoring to file editing in this update, so I'd love to hear if you run into any problems or if you have a good experience with it.

**Comment by emshvac** [comment]
Seems to have resolved the issue.  I will update you if I find something else.  I also messaged you on discord as I have some things that I would like to contribute to the project but they are operations that I created for automated unit test generation.  I think they could really help with your project.
