### ISSUE TITLE
Error: Command Failed with Exit Code 1 (PowerShell not recognized)

### ISSUE THREAD

**Issue by AlexJ-StL** [saoudrizwan/claude-dev#238]
![Screenshot 2024-09-05 140433](https://github.com/user-attachments/assets/18da516f-0e66-47ff-bb4a-2ae29078b9f5)

I have reinstalled PowerShell, ensured the PATH was correct, and attempted everything else that I can think of, but I am stuck. As of right now I'm out of ideas.

**Comment by saoudrizwan** [comment]
Can you follow the instructions in this [stackoverflow thread](https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr/29778651#29778651) and try again?

**Comment by AlexJ-StL** [comment]
> Can you follow the instructions in this [stackoverflow thread](https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr/29778651#29778651) and try again?

I wish it had been the %PATH% that was the problem. Unfortunately, I already verified all that.

However, after rebooting I was able to "Restart" or something like that (I dont remember the exact "restart" word(s) used) and it work. That said, every other approval with about 4 total errors occurred, but when I retried it worked fine. If I am not mistaken I read in another thread that someone had the same behavior.

So, I suppose this is "fixed" for now... We'll just say that it was a "Did you try turning off and on again?"
![download](https://github.com/user-attachments/assets/c975d6a3-f6f7-43ef-add5-1f2170a5dbe9)

**Comment by saoudrizwan** [comment]
Hey @AlexJ-StL, I made a troubleshooting doc to help other users experiencing this issue. Can you pls take a look over it and see if it follows what you had to do to resolve the issue? https://github.com/saoudrizwan/claude-dev/wiki/TroubleShooting-%E2%80%90-%22PowerShell-is-not-recognized-as-an-internal-or-external-command%22

**Comment by AlexJ-StL** [comment]
> Hey @AlexJ-StL, I made a troubleshooting doc to help other users experiencing this issue. Can you pls take a look over it and see if it follows what you had to do to resolve the issue? https://github.com/saoudrizwan/claude-dev/wiki/TroubleShooting-%E2%80%90-%22PowerShell-is-not-recognized-as-an-internal-or-external-command%22

No problem! I'll take a look and get back with you if I have any suggestions.

**Comment by AlexJ-StL** [comment]
> Hey @AlexJ-StL, I made a troubleshooting doc to help other users experiencing this issue. Can you pls take a look over it and see if it follows what you had to do to resolve the issue? https://github.com/saoudrizwan/claude-dev/wiki/TroubleShooting-%E2%80%90-%22PowerShell-is-not-recognized-as-an-internal-or-external-command%22

In reference to your explanation of how to add PowerShell to your %PATH%, I don't have anything to add. Although it is reiterating something simple, its never a bad idea to cover all your bases. Especially when dealing with Windows. We all know how frustrating Windows can be.

That said, I did include a theory about my issue along with a screenshot displaying the possible conflicting PowerShell installations. The screenshot was probably unnecessary, but why not I suppose. I quoted it below for simplicity. I hope that it makes sense. If you have any questions feel free to hit me up. I will be sure to pay attention to my notifications to limit response delay.

"You may want to mention that there is the possibility of conflicts between PowerShell installations. The reason I say that is because I have 2 installations of PowerShell. It is true that it hasn't been an issue before, but today is a new day and this installation of Windows 11 is getting pretty old. So, it might be wise to be mindful of which instance of PowerShell (the default installation or the most recent version from the GitHub repo) the path has first and which path is being used by VS Code. I suggest this because I was unable to arrive at any smoking gun when troubleshooting. The most reasonable thing that I could think of was when I reinstalled PowerShell 7 something changed with how the %PATH% was linked with VS Code or in the relationship between the 2 paths in the System Variables Path. This is somewhat speculative, but the only reasonable explanation that I have. I find the idea that simply rebooting 3-4 times is a sufficient answer. So, take this for what its worth in regards to an explanation."

![Screenshot 2024-09-19 032535](https://github.com/user-attachments/assets/093af677-c4e5-48ee-9a57-812e41876216)

Cheers,
Alex

PS---Fantastic work on Claude-Dev dude... Now that I have been able to use it for a bit, I am very impressed. It has found a place in my tool box amongst few others. So, thank you.

**Comment by saoudrizwan** [comment]
I appreciate the details here Alex! I haven't used windows much so don't really know specifics about powershell issues. I'll be sure to keep this conflicting powershell installation problem in mind if my troubleshooting doc doesn't work for people. Kinda crazy that you had to restart 4 times though, I would have given up after 2 😂
