### ISSUE TITLE
Unable to get it to work with any open ai compatible end point

### ISSUE THREAD

**Issue by AryanEmbered** [saoudrizwan/claude-dev#240]
![image](https://github.com/user-attachments/assets/1ada3843-b6b3-416a-9c40-8ddd882ecb04)

API Request Failed
Cannot read properties of undefined (reading '0')

I'm pretty sure I configured it correctly.
where can I find detailed logs to trouble shoot?

**Comment by saoudrizwan** [comment]
You might need to set the base url to end with /v1?

**Comment by AryanEmbered** [comment]
Yep that worked. not sure why LM studio copy button didn't add it

thanks
