### ISSUE TITLE
Can support add Base URL and custom models id for Anthropic settings？

### ISSUE THREAD

**Issue by edisonzf2020** [saoudrizwan/claude-dev#243]
![image](https://github.com/user-attachments/assets/de68e689-89f7-41c5-ab6f-c8e285753007)

**Comment by laiquziru** [comment]
我也想要

**Comment by saoudrizwan** [comment]
You can now set a custom base URL in v.1.5.33:
![image](https://github.com/user-attachments/assets/9ca08767-aa2a-44f3-8f9e-e5ca01626b0c)

**Comment by edisonzf2020** [comment]
cool
but can unselect "Supports prompt caching" with Claude models ?
Or add Custom name models, Because use the Claude model with Google Vectex AI.
