### ISSUE TITLE
Enhancement: auto-test and auto-lint

### ISSUE THREAD

**Issue by MehrCurry** [saoudrizwan/claude-dev#246]
I am a relatively experienced user of Aider and am now digging into Claude Dev. After fiddling around with Claude Dev i think the auto-test and auto-lint features from Aider may be a good enhancement for Claude Dev, too.

LLMs often make mistakes and a good linter will give fast feedback if the change broke anything. Also, auto-test is very helpful. Once I added an ArchUnit test to my Java project and let Aider execute it, it took the whole experience to another level.

**Comment by saoudrizwan** [comment]
Thanks for the suggestion! Vscode also exposes 'Problems' ie linter issues that I'm thinking of adding in somehow to the task context as claude works.

**Comment by saoudrizwan** [comment]
The latest v1.9.4 now sends *new* linter errors back to claude when he edits files. This way he isn't distracted with older project issues, but still knows when he does something problematic. Please lmk how it works for you!
