### ISSUE TITLE
local run cuda ollama3.1

### ISSUE THREAD

**Issue by ilovebamboo** [saoudrizwan/claude-dev#248]
<img width="493" alt="image" src="https://github.com/user-attachments/assets/e4e0bc6c-7282-4dff-817c-abbecd868ce7">
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/ceb60dc6-8173-4caf-a8f6-c4b7b6414473">
<img width="1335" alt="image" src="https://github.com/user-attachments/assets/0777f6b0-5349-400e-ab0a-ab64b5d201ac">

https://github.com/user-attachments/assets/5b1d3db9-aa3a-436c-a0f9-93b0f0b65893

source https://github.com/MetaCubeX/ClashMetaForAndroid
Claude is having trouble...
This may indicate a failure in his thought process or inability to use a tool properly, which can be mitigated with some user guidance (e.g. "let's try breaking this large file down into smaller files").

**Comment by saoudrizwan** [comment]
Ollama support is very much experimental right now, claude dev has quite a complex system prompt + tool schema so it won't work well with most models. I suggest for any serious tasks you use claude models.

**Comment by AllyourBaseBelongToUs** [comment]
> Ollama support is very much experimental right now, claude dev has quite a complex system prompt + tool schema so it won't work well with most models. I suggest for any serious tasks you use claude models.

The biggest issue is that Ollama limits to 2k token input

Solution:

Create a Modelfile and update the Parameters to at least 8k, though even with 30k it makes mistakes (smaller models mostly) 
could be solved with some custom Prompts, but the API requests dont really show the results that well.

second biggest issue, Claude-Dev keeps reading and feeding itself all the files in the directory, including every single python Package.

which eats up tokenwindow (is it only with ollama and OAI replacement like llamacpp?)

can we have someting like a .gitignore or only read when we approve it?

More granular control over the actions would be nice, like similar to Claude-Engineer or Omni Engineer
