### ISSUE TITLE
Reducing token usage

### ISSUE THREAD

**Issue by AbsoluteMode** [saoudrizwan/claude-dev#25]
Hi thanks for the extension, it's very cool. The only thing is that tokens fly away quickly, what do you think about such a scheme?
Prompt - “add any feature”

System prompt gpt 4o mini - "Display all files that in your opinion affect the addition of a feature"

Sonnet system prompt - "rely on {gpt4omini response} files for response"

**Comment by saoudrizwan** [comment]
That's an interesting multi-agent concept! v1.0.4 has a new `analyze_project` tool that gives Claude an overview of your project's file structures and source code definitions–this should improve its ability to work in an existing project significantly and lead to less API calls/token usage. 
I'm going to close this issue for now as I don't plan on implementing multi-agents, but please feel free to re-open if you are still running into high token issues.
