### ISSUE TITLE
Feature Request: Labeling and search

### ISSUE THREAD

**Issue by emshvac** [saoudrizwan/claude-dev#250]
Would be great to be able to label as well search tasks

Additionally it would be nice to know the model that was used for the task and warn if you are trying to use a different model than when you started with.

**Comment by saoudrizwan** [comment]
Labelling tasks is a cool idea! Pls feel free to add it to the ideas board for others to vote on so I have a better idea of what to work on next: https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas
