### ISSUE TITLE
Feature request: Handle 429 rate_limit_error 

### ISSUE THREAD

**Issue by inhale-tech-root** [saoudrizwan/claude-dev#252]
Error: 
429 {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}

Suggestion: Add a timer and avoid such errors before sending any request.

**Comment by CiberNin** [comment]
According to claude docs the error should be providing how long you have to wait, so could use that to provide a loading bar.

**Comment by inhale-tech-root** [comment]
> According to claude docs the error should be providing how long you have to wait, so could use that to provide a loading bar.

Yes, thank you.

And automatically retry the request after {WAITING_DELAY}+1s.

**Comment by TotalLag** [comment]
I would like to request that this value be customizable. For weird limitations I can't get into, my access to Bedrock is capped at 1 request / minute. It would be nice to not only have the timer, but ETA of total time it would take to do the current job at this rate :)

**Comment by sr4001** [comment]
Another option would be to cycle to a different API key from a different Claude.ai account.  Probably a violation of their TOS though.  Acct1Key returns a 429, retry with Acct2Key.  Once Acct2Key returns a 429, go to Acct3Key if available or back to Acct1Key.  Etc.

Of course, you have to pay for and manage usage across multiple accounts on Anthropic.  The TOS violation might be from one person having multiple accounts, I've not looked into that aspect.

I can do this manually, but it's a hassle.  I could also do it using a local proxy to Anthropic to handle the key switching, but I can't add a local proxy into Claude Dev.

**Comment by Anima-t3d** [comment]
There are a few 429 limits:
1. Tokens per minute
2. Requests per minute
3. Tokens per day

Would be nice to get the header response in this case, so you can see when it will reset (especially the daily limit T_T)
UX improvement would be to show timer once hit, retry if the per minute limit is reached.
Nice to have: 
If say 90% of daily limit is used, show warning.

**Comment by saoudrizwan** [comment]
I might add rate limit info to the task header, but for now if you're running into rate limit issues I suggest using the OpenRouter API option as they now support prompt caching and have much better rate limits

**Comment by redjacketKR** [comment]
face the same issues. and search lead to here.
