### ISSUE TITLE
Suggestion : Trim memory when interrupted during queued tools.

### ISSUE THREAD

**Issue by CiberNin** [saoudrizwan/claude-dev#253]
Occasionally Claude will attempt to invoke multiple tools in a single message, which is very nice and efficient. But if I want to interrupt with some feedback, then the next message all the attempted tool usages after that invocation are still in the memory & I think it causes claude confusion.

Might get better results if when a user types an interrupting message while waiting for tool approval you discard the rest of the claude reply after that tool invocation being denied. That way generation can smoothly continue.

Does that make sense?

**Comment by saoudrizwan** [comment]
This is fixed in the latest version 1.9.4! This was a great suggestion and I'm so glad you brought it up. Now when you reject/respond to a tool use, it will automatically skip the rest of the tools and let claude know they were skipped so he can try again if needed.
