### ISSUE TITLE
Suggestion: Postscript

### ISSUE THREAD

**Issue by CiberNin** [saoudrizwan/claude-dev#255]
I find that system prompt sometimes isn't strong enough and I would like to have a message appended to each of my user messages (but filtered from memory afterwards). 

For instance I like to tell claude to use as many tools in a single reply as possible. This minimizes token usage (even if cache makes it cheap) / roundtrips. 
It usually follows this system prompt for only a couple messages tho before its back to using only one tool at a time.

**Comment by saoudrizwan** [comment]
Please feel free to add this suggestion to the idea board so people can vote on it and give me a better idea of what to work on next: https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas
