### ISSUE TITLE
Feature Request: CLI usage?

### ISSUE THREAD

**Issue by ylluminate** [saoudrizwan/claude-dev#257]
It would be nice to see a generalized function or another project that utilizes `claude-dev` as a CLI tool for direct shell usage perhaps similar to this: https://github.com/vysakh0/dravid

Many would like to use it directly in zsh/fish/bash/etc. / iTerm, emacs, in a more direct fashion.

**Comment by saoudrizwan** [comment]
I don't think this is possible since claude dev relies so much on vscode integrations like running commands in your terminal and upcoming diagnostics monitoring (problems tab). If you have any suggestions to create a cli tool while taking advantage of these integrations, I'd love to hear

**Comment by draxil** [comment]
The correct redirection for emacs uses is probably gptel, which starting to have tool use similar to cline:
https://github.com/karthink/gptel
