### ISSUE TITLE
Running Extension - Error loading webview: Error Could not register service

### ISSUE THREAD

**Issue by shannonlal** [saoudrizwan/claude-dev#26]
I just tried installing Claude Dev on VS Code (see details below) and I am getting the following error

```
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.


```

<img width="476" alt="Screenshot 2024-07-27 at 12 18 05 PM" src="https://github.com/user-attachments/assets/e15de3be-ec9b-4ca8-84ec-11cf1454831a">

I have tried installing from the MarketPlace as well as from source and seem to be getting the same error

Environment: 
Mac M2
VS Code Version: 1.91.1

Does anyone have any insight on how to fix this issue?

**Comment by shannonlal** [comment]
My bad.  Looks like it was a configuration issue on my side.

**Comment by gdoteof** [comment]
I am running into this.  What is/was the configuration issue?

**Comment by 0xDezzy** [comment]
I'm getting this error. and I can't even get the the extension configuration.
