### ISSUE TITLE
Model Selection

### ISSUE THREAD

**Issue by ncd76** [saoudrizwan/claude-dev#262]
I have details added for Claude and Groq (via OpenAI option), **OpenAI is selected but Claude is still being used.**

Suggestions: Add a verify connection button and some sort of current model indicator? 

Thx for making an assistant like it should be..

**Comment by kiranmaya** [comment]
write manually llama3-groq-70b-8192-tool-use-preview
![Uploading Screenshot_8.jpg…]()

**Comment by kiranmaya** [comment]
write model id as llama3-groq-70b-8192-tool-use-preview
![Screenshot_8](https://github.com/user-attachments/assets/d60d0ab0-7e8e-4cf4-a9da-d9b8a57536c6)

**Comment by ncd76** [comment]
![image](https://github.com/user-attachments/assets/4bd7ba23-a918-4ce0-97c1-4767e841ce8c)

Still using Claude.

Also, now just wants to run CLI commands and not provide code changes. No matter what question I ask. Can I install a specific version in VSC?

Thx

**Comment by saoudrizwan** [comment]
The extension will say "Claude wants to" but it's still using the api provider you select. Also YMMV with any non-claude models, the extension works best with claude 3.5 sonnet.
