### ISSUE TITLE
Any plans to add Gemini API?

### ISSUE THREAD

**Issue by wsnbb1234** [saoudrizwan/claude-dev#263]
Google says their latest Gemini 1.5 Pro model, gemini-1.5-pro-exp-0827, has made a significant leap in coding abilities and complex instruction following. Plus, gemini-1.5-pro-exp-0827 is currently free to use. So, are there any plans to add Gemini API for Claude Dev? Thanks!

**Comment by saoudrizwan** [comment]
I'll look into this! I think I'll have to transform anthropic message format to gemini format, thats really the only issue i see but otherwise pretty straightforward

**Comment by Cally99** [comment]
@saoudrizwan I've read that gemini 1.5 is much smoother than claude 3.5 sonnect and has a larger context window. Seems to be the flagship model for this tool from what I've read. No rate limiting and cheaper too.

**Comment by wsnbb1234** [comment]
> I'll look into this! I think I'll have to transform anthropic message format to gemini format, thats really the only issue i see but otherwise pretty straightforward

I really appreciate you including it in your update schedule!

**Comment by saoudrizwan** [comment]
Gemini support is added in v1.6.5! Pls play around with it and let me know if you run into issues

**Comment by wsnbb1234** [comment]
> Gemini support is added in v1.6.5! Pls play around with it and let me know if you run into issues

It runs well! Thanks for your hard work!
