### ISSUE TITLE
I keep getting invalid url even for standard open ai calls

### ISSUE THREAD

**Issue by fedesantamarina** [saoudrizwan/claude-dev#267]
I keep getting invalid url even for standard open ai calls
![image](https://github.com/user-attachments/assets/c422676b-42e9-4dce-b877-bad5a78b4eca)

_Originally posted by @Ethan-Otto in https://github.com/saoudrizwan/claude-dev/issues/216#issuecomment-2336431842_

**Comment by saoudrizwan** [comment]
The base url should be https://api.openai.com/v1
