### ISSUE TITLE
deepbricks support

### ISSUE THREAD

**Issue by mask2012** [saoudrizwan/claude-dev#27]
While I'm using https://deepbricks.ai/, I wonder if there is a way to use DeepBricks' API with something other than Claude? Looking forward to your reply, thank you！

**Comment by saoudrizwan** [comment]
Unrelated but I just released v1.0.9 with OpenRouter and AWS Bedrock support (hit the settings button in the top menu bar > API Provider > OpenRouter). Adding new APIs and models is on the roadmap. There's other open issues for that though, so I'm going to close this ticket for now. Feel free to re-open if you still have any questions or feedback.
