### ISSUE TITLE
Approved file access but stuck in Claude tried to use read_file without value for required parameter 'path'. Retrying...

### ISSUE THREAD

**Issue by subinpauljoy** [saoudrizwan/claude-dev#272]
I asked Claude to look into files and facing this issue
Claude tried to use read_file without value for required parameter 'path'. Retrying...

using gemini through as follows. litellm --model gemini/gemini-1.5-flash

**Comment by saoudrizwan** [comment]
Working on adding native gemini support!

**Comment by mbuhler** [comment]
I am getting a smilar error when trying to do the same thing with the same setup as the OP.  I get this error when asking to write code for a simple test application.   

Claude tried to use write_to_file without value for required parameter 'path'. Retrying...

**Comment by saoudrizwan** [comment]
Pls try using the Google Gemini api provider option, it provides native support that should fix these issues

**Comment by subinpauljoy** [comment]
Hi Saoud, tried the same and I can confirm that its working.
