### ISSUE TITLE
Feature request: add custom `baseURL` support

### ISSUE THREAD

**Issue by Luo-hongyi** [saoudrizwan/claude-dev#28]
I want to use my own endpoint.

**Comment by shannonlal** [comment]
@Luo-hongyi can you provide a bit more context on this?  When you say you want to use your own baseURL is this to support your own model or Claude running in a different environment (i.e. Bedrock)

**Comment by Luo-hongyi** [comment]
I cannot directly access the Claude API due to regional restrictions. I can only use a "proxy" to access it now. So I want to be able to set up the baseURL point to the proxy.

**Comment by saoudrizwan** [comment]
I just released v1.0.9 with OpenRouter and AWS Bedrock support (hit the settings button in the top menu bar > API Provider > OpenRouter). I don't have any plans to provide a custom baseURL option because of how heavily the extension relies on Anthropic's SDK, but I believe you should be able to access Claude through OpenRouter.

**Comment by fdionisi** [comment]
@saoudrizwan is there a change you can reconsider the `baseURL` addition?

It is a configuration option offered by the [Anthropic SDK](https://github.com/anthropics/anthropic-sdk-typescript/blob/e400d2e8a54aa736717ed849ef8b44a3490fce68/src/index.ts#L20-L25), therefore this should be a painless addition.

Including this option would enable my team to use `claude-dev` while following organisational policies.

**Comment by saoudrizwan** [comment]
@fdionisi I see what you mean, sure I can work on adding this!

**Comment by saoudrizwan** [comment]
@fdionisi You can now set a custom base URL for the Anthropic API in v.1.5.33:
![image](https://github.com/user-attachments/assets/9ca08767-aa2a-44f3-8f9e-e5ca01626b0c)

**Comment by gahoo** [comment]
Can we have custom base URL for Google Gemini too? 

The URL seems defined in `google/generative-ai`:

https://github.com/google-gemini/generative-ai-js/blob/2df2af03bb07dcda23b07af1a7135a8b461ae64e/src/requests/request.ts#L25

**Comment by diszone** [comment]
Can we have custom base URL for deepseek too?
