### ISSUE TITLE
Multi LLM USE & SEARCH Engines

### ISSUE THREAD

**Issue by MaximPro** [saoudrizwan/claude-dev#280]
Hey, I would really love to see this with several other Modells, operating together.
Where you also can choose wich model to use, or one model even chooses the models for you based on the tasks...

Please add more Features like that.

**Comment by MaximPro** [comment]
One major Problem with auto coder dev ops is the cutoff of the public llm, so claude and others use old versions of python or github tools.

So we will mostly get an older version then possible. Wich is really bad.

To fix that, it should also use things like perplexity api and better even https://tavily.com/ or open source perplexity alternatives.

It should often use that, to be able to resolve issues and use latest models.
Also a system, that prevents it from doing small repetitive tasks and some memory to not go below version X, when already applied. also to it should be able to research the actual github framework, find and use latest advancements and how to code properly using lastest library from xy.

Please add those important features, as we are wasting lots of api credits with redundant tasks or things, where it makes errors, because of version problems etc.

Please implement those things to make it a whole lot better, but its already really good and thanks for your work :)

**Comment by saoudrizwan** [comment]
Hey thank you for all the great suggestions! Please feel free to add these to our ideas board so people can vote on their favorite feature requests to give me a better idea of what to work on next. https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas
