### ISSUE TITLE
Detect code snipets

### ISSUE THREAD

**Issue by enginrrr** [saoudrizwan/claude-dev#289]
At a certain point Claude is returning code snippets, which then overwrites entire blocks of existing code if you're not paying attention.

Example:

// Keep the existing PHP code unchanged
// ... (previous PHP code remains the same)

It may be super useful to try and detect code snippets and kick out a warning or an error.  Perhaps inject something into the prompt to try and prevent this, or simply make the user super aware of it before they click to accept changes.

**Comment by AndyMik90** [comment]
Was going to report the same, it's very good until it starts doing this. 

Maybe add a verify tool to the agent or a quick check that the "remains the same" is not present in the returned code?

**Comment by quinn** [comment]
Discussing this in #314

**Comment by saoudrizwan** [comment]
I've made a wiki about working around this issue, please lmk if this helps! https://github.com/saoudrizwan/claude-dev/wiki/Troubleshooting-%E2%80%90-Claude-Deleting-Code-with-%22rest-of-code-here%22-Comments
