### ISSUE TITLE
Executes commands outside of Virtual environment

### ISSUE THREAD

**Issue by michaelmegrath** [saoudrizwan/claude-dev#29]
Problem:
In my python/django project claude attempts to execute code using my systems python and fails.  It is able to find the venv python and execute the code successfully after two calls, and it remembers the venv for the rest of the task.  But it does this every new task I start.

Example:
Here is an example of how claude tries to run my code before finding the venv
`python /path/to/project/manage.py makemigrations` **Fails**
`python3 /path/to/project/manage.py makemigrations` **Fails**
`source /path/to/project/venv/bin/activate && python3 /path/to/project/manage.py  makemigrations` **Succeeds**

Question:
Is there a way to check what code interpreter vscode is using for the project and use that? A setting that I can set for the plugin that declares a path to the venv? Or a way to prefix all initial requests with initial instructions?

**Comment by saoudrizwan** [comment]
v1.5.16 now has lets claude know of your python environment!
