### ISSUE TITLE
API request failed

### ISSUE THREAD

**Issue by Tommm07** [saoudrizwan/claude-dev#290]
![image](https://github.com/user-attachments/assets/099e6d7e-a3be-4b4b-a54c-3688c5ffd636)

Not sure why this API request failed, previously I thought I haven't upgrade plan in Anthropic Console. But I already fund and other API can function well.

**Comment by saoudrizwan** [comment]
Can you follow the instructions in this [stackoverflow thread](https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr/29778651#29778651) and try again?

**Comment by Tommm07** [comment]
I tried to add "PATH" variable with %SystemRoot% also cannot.

**Comment by Tommm07** [comment]
Thank! The issue resolved!
