### ISSUE TITLE
FEATURE - Add Support for o1-mini OpenAI

### ISSUE THREAD

**Issue by emshvac** [saoudrizwan/claude-dev#292]
Please add support for the newly released model.

Thanks!

**Comment by saoudrizwan** [comment]
o1 does not support system prompt or tool calling, which are the bread and butter of claude dev. But I'm playing around with getting structured output to try to parse tool calls manually. Will report back if it works!

**Comment by wsnbb1234** [comment]
You don't have to use o1 or o1 mini within Claude dev. They both have similar capabilities to chain-of-thought, so you can just give them your requirements directly

**Comment by saoudrizwan** [comment]
v1.6.8 has o1 support, but please beware that it is very expensive and not that great since it's not made for tool use (I use structured output prompting to achieve the same effect, but this takes a toll on output)
