### ISSUE TITLE
Requested generation length 1 is not possible! 

### ISSUE THREAD

**Issue by robertio** [saoudrizwan/claude-dev#294]
Hi,

Claude dev configured for https://api.sambanova.ai/v1 with Meta-Llama-3.1-405B-Instruct but got this error message:

API Request failed
`Requested generation length 1 is not possible! The provided prompt is 4309 tokens long, so generating 1 tokens requires a sequence length of 4310, but the maximum supported sequence length is just 4096!`

**Comment by msti** [comment]
I got the same error.

**Comment by saoudrizwan** [comment]
This isn't something I can fix unfortunately, seems to be a problem on that particular API provider's end with tool calling

**Comment by robertio** [comment]
Sad. but thX to inform me. 
Thanks for this wonderful extension.  :) I started to use with google api and seems ok.
