### ISSUE TITLE
Add option to disable reading files specified by regex.

### ISSUE THREAD

**Issue by TooCoolName** [saoudrizwan/claude-dev#297]
Hi i want to disable reading of some files in project. It can be done like .gitignore or other ignore where you spcify patterns/regexes which exclude files for usage/indexing.

**Comment by saoudrizwan** [comment]
The best way to do this right now is to go to Settings > Custom Instructions and adding something along the lines of "Do not ask to read or write to the following files <file paths>". In any case claude never reads any files without your permission, the most information that he gets automatically is a list of your project's file paths but aside from that you're in control of what information he gets.

Some of the folks in our discord are thinking through a concept of adding .context/.context-ignore to let you more clearly define what kinds of context you want claude to have from the start or things you want him to ignore. So better support for what you want is in the works!

**Comment by TooCoolName** [comment]
I want to enable option to autoread files but dont want specific files to be read.
