### ISSUE TITLE
 The bot sometimes tries to delete all the code instead of editing parts of the code needed

### ISSUE THREAD

**Issue by alexxety** [saoudrizwan/claude-dev#298]
The bot sometimes tries to delete all the code instead of editing parts of the code needed - you tell him not to delete all the code, he replies that he made a mistake and says that you need to edit only a small part of the code where it is necessary, but then it still deletes all the code
<img width="1202" alt="Снимок экрана 2024-09-14 в 11 27 24" src="https://github.com/user-attachments/assets/d9410e28-ad03-4060-8b56-b34714524db3">
<img width="445" alt="Снимок экрана 2024-09-14 в 11 29 22" src="https://github.com/user-attachments/assets/bca22e90-abcc-462a-9796-ddcafe0cfd5c">

**Comment by saoudrizwan** [comment]
This tends to happen when working on large files. Everytime claude edits a file he has to recreate the entire file's contents so when he runs into max output limits he truncates large blocks like this. To work around this, you can use the revert block button in vscode to undo these truncations (see: https://x.com/sdrzn/status/1829873616441278915), and you have the freedom to directly edit the right side in the diff view to copy paste the deleted content from the left. 

Fortunately Anthropic is about to release a new feature that will make editing existing files much more reliable (and faster), super excited about it and hoping this issue will be a thing of the past.
