### ISSUE TITLE
Add support for additional models and API providers

### ISSUE THREAD

**Issue by mkearl** [saoudrizwan/claude-dev#30]
I would love to use Claude more, but either it is crazy expensive, or I'm limited by rate and or tokens used.  

On a larger project were there are tons of files that need to be evaluated created etc those tokens/rates get eaten up pretty quickly.

With the release of LLAMA 3.1 with tool support how hard would it be to port this... and or give support to a LLM such as LLAMA 3.1 via Ollama or LM Studio?   I may not understand everything Claude offers with artifacts so this may be a dumb question, and if so please forgive me.

Love the latest changes BTW. history and autoaccept are working great.. wish I could use it more.. I have already used up all of my tokens.   LOL.

**Comment by nicucalcea** [comment]
I can't run local models on my machine, but I'd be interested in support for Gemini 1.5 Pro, both because of its large context window, and because usage of the API is free. Their [latest update](https://twitter.com/OfficialLoganK/status/1819041453978357899) seems to be pretty performant, but the point is that it is inevitable that something better than Sonnet 3.5 will come along. I like the way [Continue](https://github.com/continuedev/continue/) implements it.

Anyway, thanks for this, it's really impressive!

**Comment by pathikb** [comment]
+1, this will be so amazing to have! Especially Ollama and OpenAI

**Comment by jadams777** [comment]
I love Claude Dev, but I keep hitting the daily token limit in 1-2 hours of using it. Then it's dead for the next 24 hours, so I have to switch to Aider.

Please add support for a backup LLM, e.g. DeepSeek Coder V2 0724. It's ranked second on Aider's leaderboard.
https://aider.chat/docs/leaderboards/

**Comment by ClaudiuHNS** [comment]
add support for Groq models, they are free unlimited.

**Comment by acidlake** [comment]
it would be amazing if it can support local LM, like ollama, LM Studio etc

**Comment by jtac** [comment]
i believe this project was born from a claude hackathon, so probably quite solidly built on the claude artifacts function

**Comment by jeanjerome** [comment]
The Ollama API is compatible with the OpenAI API. This means that any Ollama model can be called using an OpenAI client.
Claude Dev already integrates an OpenAI-compatible client: https://github.com/saoudrizwan/claude-dev/blob/main/src/api/openrouter.ts
I tried with Llama 3.1, but it gets stuck in a loop and mixes up the user and assistant roles... I think the OpenRouter has some bugs in the message conversion process (?)

**Comment by saoudrizwan** [comment]
v1.1.13 now lets you choose other Claude models (+ GPT-4o, DeepSeek, and Mistral if you use OpenRouter).

OpenRouter only allows tool calling with certain models, and I tested Claude Dev with [each and every one of them](https://openrouter.ai/models?supported_parameters=tools). What I found was most of them did not have the ability to understand complex system prompts/tools the way Claude 3.5 Sonnet can which is what makes something like Claude Dev even possible in the first place.

I'll leave this thread open to keep anyone interested updated on new provider/model support.

**Comment by jadams777** [comment]
Thank you. Which is the best "backup" model to use if we hit Claude's daily token limit?

**Comment by JosephShawa** [comment]
.....
> I'll leave this thread open to keep anyone interested updated on new provider/model support.

You need to make an agent to run through all the "issues" and auto reply that answer. I am sure it will happen with the next models. It is difficult for newbies like myself to grow ideas when there is a lot of fumbling which costs token. What would you think of using the local llm but maybe this is the future: 

"For example, Groq’s infrastructure can be used to implement multi-agent systems, where different AI agents collaborate to perform tasks. [This is evident in projects like the Mixture of Agents (MOA) architecture, which leverages Groq’s LLMs for enhanced AI-driven conversations](https://github.com/skapadia3214/groq-moa)[2](https://github.com/skapadia3214/groq-moa)."

**Comment by jtac** [comment]
@saoudrizwan would you have anything against supporting direct use of OpenAI models from their API?

**Comment by danividalg** [comment]
It could be great if it could be possible to use ollama, deepseek and or openai compatible API :)
Perhaps it could be needed a little bit modifications on prompts to be able to guide the model to reply as expected.

**Comment by sammcj** [comment]
> v1.1.13 now lets you choose other Claude models (+ GPT-4o, DeepSeek, and Mistral if you use OpenRouter).

@saoudrizwan is there any reason we can't provide a custom OpenAI compatible API endpoint?

**Comment by sammcj** [comment]
The reason I ask @saoudrizwan is - I have a working branch that adds OpenAI compatible APIs and lets the user configure their base URL and model in the settings. It works quite well with my Ollama server.

I just want to make sure before I clean it up submit you a PR that there's not some fundamental reason you don't want to allow OpenAI compatible APIs.

<img width="329" alt="SCR-20240823-qsio" src="https://github.com/user-attachments/assets/3ff46367-b459-48e6-9635-0b8c97403301">

<img width="391" alt="SCR-20240823-qurl" src="https://github.com/user-attachments/assets/12411f81-c82b-478e-8e68-517918c5b3ff">

**Comment by saoudrizwan** [comment]
@sammcj no reason I wouldn't want OpenAI as an option! I have something in the works but pls feel free to open a PR

**Comment by sammcj** [comment]
Neat! Thanks for the response @saoudrizwan, That's great you've got something in the works - in that case, perhaps what I'll do is clean my fork up just slightly and share with you via a draft PR, then if there's anything thats useful you can use it - if your implementation is better - you can bin it 😄.

**Comment by sammcj** [comment]
@saoudrizwan https://github.com/saoudrizwan/claude-dev/pull/162, I did it all on a fork and in my fork I changed the name of the extension to avoid clashing etc... hopefully I've brought everything across but there's always a small chance I missed a file so let me know if so :)

**Comment by mkearl** [comment]
I tried using your fork and there are a couple of issues: when trying to modify the model it types over the model so I have to paste it in vs type it.  the base url doesn't save it seems that it always reverts back to openai url.

**Comment by mkearl** [comment]
Nevermind .. it needed: http://localhost:11434/v1

**Comment by sammcj** [comment]
Yeah the way the app is written it doesn’t support models without native tooling.

The PR is just a first attempt but give it a go with llama 3.1

**Comment by saoudrizwan** [comment]
Going to make this the main issue to keep track of model/API requests. Currently on the roadmap:
- [ ] Google Gemini
- [ ] Ollama
- [ ] OpenAI compatible APIs

**Comment by saoudrizwan** [comment]
v1.5.19 now supports OpenAI compatible endpoints! To use ollama use the following:
base url: http://localhost:11434/v1
api key: ollama
model id: llama3.1 (or whatever model that supports tool use) 

Please keep in mind that claude dev uses complex prompts so it may not function nearly as well as claude 3.5 sonnet. I added a new error message in case he makes 3 mistakes in a row (mistakes mean invalid tool calls or no tool call whatsoever), so this should help you guide less capable models in the right direction.
![image](https://github.com/user-attachments/assets/42f5de75-be5f-4a7b-9996-75b0cae30030)

**Comment by sammcj** [comment]
Oh you legend you @saoudrizwan! 🙏 🎉 😍

**Comment by sbchoime** [comment]
thank you for the ollama support.  could you add support to change the base url to http://host.docker.internal to handle dev containers?

**Comment by saoudrizwan** [comment]
@sbchoime the ollama provider is just a convenience option for OpenAI compatible API, so select that and input 
base url: your docker url
api key: ollama

**Comment by Raintimewang** [comment]
Can you support deepseek? https://api.deepseek.com, this model's official link supports caching, the cost is very low but the coding score in aider is extremely high！

> @sbchoime the ollama provider is just a convenience option for OpenAI compatible API, so select that and inputollama 提供者是 OpenAI 兼容 API 的便利选项，因此请选择该选项并输入 base url: your docker url基础 URL：您的 Docker URL api key: ollama API 密钥：ollama

**Comment by saoudrizwan** [comment]
Closing as it looks like we got everybody's provider requests in, deepseek support is gonna be available as soon as they update their API (see https://github.com/saoudrizwan/claude-dev/issues/230)

**Comment by darcula1993** [comment]
the api format looks exactly like a "openai compatible format":
```
POST /v1/chat/completions
Content-Type: application/json
Authorization: Bearer br_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

{
  "model": "claude-3-sonnet",
  "messages": [
    {
      "role": "user",
      "content": "ping"
    }
  ],
  "stream": true,
  "temperature": 1,
  "max_tokens": 4096
}
```
https://github.com/cloudbeer/BRConnector/blob/main/README.md

**Comment by andremohrmann** [comment]
Any news on groq support?

**Comment by c-basalt** [comment]
Given that groq recently added qwen-qwq-32b into their model list, is there any plan to reconsider officially adding groq support.
