### ISSUE TITLE
API Request Failed on Provider of OpenAI Compatible

### ISSUE THREAD

**Issue by hunter001325** [saoudrizwan/claude-dev#300]
Hi, all.
I used gpt-4o by OpenAI Compatible:
![image](https://github.com/user-attachments/assets/13811472-987e-4836-a8ee-9aa376d3fe42)

Claude dev failed to run the request:
![image](https://github.com/user-attachments/assets/aeb5136a-d5ea-4d4a-a18a-dafc88d787ff)

**Comment by saoudrizwan** [comment]
Closing as it's not something I can fix without creating a new API provider that formats the messages for it
