### ISSUE TITLE
Question: Is it possible to define ignore files/folders?

### ISSUE THREAD

**Issue by udiedrichsen** [saoudrizwan/claude-dev#302]
Hi there,

First off, I want to say that the ClaudeDev plugin is fantastic—it's been a great addition to my workflow!

I have a quick question: Is it possible to define specific files or folders to be ignored by the plugin? I’m looking to exclude certain files or directories from being processed or analyzed.

Any guidance on how to set up an ignore list or configure exclusions would be greatly appreciated!

Thanks in advance!

**Comment by saoudrizwan** [comment]
> First off, I want to say that the ClaudeDev plugin is fantastic—it's been a great addition to my workflow!

Thank you for saying this ❤️

> Is it possible to define specific files or folders to be ignored by the plugin?

The best way to do this right now is to go to Settings > Custom Instructions and adding something along the lines of "Do not ask to read or write to the following files `<file paths>`". In any case claude never reads any files without your permission, the most information that he gets automatically is a list of your project's file paths but aside from that you're in control of what information he gets. 

Some of the folks in our discord are thinking through a concept of adding .context/.context-ignore to let you more clearly define what kinds of context you want claude to have from the start or things you want him to ignore. So better support for what you want  is in the works!
