### ISSUE TITLE
Gemini : \r bug?

### ISSUE THREAD

**Issue by vinoudropdrop** [saoudrizwan/claude-dev#303]
I've noticed an issue when using Gemini. Sometimes, \r characters appear at the end of all lines in the output. I'm not sure if this is caused by Gemini or by the integration with claude-dev, but it's randomly creating unexpected behavior. Could you please investigate this and see if there's a way to prevent these extra carriage return characters from appearing? Thank you for looking into this matter.
![image](https://github.com/user-attachments/assets/5c6fb7c4-7d92-4d9e-969d-986244762d82)

**Comment by saoudrizwan** [comment]
That's exactly how I'll fix this @bradlishman 👍 Gemini has a [known issue](https://discuss.ai.google.dev/t/function-call-string-property-is-double-escaped/37867) with function calling where it double escapes certain characters. Will get this fix out ASAP

**Comment by saoudrizwan** [comment]
Fixed in v1.7.1!
