### ISSUE TITLE
Claude Dev - API Request Fail Loop

### ISSUE THREAD

**Issue by edwrdcrpio** [saoudrizwan/claude-dev#304]
<img width="600" alt="Screenshot 2024-09-15 at 6 22 35 AM" src="https://github.com/user-attachments/assets/448e342c-1abe-495b-ba73-0d717a3a8e8b">

Hi Saoud,

Just fyi I am a beginner in GitHub, VS Code, and AI. So apologies if this is a novice issue!

I'm a stuck in a loop with the same API Requested Failed 529 Error (as shown in the attached image) and I've been retrying for about 10-15 mins. I am left with only 1 choice, which is to Start New Task since I cannot type in the prompt field (it's grayed out and not selectable) or somehow cancel the last prompt. I prefer to not Start a New Task. 

What should I do?

Thank you!

**Comment by saoudrizwan** [comment]
Hi there! 529 indicates the server is down, this tends to happen sometimes with Anthropic. I suggest going to settings > API Provider and switching to OpenRouter in the meantime (they have higher rate limits too!)

**Comment by edwrdcrpio** [comment]
Thank you for the quick reply!

Sorry another novice question. Do I need to pay for another API key from OpenRouter? (I'm Tier 2 in Anthropic)

**Comment by saoudrizwan** [comment]
Yes but if you want a free model in the meantime then I suggest Google Gemini, their flash model offers 15 request per minute for free
