### ISSUE TITLE
Feature Request: Markdown/Site URL Indexing for Documentation Updates

### ISSUE THREAD

**Issue by Lightning-Dev** [saoudrizwan/claude-dev#306]
Currently Claude dev relies on the knowledge base of the selected LLM however often the documentation of various frameworks and APIs changes.

A documentation feature where uses could add documentation URLs or markdown files would help Claude Dev stay updated and be able to reference the latest documentation.

Currently Continue.dev has this feature so you could potentially have an integration that is able to work with Continue or build it natively into Claude Dev.  Although if you did build it natively, a setting to choose a second LLM more cost effective just to access the documentation would help to reduce costs.

Attached is a screenshot from Continue.dev showing the site indexing feature.

Thanks for all your great work!

![DocumentationClaudeDev](https://github.com/user-attachments/assets/5b0fe0fb-d53d-49db-86f1-ab32094d7376)

**Comment by saoudrizwan** [comment]
Started working on this yesterday actually!

**Comment by Lightning-Dev** [comment]
Oh wow, that's awesome. You were reading my mind. Thanks a lot.

**Comment by saoudrizwan** [comment]
You can now add links to docs in the text area with the new `@` context mentions feature in v1.8.0! It fetches the contents of the site and converts to markdown format. While it's not docs indexing, I find this much more practical for cases where claude doesn't have knowledge on one particular thing and you can give him a link to the page on that one thing, versus doing janky rag queries on a local docs db.

**Comment by Lightning-Dev** [comment]
That is so awesome! Thanks a lot for for your great work on this. I agree, having the updated docs directly available from the context is the best approach. I also have Firecrawl so I'm looking forward to testing it out with Claude.
