### ISSUE TITLE
Add ability to include message when approving a write_file

### ISSUE THREAD

**Issue by Evizero** [saoudrizwan/claude-dev#308]
I find myself in the position of often wanting to include a little message or instruction when I approve something.

For example: 
1. ClaudeDev requests to write code to a file and I like what I see
2. I know that after this write, it should look into a specific file next as it a complex project and easy to lose track
3. I would like it if i could just enter a message into the instruction text box and it get included in my response when i click "Approve"

We can already do the opposite use-case (rejecting with a message) by just ignoring the buttons and sending a new message. I use that ability quite a lot and its very useful. (mainly to say things like "edit foo.ts first", or "look at types.ts first")

PS: amazing extension. I am blown away how practically useful this way of using LLMs are.

**Comment by beanhilton** [comment]
Plus one for this. I love ClaudeDev, but I often find as I am reviewing code as it marches on, one api call after another. I can see it starting to deviate from the task at hand. Without being able to guide it as I approve saves I have to decide whether to let it finish its train of thought and make a second pass to fix it , or interrupt it and risk a house of cards collapse in the flow often resulting in throwing away the output of the task to that point (so i can get back to a stable starting codebase for the next attempt).

**Comment by saoudrizwan** [comment]
> I am blown away how practically useful this way of using LLMs are.

Thank you for saying this ❤️

> I find myself in the position of often wanting to include a little message or instruction when I approve something

Although the prompt internally frames this as 'the user denied this tool', if you word your feedback in a way that tells claude to retry the edit with your suggestions in mind that should work too. I don't think adding another button here would be as simple as that honestly, although I could make the text input response to edits more neutral in the prompt sent back to claude. If you want this to be its own button and have ideas for a good UX, pls feel free to add them to the ideas board so ppl can vote on it https://github.com/saoudrizwan/claude-dev/wiki/Troubleshooting-%E2%80%90-Claude-Deleting-Code-with-%22rest-of-code-here%22-Comments
