### ISSUE TITLE
Bad request in Anthropic with custom base URL

### ISSUE THREAD

**Issue by AFreeCoder** [saoudrizwan/claude-dev#316]
## Problem
When I use Claude Dev with API Provider Anthropic by custom base URL: https://api.gptsapi.net，An error was occured: 
```
400 {"timestamp":"2024-09-16T15:31:18.348+00:00","path":"/v1/messages","status":400,"error":"Bad Request","requestId":"4d8093cf-233166"}
```
here is my settings:
<img width="419" alt="image" src="https://github.com/user-attachments/assets/eb62547a-a422-4e51-9506-dc65d023d68d">

## Test
I write a curl demo with use URL "https://api.gptsapi.net" and path "/v1/messages":
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/c97fbeb8-6861-4991-b655-715f6bf31cba">
so the URL is no problem.

Begging your reply.
Thank you!

**Comment by amingze** [comment]
![image](https://github.com/user-attachments/assets/9255ffd6-bc12-4433-a7a0-6abcfcc86791)
![image](https://github.com/user-attachments/assets/bab85230-0d0d-48c8-8244-07ccacb9bd34)

**Comment by amingze** [comment]
![image](https://github.com/user-attachments/assets/d0895799-e08f-48b3-aa9e-221f9797e82a)
The picture on the right is the json sent by claude-dev,Their json is different

**Comment by AFreeCoder** [comment]
> ![image](https://private-user-images.githubusercontent.com/45252716/367929120-d0895799-e08f-48b3-aa9e-221f9797e82a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDEzMzgsIm5iZiI6MTcyNjU0MTAzOCwicGF0aCI6Ii80NTI1MjcxNi8zNjc5MjkxMjAtZDA4OTU3OTktZTA4Zi00OGIzLWFhOWUtMjIxZjk3OTdlODJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDAyNDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ODA2NmFkZDM5YTM2OTVlMzliNTk2ODg0NTg5NWVjZmYyN2M5NjBmOWI2ODJlZGY4MzI0OTQ3MThlMGMyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CIrGzYMCkH-ILTlFox9kOzY0U_bXQiVqymnUPN2BKEo) The picture on the right is the json sent by claude-dev,Their json is different



> ![image](https://private-user-images.githubusercontent.com/45252716/367929120-d0895799-e08f-48b3-aa9e-221f9797e82a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDEzODUsIm5iZiI6MTcyNjU0MTA4NSwicGF0aCI6Ii80NTI1MjcxNi8zNjc5MjkxMjAtZDA4OTU3OTktZTA4Zi00OGIzLWFhOWUtMjIxZjk3OTdlODJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDAyNDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlODJhYzY0OGY4NWIzZjU5MzQ3YzQ2NmNhZmJhNGQ2NTQ4MzQ4MDRkMzBlZmQ5NTBkNDI0OTcwMmMzZTA0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VsmEWgMM1L-TNnR-DmiYjay0JJex__-mMF72aqvY3Pg) The picture on the right is the json sent by claude-dev,Their json is different

It didn't seem to be for that reason. I used the right json in curl demo, it also works.
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/4a4025a5-c0f4-4eee-bd7b-f8b179f86b9d">

Moreover, I tried changing the 'system' parameter in Claude dev request body from array object to  string type, and the request was successful. It seems there was an issue with Claude's internal processing of the 'system' parameter.

**Comment by amingze** [comment]
![image](https://github.com/user-attachments/assets/64ea9296-1f17-4772-b1f6-166f0698bb6b)
Thank you for your reply. I modified the code myself to make claude-dev run. but I don't know what effect this will have.

**Comment by saoudrizwan** [comment]
Please let me know if I need to add a new API provider option to handle these cases, or change something in the UX to allow for these edge case APIs that expect the system prompt in some kind of format. Closing for now since it seems like there's a fix here, but feel free to comment if you'd like me to update the extension somehow.
