### ISSUE TITLE
Continues command set chat in infinite waiting

### ISSUE THREAD

**Issue by BartNetJS** [saoudrizwan/claude-dev#32]
For example, the chat asker permission to execute 'kubectl logs -n flagger-system deployment/flagger-controller-commonsp -f'
But the -f flag makes it continues to watch for logs.
It would be nice to interrupt the execution, or that the agent kills it after a while.

**Comment by saoudrizwan** [comment]
Just released v1.0.6 that now has support for interactive and long running CLI commands. When a command expects input, you can send a message like normal and it will be streamed to the subprocess's stdin. For long-running processes or non-returning commands like your case, there is now an 'Exit Command' button.
