### ISSUE TITLE
Feature Request: Add an option to check files for placeholders after task completion

### ISSUE THREAD

**Issue by techcow2** [saoudrizwan/claude-dev#322]
It would be awesome if you could add an optional feature where it checks if placeholders were used instead of code after the task is completed and then have it automatically tell the AI something like "You used palceholders instead of code in index.html, scripts,js. Please fix it)." As of now, I check myself and simply say something like "index.html is not complete" and it fixes it.

Thank you for making this project!

**Comment by quinn** [comment]
are you referring to stuff like:

```
// ... (rest of the file remains unchanged)
```

in the diff?

I wonder if it would be possible to detect this and instruct Claude to generate a git patch of the changes it wants to make?

**Comment by quinn** [comment]
Might be duplicate of https://github.com/saoudrizwan/claude-dev/issues/289

**Comment by techcow2** [comment]
sorry its duplicate
