### ISSUE TITLE
429 error on every request since 1 time hitting the real limit.

### ISSUE THREAD

**Issue by shintaii** [saoudrizwan/claude-dev#323]
I have multiple devices so i've tested this. 

On my main pc, i had hit the limit of claudce one day. I got a ratelimit (429), so that made sense. But one week after i still get the same error on every task i create. I created a new API key and added it in, but made no difference. 

When i open vscode with claudedev in my macbook, it works fine. No ratelimit errors. 

I'm not sure of this is caused by the huge amout of cached tokens i have on my PC and not on my macbook, but something is off.

**Comment by shintaii** [comment]
If that is the case, what I will test when i'm back at the pc, that that block is still caused by requests made using this plugin. (Using Claude Sonnet btw). Which would be weird no?

**Comment by shintaii** [comment]
So this is weird. When i got back, i fired up my laptop, and send a task. Got a response. I started my pc, did the same task i got a 429 for almost a week, and boom, instant response. 

Maybe coincidence?

**Comment by saoudrizwan** [comment]
It's probably your account was in some weird suspended state, which might happen if they think you're spamming their API.

**Comment by PritiKumr** [comment]
Same issue. I am blocked even when I use different API tokens and still hit the rate limit in 1 min

**Comment by Hosselo** [comment]
Same issue. hit the rate limit in 1 min every second API request.
