### ISSUE TITLE
I have tried to use Ollama and Gemini within Claude Dev on VSCode but keep getting this error. 

### ISSUE THREAD

**Issue by SanatKulkarni** [saoudrizwan/claude-dev#328]
Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
'powershell' is not recognized as an internal or external command,
operable program or batch file.

**Comment by saoudrizwan** [comment]
did this error show up under 'API request failed'? when exactly did this error show up for you?

**Comment by philfung** [comment]
@SanatKulkarni probably [missing environment variable](https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr)?

**Comment by saoudrizwan** [comment]
I made a troubleshooting doc for this error but am curious when exactly it showed up for @SanatKulkarni, I believe it shows up when the first API request is made but not sure. 

Pls see this guide and lmk if this helps! https://github.com/saoudrizwan/claude-dev/wiki/TroubleShooting-%E2%80%90-%22PowerShell-is-not-recognized-as-an-internal-or-external-command%22

**Comment by SanatKulkarni** [comment]
![image](https://github.com/user-attachments/assets/4c8e2a7e-4011-4ba2-abe4-9b448e962634)
Hey @saoudrizwan I am getting this exact error ever since I downloaded the extension for the first time. I did mess around with the environment variables and also used your guide as well :D . Sadly didn't fix the issue.

**Comment by saoudrizwan** [comment]
There are other users that followed the steps in that guide and were able to get this issue fixed, can you pls make sure that you're using the latest version of powershell? Pls feel free to DM my discord so I can help further troubleshoot this, it would help to see screenshots of your environment variables for example. https://discord.gg/claudedev
