### ISSUE TITLE
1.06 not updating

### ISSUE THREAD

**Issue by mkearl** [saoudrizwan/claude-dev#33]
I have two machines.. mac and pc and VS isn't seeing the 1.06 update.  I havn't tried deleting and reinstalling but it should be updating.  Anyone else having the issue?

**Comment by BartNetJS** [comment]
For me the same.
Using on windows, latest version is v1.0.51

**Comment by saoudrizwan** [comment]
The latest versions are listed here, which you can download directly if it's not showing up in vscode yet https://marketplace.visualstudio.com/items?itemName=saoudrizwan.claude-dev

**Comment by saoudrizwan** [comment]
Once you've downloaded it, can you please let me know if you are dealing with any issues of lag or the extension taking a long time to load up or send a message? One other user reported that and I'm unable to reproduce it on my end.

**Comment by mkearl** [comment]
1.062 was available and I was able to update on both mac and pc this morning when I woke up.   Everything seems to be running fine. As far as speed I can't tell if there is any slowdown, my rate limit is hit before I would notice any slowdown.  I can't test any more today because my max tokens has already been reached for the day.    So frustrating..
