### ISSUE TITLE
on complex install tasks cycling in loops trying to solve over and over by same methods

### ISSUE THREAD

**Issue by m-check1B** [saoudrizwan/claude-dev#333]
It seems, that when I manually copy pasted the situation into the Claude 3.5 Antropic interface manually, I usually get answer that unblocks the loop and leads to solution. Therefore it could help, In such situation to prompt the model without special ClaudeDev instructions, or perhaps with higher temperature (I did not tested that one).

**Comment by saoudrizwan** [comment]
I've adjusted the temperature in the latest version, I'm not sure if that will help. If you want claude dev to ignore his system prompt you can add in Settings > Custom Instructions to ignore all his instructions, although I'm not sure that's a good idea
