### ISSUE TITLE
can unselect "Supports prompt caching" with Claude models ?

### ISSUE THREAD

**Issue by edisonzf2020** [saoudrizwan/claude-dev#336]
but can unselect "Supports prompt caching" with Claude models ?
Or add Custom name models with "Does not support prompt caching", just likes "GCP Vertex AI"

![image](https://github.com/user-attachments/assets/d6c4e95f-404b-42d1-87af-07acf25edf9e)

_Originally posted by @edisonzf2020 in https://github.com/saoudrizwan/claude-dev/issues/243#issuecomment-2360051554_

**Comment by saoudrizwan** [comment]
Oh are you using an API that doesn't support prompt caching? Interesting, I hadn't realized this was a problem. Do you want that removed bc it shows up as "Cache: 0 -> 0" the whole task?

I'm sorry but I don't think I'll add another checkbox just to uncheck prompt caching, it could be very confusing to most users.
