### ISSUE TITLE
Task diff popping up in front of other work

### ISSUE THREAD

**Issue by tsdevau** [saoudrizwan/claude-dev#339]
I have no idea how you might approach this, but here it is...  I would love it if the diff from a task, didn't pop up in front of what I doing while I wait for a Task to progress.

Now, I'm the first to admit, there are some tasks I will wait for and watch, so I want the diff immediately.  On the other hand, there are some longer running Tasks, where I might choose to move on with something else while it completes.  In that case, I would prefer the diff not to pop up in front of the editor I'm working in.

I'm not sure if it's something VSCode even allows you control of in anyway, but it would be a great improvement if something along these lines where possible.

**Comment by saoudrizwan** [comment]
Hey thanks for the idea! Hm I wonder if a 'background mode' setting is a solution here, where you tick a checkbox so he wont disrupt your workflow. Pls feel free to post this on the idea board for others to vote on: https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas

For now you can just open another vscode window, have claude dev work on one while you work in the other
