### ISSUE TITLE
Add openrouter.ai support for API

### ISSUE THREAD

**Issue by emicovi** [saoudrizwan/claude-dev#34]
It would be great if you could add support for using the API from OpenRouter. As a student from Europe without a VAT ID, I’ve tried multiple times to create an API from the Claude website but haven’t been successful. Thank you!

**Comment by Hamidanen** [comment]
Yes . it's Very appreciated if you can provide openrouter.ai support for API . it's my problem too.

**Comment by iamviktorhorvat** [comment]
Yes, please add this!!!

**Comment by QDaed** [comment]
This should be put into high piority

**Comment by iamviktorhorvat** [comment]
Also, adding support for **Poe** would be great!

**Comment by saoudrizwan** [comment]
Good news! I just released v1.0.9 with OpenRouter and AWS Bedrock support 🎉 (hit the settings button in the top menu bar > API Provider > OpenRouter)

**Comment by Hamidanen** [comment]
i'm forever grateful

**Comment by jshay21** [comment]
hi @saoudrizwan How do we select which model we want to use in OpenRouter?

**Comment by saoudrizwan** [comment]
@jshay21 it automatically uses the latest claude 3.5 sonnet beta model right now, but ability to select other models is coming.
