### ISSUE TITLE
Global docs

### ISSUE THREAD

**Issue by cadilhac** [saoudrizwan/claude-dev#348]
**Feature request**: add docs urls globally in settings so that I don't have to repeat them for each new task.

**Comment by Sarke** [comment]
For suggestions, you should close this and post it here: https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas

**Comment by cadilhac** [comment]
The need is really to let the model know about some libraries unknown to him as well as some recent versions he doesn't know. Otherwise some responses are outdated or even impossible. For example I would like him to know Primevue latest version 4 so that it knows about it for every of my questions/tasks. Putting all this is a context.md file seems a bit too much here...
