### ISSUE TITLE
Save All and Approve All Feature

### ISSUE THREAD

**Issue by akamalov** [saoudrizwan/claude-dev#350]
Greetings,

Wondering, is it possible to introduce features such as:

- Approve All
- Save All

This will save time instead of clicking each every file if needed.

**Comment by Sarke** [comment]
For suggestions, you should close this and post it here: https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas

**Comment by saoudrizwan** [comment]
Hey @akamalov! You can already do this with Settings > Automatically approve all read-only operations. If you have suggestions for improving this, pls feel free to open an idea in the link @Sarke posted. Thank you!
