### ISSUE TITLE
feat: Keyboard navigation of "@" select options

### ISSUE THREAD

**Issue by tsdevau** [saoudrizwan/claude-dev#353]
Is it possible to add keyboard navigation of the selectable list that appears with `@`?  So that after refining with a partial name you can use arrow keys to select the file/directory.

**Comment by saoudrizwan** [comment]
Hi! You can use arrow keys + Enter/Tab to navigate the context menu, so I'm not sure what you mean, maybe i'm not understanding correctly. When typing a file path, you can hit tab to autocomplete the closest match, and arrow keys to select other results.

**Comment by tsdevau** [comment]
Sorry, I'll close this ... it does exactly what I want as you say.  Trouble was my theme wasn't showing the highlighted items, so it appeared as though nothing was happening.  Changed to another theme to test it and it works exactly as you say.  Now I just need to find the theme style property to adjust the display colour of the highlighting in that menu so I can see it!

**Comment by saoudrizwan** [comment]
Agh sorry it's not working with your theme. It's hard picking the right theme variables for these things, but I try to test like 20 of the most popular themes.
