### ISSUE TITLE
Play sound when action is complete

### ISSUE THREAD

**Issue by ALMaclaine** [saoudrizwan/claude-dev#355]
Play sound when action is complete.

I'm guilty of staring at my phone and other things while waiting, a sound for complete would be awesome to get attention.

Customizable sound would be ideal, but any (reasonably pleasant) sound will do.

**Comment by saoudrizwan** [comment]
Can you pls add this idea to the Ideas board: https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas Not sure how many ppl would find this useful, but they can vote for it there

**Comment by jmendiola222** [comment]
This was added as a feature request [here](https://github.com/cline/cline/discussions/5953), with some hacky temporal workaround as well.
