### ISSUE TITLE
I am not able to choose other models

### ISSUE THREAD

**Issue by mehranmahouti** [saoudrizwan/claude-dev#36]
Is there a way to use other models rather than sonnet 3.5
I want to try the others too if possible.

By the way after version 1.04 its working perfectly.

Right now the only problem is Antropics rate limits, which they told me will rise automatically, but I am not sure how long it will take, or is there any other thing I can do?

Maybe you can add additional API fields so we can put our secondary account's API to continue.

**Comment by saoudrizwan** [comment]
I just released v1.0.9 with OpenRouter and AWS Bedrock support, which have much more generous rate limits.
