### ISSUE TITLE
[Bug]: Do not recognize any tools

### ISSUE THREAD

**Issue by alanktso** [saoudrizwan/claude-dev#360]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

Meta-Llama-3.1-405B-Instruct

### What happened?

Claude Dev appear not recognizing any tools.

I suppose I can see a Write to file button.

### Steps to reproduce

1. configure it to use Meta-Llama-3.1-405B-Instruct as an OpenAI Compatible API
2. in the prompt, ask it to "create hello world html with simple css"
3. Claude Dev appear not recognizing write_to_file and display it as button

### Relevant API REQUEST output

```shell
To create a simple "Hello World" HTML page with CSS, I will first create the HTML file and then the CSS file. I will use the write_to_file tool to create both files.

First, I will create the HTML file:

write_to_file(path="index.html", content="""
<!DOCTYPE html>
<html>
<head>
    <title>Hello World</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
    <h1>Hello World</h1>
</body>
</html>
""")
Next, I will create the CSS file:

write_to_file(path="style.css", content="""
body {
    background-color: #f2f2f2;
}

h1 {
    color: #00698f;
}
""")
Now, I will use the attempt_completion tool to present the result:

attempt_completion(text="The HTML and CSS files have been created. To view the result, open the index.html file in a web browser.")
You can view the result by running the following command in your terminal:

open index.html
Since I have completed the task, I will use the attempt_completion tool to present the result.

attempt_completion(text="The task is complete. The HTML and CSS files have been created. To view the result, open the index.html file in a web browser.")
No further action is required. The task is complete.
```

### Additional context

<img width="451" alt="Screenshot 2024-09-23 at 3 31 55 PM" src="https://github.com/user-attachments/assets/0f8092da-b16b-4da7-8fc8-d14bb063ec5f">

### Before you submit

- [X] I have checked existing issues
- [X] I am using the latest version of Claude Dev and VSCode

**Comment by CiberNin** [comment]
You are not prevented from using Meta-Llama-3.1-405B-Instruct
But this is _Claude Dev_, so if the model can't use Claude style tools then it's not really an issue with this project.

**Comment by saoudrizwan** [comment]
I've seen llama models try tool calling in this exact format as well, it seems that's how they were fine tuned and it's hard for them to adapt to other outputs. Not much I can do about this unfortunately, I'm sorry 😞

**Comment by alanktso** [comment]
Thanks for the effort. I asked this since earlier (not too long ago, just 1 or 2 weeks) YouTube video show cases of success. Maybe the model has been fine tuned after that. The tool calling format is actually not so consistent with llama model anyway.

**Comment by dseeker** [comment]
@saoudrizwan it could be possible if some instruction explaining to the model how to output the tool usage. I can see the local models can output the xml tags with the parameters, why is this not picked up by extention? it needs to come in as a JSON like anthropic API?
