### ISSUE TITLE
[Bug]: write_to_file replacing content instead of appending

### ISSUE THREAD

**Issue by sumith** [saoudrizwan/claude-dev#367]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

When asked to update an existing file, it is always replacing the content.  It shows the text
`# ... (keep all existing code)`
and adds the new content below this line. 
However, the (keep all existing...) is actually entered in place of the entire content of the file.  If you approve the edit, all is left is the comment and the new code!

### Steps to reproduce

1. Give an task to update an existing project
2. I tried on a Django project. The urls.py was updated correctly, but the view file were overwritten

### Before you submit

- [X] I have checked existing issues
- [X] I am using the latest version of Claude Dev and VSCode

**Comment by CiberNin** [comment]
There is a little button for you to click between the old & new screens to disapprove individual edits like this.
