### ISSUE TITLE
Video Resources using Claude-Dev

### ISSUE THREAD

**Issue by mkearl** [saoudrizwan/claude-dev#40]
**Shows setup and creation of a Tetris Game.**
https://www.youtube.com/watch?v=VT-JYVi81ew

**Using to create Dino Game**
https://www.youtube.com/watch?v=5FbZ8ALfSTs&t=553s

**A couple in Chinese**
https://www.youtube.com/watch?v=bmEM7GU2sXM
https://www.youtube.com/watch?v=N7pu8gWc02Q

**Comment by saoudrizwan** [comment]
Thank you for finding these! I'll add them to the README

**Comment by AlexanderHel** [comment]
> https://www.youtube.com/watch?v=N7pu8gWc02Q

Just want to clarify, this one is korean

**Comment by mkearl** [comment]
Another Video Today:
https://www.youtube.com/watch?v=UNsQHosbIoE by WorldofAI 
Track Income and expenses with report.
