### ISSUE TITLE
Claude-Dev erroneously removing large sections of code.

### ISSUE THREAD

**Issue by nfxbeats** [saoudrizwan/claude-dev#410]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude

### What happened?

Often times when I aske claude-dev to add a feature, it makes changes and shows me the diff file waiting for approval. When I look at the diff it shows large sections of pre-existing and working code deleted and replaced with a comment that say "previous code remains unchanged". If I accept the change it removed the previousl code and puts that comment there in it's place, resulting in a broken file.

![claudedev](https://github.com/user-attachments/assets/46eda5c3-7edc-4144-b979-f69f93046203)

### Steps to reproduce

1. have a lengthy bit of code 
2. ask for a small feature to be added
3. wait for the issue to occur (it is not 100% reproduceable)

### Additional context

if I tell claude-dev "you are removing too much code" it agrees, asks me for permission to re-read the file it's editing and usually can then add the code properly.

![claude 2](https://github.com/user-attachments/assets/fd30c331-6304-4d19-af67-bb6cf5cc0778)

**Comment by vicojj** [comment]
Same issue for me. It looks like Claude only provides the parts of the code that remain unchanged and adds a comment indicating "// This part of the code remains unchanged" but then it omits this code from the answer. I provide custom instructions to avoid this but it still does it.

**Comment by shintaii** [comment]
I just wanted to open a issue for this. It happens to me all the time.

**Comment by saoudrizwan** [comment]
@nfxbeats @vicojj @shintaii @antsbuildit Hey im sorry you're dealing with this. This unfortunately is a limitation with language models only being able to output a max number of tokens, so you'll see this happen when working with large files for example. But there's an easy fix! Please check out this guide I made about how to work around this: https://github.com/saoudrizwan/claude-dev/wiki/Troubleshooting-%E2%80%90-Claude-Deleting-Code-with-%22rest-of-code-here%22-Comments

**Comment by shintaii** [comment]
Hi, thanks for the guide, this is what i was already doing. Thing is that it also happens with (very) small files. I will post a screenshot when it happens.

**Comment by anthonyjj89** [comment]
I've found splitting css and js files into more smaller ones helped with this issue.
