### ISSUE TITLE
Per minute rate limit error after v1.0.85

### ISSUE THREAD

**Issue by mehranmahouti** [saoudrizwan/claude-dev#42]
I started to get this error more frequently after I update to v1.0.85

429 {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}

**Comment by saoudrizwan** [comment]
What tool was used before this error came up? It would help to get a summary of task events that led to this

**Comment by mehranmahouti** [comment]
I am working on a simple HTML page with .js and .css files beside it. I need to wait 1 min and after that it works.

**Comment by mehranmahouti** [comment]
![image](https://github.com/user-attachments/assets/222d1790-af2f-453d-bebf-80cb70803b9e)

**Comment by mehranmahouti** [comment]
this time its the daily limit. but it gave me this error for per minute too, in same situation

**Comment by AlexanderHel** [comment]
well check your usage to see if it's exceed your limit today or not

https://console.anthropic.com/settings/usage

https://console.anthropic.com/settings/limits

**Comment by mehranmahouti** [comment]
I know, when I wrote the first message here I had daily limits, I always checking those pages.
But before the last version the per-minute limit was not seen.
Now I am using another API from another account of mine and again I receive this error.

![image](https://github.com/user-attachments/assets/32335d32-6637-42ef-bd03-4caca48fc488)

I am sure I reached my per-minute limit, but maybe calaude-dev can handle this.

**Comment by AlexanderHel** [comment]
per-minute limit can easily avoid, just wait a little maybe 30 seconds then retry, maybe claude-dev can add a delay options

**Comment by saoudrizwan** [comment]
I just released v1.0.9 with OpenRouter and AWS Bedrock support, they are much more generous with rate limits. Please give those options a try, for now I'm going to close this but feel free to re-open if you still run into this problem.

**Comment by danividalg** [comment]
It could be great if you can add a configuration field for the rate limits, so Claude Dev can wait if needed to avoid overpass this limit and get this type of errors.
What do you think ? :)
