### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by brenorb** [saoudrizwan/claude-dev#43]
There should be an automatic log of at least the prompts.

Context:
I was working with it while tried the `Interpreter Mode` from Cursor which erased a whole file I did before. I could ask it to generate again but it would be much easier if I could open the log and just repeat the what I asked before. I see we can Export .MD, but it's very simple to lose it and it's not updatable, I need to export it all the time and it will generate lots of logs with repeated information instead having it in one file.

**Comment by saoudrizwan** [comment]
Claude dev now has task history that should help with this
