### ISSUE TITLE
Claude artifact's suggestion "the remaining code stays unchanged" actually deletes tons of code

### ISSUE THREAD

**Issue by rowild** [saoudrizwan/claude-dev#456]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude Sonnet 3.5

### What happened?

In an existing Nuxt project, I ask Claude why a certain composable is not working. After analysing the code, Claude suggest a different solution, and in the code comparison window there will be comments that say `// ... (rest of the file remains the same)`. It says "REMAINS", but instead, when clicking on `SAVE`, all that code will be deleted (which is also indicated by the line numbers on the left side). Not sure if this is Claude's standard behaviour, it is in any case very destructive and dangerous.

### Steps to reproduce

1. open an existing project, I had a Nuxt project
2. ask Claude to make a small change somewhere
3. examine the code comparison and deletion!

I think these screenshots tell more about the situation.

![Screenshot 2024-10-06 at 15 45 45](https://github.com/user-attachments/assets/930db016-a81c-4882-b8f7-d1e7a6ffb079)

![Screenshot 2024-10-06 at 16 41 17](https://github.com/user-attachments/assets/e116a7f4-fba6-4232-92ea-5f9320169b3e)

**Comment by farbour** [comment]
This is an extremely common issue with all LLMs. You can try adding special instruction and ask to always provide the full code of any modified file.

**Comment by rowild** [comment]
Aha, ok. Thank you for clarifying, @farbour! I clearly have no experience with other LLMs. :-)
