### ISSUE TITLE
Shell Integration Unavailable on MacOS

### ISSUE THREAD

**Issue by StephenBrough** [saoudrizwan/claude-dev#458]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

I am attempting to have Claude run commands and check the terminal output but it can't see the output. I have updated VSCode and set the shell to zsh, but still getting the error.

### Steps to reproduce

1. Ask if Claude Dev can see console output
2. Wait for it to generate a command
3. Run command
4. Confirm that it doesn't see the console output
5. Updated/Confirmed VSCode is up-to-date
6. Still no dice
7. Set shell to zsh
8. Still not working
9. Added `[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"` to ~/.zshrc
10. Restarted VSCode
11. Still seeing error
12. Tried adding these lines to `settings.json`:
   ```json
    "terminal.integrated.defaultProfile.osx": "zsh",
    "terminal.integrated.shellIntegration.enabled": true,
    "terminal.integrated.shellIntegration.decorationsEnabled": "both"
```
13. Still not working
14. Restarted Mac and disabled all other extensions in VSCode
15. Still not working

### Additional context

**VSCode about info**
Version: 1.94.0 (Universal)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z (4 days ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.4.0

**ZSH Version**
zsh 5.9 (x86_64-apple-darwin23.0)

**Comment by jonny7737** [comment]
I can't help but I can say that shell integration works fine on my mac. I used it as recently as yesterday.

**Comment by StephenBrough** [comment]
I wouldn't be surprised if it was something in my current setup, but I have no idea what would be conflicting with it. I tried restarting my Mac and disabling all other VSCode extensions but I'm still getting the error. Nothing obvious in the developer tools console logs. Just looks like Claude Dev times out waiting for terminal output.

**Comment by StephenBrough** [comment]
Oddly enough, VSCode is saying the terminal has shell integration.

<img width="473" alt="Screenshot 2024-10-07 at 2 11 41 PM" src="https://github.com/user-attachments/assets/aa128d3e-e939-458f-b071-d71ff3ee102e">

**Comment by Anima-t3d** [comment]
Check your Mac security settings like accessibility features etc. not sure if that's your specific issue, but with Mac that's typically the issue for me.
