### ISSUE TITLE
Adding functionality for updating files without re writing the whole thing

### ISSUE THREAD

**Issue by SamPink** [saoudrizwan/claude-dev#46]
When starting to use this tool on larger projects, the limitation of having to output the whole of a files contents becomes quite a significant restriction. 

Adding a tool / functionality to make changes to a file in place would make it much more powerful for working with larger projects, and cheaper! I believe Claude engineer has this functionality (although worse overall in my opinion) 

Another thing to note, ive been asking claude dev to read / write a README.md file, since I find this helps when coming back to a project, I often start the task by asking it to go through the read me. i feel this gives it a good overall understanding of the project from the beginning. 

So based on this it could make sense to intergrade this functionality into its task logic, kind of like a way of getting it to save its state / thinking. but also working as actual useful documentation for the project you are working on.

**Comment by nagmus** [comment]
I love this idea, the models I've used do often want to provide code snippets instead of the whole script, overwriting the whole file. It would be wonderful if claude-dev knew how to work with them. Saving on tokens is a big plus!

**Comment by BartNetJS** [comment]
I like the idea of a readme.md
What is did is created a readme.md file with a tasks list, and asker claude dev to read it and execute the steps.
Worked fine.
Some integrated solution sound also great.
Thinking further, someone could share boilerplate project/solution files, so other people can start from such a document and let claude dev do the boilerplate work.

**Comment by CiberNin** [comment]
I think the only way to do less that full file writes would be to insert line numbers in all the code fed into Claude & filter them out on all code Claude returns. And that only works if line numbers don't change. So might be an "update_single_line" tool.
Maybe for multiple lines /deletions could figure out some sort of diff like syntax? challenging to parse and get claude to produce consistently.
Maybe give explicit insert after & delete line tools that is can use multiple times in a reply for edits of just a few lines?

Probably should create some test tasks and evaluate each option.

**Comment by dchuk** [comment]
Looks like cursor prompts the AI to provide search and replace diff blocks to solve for this: https://www.cursor.com/blog/instant-apply
