### ISSUE TITLE
Add GROQ support

### ISSUE THREAD

**Issue by Verzitile** [saoudrizwan/claude-dev#47]
I would like to be abble to use the groq.com api as its free

**Comment by Elias-Lindholm** [comment]
@saoudrizwan  will groq get added?

**Comment by saoudrizwan** [comment]
Just want folks to know that GROQ does not offer claude or gpt4o models (https://console.groq.com/docs/models) - I've tried the models they do support through openrouter and they performed poorly with claude dev's massive system prompt/tool schema. If they support more models I'll add them as an option, but until then I don't want people to select GROQ thinking claude dev is going to work well with it.

**Comment by Elias-Lindholm** [comment]
@saoudrizwan  i get that, but you could add a tag like *Preformce baddly

**Comment by saoudrizwan** [comment]
GROQ is on the todo list, closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/30

**Comment by deafmanskwx** [comment]
This becomes even more relevant for R1 hosted on Groq.

**Comment by cvladan** [comment]
Yes, please! Now!
Groq is really, really, really fast and is finally offering a competitive model [DeepSeek-R1-Distill-Llama-70b](https://groq.com/groqcloud-makes-deepseek-r1-distill-llama-70b-available/)

**Comment by ta1kun** [comment]
pls add it

**Comment by awfssv** [comment]
hope to add GROQ ASAP, a very fast and good R1 model.

**Comment by cvladan** [comment]
Oh, I'm so stupid. It works perfectly as an OpenAI compatible provider with these settings:

![Image](https://github.com/user-attachments/assets/7585497d-3f17-4163-b380-e28ed93de248)

**Comment by Benniepie** [comment]
> Oh, I'm so stupid. It works perfectly as an OpenAI compatible provider with these settings:
> 
> ![Image](https://github.com/user-attachments/assets/7585497d-3f17-4163-b380-e28ed93de248)

Fab, I didn't realise... thanks for posting this. That makes me stupid too! Will try it out ASAP, eager to see how it measures up. Cheers

**Comment by ta1kun** [comment]
> Oh, I'm so stupid. It works perfectly as an OpenAI compatible provider with these settings:
> 
> ![Image](https://github.com/user-attachments/assets/7585497d-3f17-4163-b380-e28ed93de248)

i cant use it cause only 6000 token and cline first request is 13112 tokens:

413 Request too large for model `deepseek-r1-distill-llama-70b` in organization `org_01hqhbtx43ekesp60vaydmxrh2` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Requested 13112, please reduce your message size and try again. Visit https://console.groq.com/docs/rate-limits for more information.

how did u fix it?

**Comment by shivam2014** [comment]
> > Oh, I'm so stupid. It works perfectly as an OpenAI compatible provider with these settings:
> > ![Image](https://github.com/user-attachments/assets/7585497d-3f17-4163-b380-e28ed93de248)
> 
> i cant use it cause only 6000 token and cline first request is 13112 tokens:
> 
> 413 Request too large for model `deepseek-r1-distill-llama-70b` in organization `org_01hqhbtx43ekesp60vaydmxrh2` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Requested 13112, please reduce your message size and try again. Visit https://console.groq.com/docs/rate-limits for more information.
> 
> how did u fix it?

The same for me too.  I would like to know a solution if possible as well. Thanks

**Comment by cvladan** [comment]
> how did u fix it?

Simply pay for a paid plan. It is still astonishingly cheap and blazingly fast.

**Comment by justlovemaki** [comment]
I request https://api.groq.com/openai/v1 to return 404

**Comment by lospark** [comment]
Hi all, any updates on the progress

**Comment by tsaijamey** [comment]
> I request https://api.groq.com/openai/v1 to return 404

+1

**Comment by DowsingUK** [comment]
https://api.groq.com/openai/v1/ add the slash at the end it'll fix the 404 error

**Comment by rainingthunderbolt-1645** [comment]
cant use groq now also
