### ISSUE TITLE
Add option to approve tool use without immediately creating new API request

### ISSUE THREAD

**Issue by rplglobal** [saoudrizwan/claude-dev#48]
This is a great project, used it for a couple days and I really enjoy the flow. I have some thoughts on features or suggestions

1. When approving to change a file would be nice to have an option that doesn't automatically send another api request.  after clicking approve changes and applying changes to file, at this state i would like to pause and have 2 options: 1. continue the prompt as it normally would with whatever the auto prompt is when approving or 2. enter a new prompt to continue from.  this way i can test the change and instead of sending the automatic request after approving a file change I can enter my error or changes as a prompt.  

2. An option to limit the amount of verbosity in the responses.

3. When asking to read a file we can select a portions of that file to read instead of the whole file.

**Comment by saoudrizwan** [comment]
If this is still something you'd like to see added, please feel free to add it in the [ideas board](https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas) so people can vote on it. Thank you!
