### ISSUE TITLE
command 'claude-dev.settingsButtonTapped' not found

### ISSUE THREAD

**Issue by eprofos** [saoudrizwan/claude-dev#51]
command 'claude-dev.settingsButtonTapped' not found 

Version 1.0.96

**Comment by BartNetJS** [comment]
Same here

**Comment by SamPink** [comment]
Same

**Comment by Kynetic25** [comment]
Getting the same error. Was working fine yesterday - bug in the update?

**Comment by BartNetJS** [comment]
i rolled back to this version:
![image](https://github.com/user-attachments/assets/fb785c50-cd14-43b7-9e20-f83f9c90f718)

**Comment by Tribe77-Tech** [comment]
Still seeing the same issue with `v1.0.97`.

**Comment by sumedhphadke** [comment]
Same issue with v1.0.97

**Comment by paodal** [comment]
Hi, all. I rolled back to version 1.0.95, but I receive `529 {"type":"error","error": "type":"overloaded_error","message":"Overloaded"}}` for every request I make. Has this happened to anyone else?

**Comment by Kynetic25** [comment]
Yes... Also getting the same error. Tried another app that uses Anthropic
API key and that works fine.

**Comment by eprofos** [comment]
> Hi, all. I rolled back to version 1.0.95, but I receive `529 {"type":"error","error": "type":"overloaded_error","message":"Overloaded"}}` for every request I make. Has this happened to anyone else?
Same

**Comment by atoptun** [comment]
Same bug

**Comment by eprofos** [comment]
> > Hi, all. I rolled back to version 1.0.95, but I receive `529 {"type":"error","error": "type":"overloaded_error","message":"Overloaded"}}` for every request I make. Has this happened to anyone else?
> 
> Same

This one came from Anthropic API

**Comment by saoudrizwan** [comment]
I just put out a patch to fix the issue where the extension wouldn't load. Please download **v1.0.98** and you should be good to go. (It was caused by adding a package that included a binary that doesn't play well with electron builds)

**Comment by saoudrizwan** [comment]
Regarding the API error, from Anthropic's docs: "529 - overloaded_error: Anthropic’s API is temporarily overloaded."

**Comment by sumedhphadke** [comment]
Can confirm it works now with `v1.0.98`

**Comment by BartNetJS** [comment]
> Regarding the API error, from Anthropic's docs: "529 - overloaded_error: Anthropic’s API is temporarily overloaded."
Indeed issue with Anthropic
![image](https://github.com/user-attachments/assets/5c7c5b53-8321-4ce0-b1cd-e41501a7b499)

**Comment by saoudrizwan** [comment]
Unrelated but for you folks playing around with the extension so late ate night, the new version let's you add images to your messages! Try it out and let me know what you think

**Comment by eprofos** [comment]
> Unrelated but for you folks playing around with the extension so late at night, the new version let's you add images to your messages! Try it out and let me know what you think

Great feature!! but v1.0.98 is not realeased yet !!

**Comment by eprofos** [comment]
Working well
