### ISSUE TITLE
API Request Failed - Error 529

### ISSUE THREAD

**Issue by Kynetic25** [saoudrizwan/claude-dev#52]
Using Anthropic API but keep getting API Request Failed with 529 {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}.

Tried an another app that uses the same API key and that works fine. Not sure if this applies to only Claude Dev?

**Comment by saoudrizwan** [comment]
From Anthropic's docs: "529 - overloaded_error: Anthropic’s API is temporarily overloaded." Please try again later or use a different provider (OpenRouter is working fine)
