### ISSUE TITLE
529 Overload Error

### ISSUE THREAD

**Issue by hibouyave** [saoudrizwan/claude-dev#53]
Hello, 

I'm new to Claude Dev and have this error "API Request Failed

529 {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}"

I wanted to know if it is a personnal issue or an API issue. (I have 0 token send nad find it wierd)(Newbie developer BTW)

THnaks in advance for your project.

**Comment by 8ByteSword** [comment]
Same. Rolled back to 1.0.95 and doesnt work either. Seems a bug.

**Comment by saoudrizwan** [comment]
From Anthropic's docs: "529 - overloaded_error: Anthropic’s API is temporarily overloaded." Please try again later or use a different provider (OpenRouter is working fine)

**Comment by hibouyave** [comment]
Thank you for the fast reply
