### ISSUE TITLE
Add rate limit information

### ISSUE THREAD

**Issue by CiberNin** [saoudrizwan/claude-dev#54]
By my reading, the API should be returning how long until rate limit blocking wears off so you should be able to show a loading bar if you hit rate limit.

**Comment by drhouse** [comment]
Is there a place that shows you rate limit timings? Is it on Anthropic's API website?

**Comment by saoudrizwan** [comment]
Closing as duplicate of https://github.com/saoudrizwan/claude-dev/issues/186
