### ISSUE TITLE
Feature Request - Custom Instructions

### ISSUE THREAD

**Issue by mark-avalaunch** [saoudrizwan/claude-dev#56]
It would be great if we could add custom instructions for all prompts. Things like the languages used, etc. as it seems like claude sometimes forgets or doesn't pick up on it.

**Comment by saoudrizwan** [comment]
This is a great idea, maybe a 'System Prompt' field in settings?

**Comment by saoudrizwan** [comment]
v1.1.13 now lets you add custom instructions in settings! Thank you for the wonderful suggestion.
