### ISSUE TITLE
Ability to see Images

### ISSUE THREAD

**Issue by xavitg** [saoudrizwan/claude-dev#59]
Hello,

I don't figure out how to send images easily to Claude via "Claude-Dev". One of the strengths of Claude is the ability to see images and understand very well what its happening and to see the same as you see... that helps a lot to improve front end design, resolve bugs and so.

Why don't you add the ability to attach photos to che chat?

Thank you

**Comment by AlexanderHel** [comment]
I think it can, usually I just add the image to the project folder then tell it inspect the image.png

**Comment by xavitg** [comment]
I tried it several times, but didnt work for me. Something as easy as that should work smoothly. At least, I tried and it doesnt work. I am using vscode on cloud shell (google cloud).

**Comment by xavitg** [comment]
> I think it can, usually I just add the image to the project folder then tell it inspect the image.png

I tried it several times, but didnt work for me. Something as easy as that should work smoothly. At least, I tried and it doesnt work. I am using vscode on cloud shell (google cloud).

**Comment by saoudrizwan** [comment]
v1.0.98 now lets you attach images to your messages! (Either with the camera button or paste directly into the input field)
