### ISSUE TITLE
Can you add OpenRouter Support?

### ISSUE THREAD

**Issue by PierrunoYT** [saoudrizwan/claude-dev#6]

**Comment by emicovi** [comment]
Waiting fot the same

**Comment by iamviktorhorvat** [comment]
PLEASE, ADD THIS FEATURE!!! <3

**Comment by saoudrizwan** [comment]
Good news! I just released v1.0.9 with OpenRouter and AWS Bedrock support 🎉 (hit the settings button in the top menu bar > API Provider > OpenRouter)
