### ISSUE TITLE
auto refresh

### ISSUE THREAD

**Issue by benjamix95** [saoudrizwan/claude-dev#62]
i have a big problems with claude dev auto refresh, while sending some request, or maybe i hat to approve some changes, it refresh the ui and lose everything. Than i had to submit again analyze to the intire project etc.. and cost a lot of tokens to do this again and again. need the history buttuns.

**Comment by saoudrizwan** [comment]
Task history is currently in development, but I recommend you export your task conversation using the 'EXPORT .MD' button and use that as context for future tasks. Be sure to strip out any irrelevant information to keep token count low.
