### ISSUE TITLE
[FEATURE] Add option to include a message when rejecting a suggestion

### ISSUE THREAD

**Issue by eprofos** [saoudrizwan/claude-dev#66]
It would be beneficial to add the ability to include a message when rejecting a suggestion using the reject button. This would allow users to provide context or feedback on why the suggestion was rejected, which could be valuable for the development and collaboration process. Please consider implementing this feature to enhance communication and improve the overall user experience.

**Comment by saoudrizwan** [comment]
The reject button is just shorthand for "The user is not satisfied with this", but you can instead send a message to provide feedback to Claude–then the tool response would be "The user is not satsfied with this. Here is their feedback:...".

**Comment by eprofos** [comment]
But when I added the feedback I don't see it in the chat, also I think that it didn't took my feedback on consideration
