### ISSUE TITLE
[FEATURE] Add Option to Always Allow Access to Folders and Files Without Repeated Confirmation

### ISSUE THREAD

**Issue by eprofos** [saoudrizwan/claude-dev#67]
I would like to request the addition of a feature that provides users with the ability to always allow access to folders and files within the extension settings. Currently, each time access is required, users must manually confirm the action, which can be cumbersome, especially during frequent operations.

This proposed feature would enhance user experience by streamlining the workflow and reducing the number of repetitive confirmations needed. Ideally, this option could be toggled on or off in the extension settings, allowing users to choose their preferred behavior.

Thank you for considering this enhancement.

**Comment by jtac** [comment]
+1 on this, I suggest some kind of whitelisting: ie. recursive permission to access a specific whitelisted folder ( no symlink creation allowed outside the structure  ) and some kind of max budget limiter to prevent runovers

**Comment by CiberNin** [comment]
At the very least for reads I think this makes sense.

**Comment by saoudrizwan** [comment]
v1.5.16 now lets you enable 'Auto allow read-only operations' to do this!

**Comment by eprofos** [comment]
Yes seen 👍

**Comment by lee-b** [comment]
Please add for writes too.  It needs a big red warning in the settings, but I'd love to be able to let this just run on a local model while I'm at work or something, on a new repo that there's nothing to lose on, or a fully backed up repo that I've equally nothing to lose on.
