### ISSUE TITLE
continuing / picking up where you left off

### ISSUE THREAD

**Issue by jtac** [saoudrizwan/claude-dev#70]
Currently "catching up" to what's been done so far has been a bit tricky, i usually tell claude-dev to create a readme to describe the system and a roadmap to keep tab of tasks to do. But I usually end up starting the agent each time with a command like: "read readme.md, roadmap.md and familiarize with the main project files, the project is a xyz project" where xyz is the framework used or the style of the implementation.

Right now I'm testing creating a Django site and this means there's a lot of existing files to take into account.

Even doing this, claude sometimes decides to wipe out most of the existing work, like when fixing a bug in urls.py it nukes all the existing urls and makes just one new one.

So, there's 2 things in this issue:
- storing some kind of a context -state for restarting in a new task
- respecting existing implementation

**Comment by jtac** [comment]
Correction, nuking content was an issue with big files (separately handled) but the context memory is still an issue. Perhaps we should save an abbreviated context as a pickup if nothing else is given?

**Comment by sergeyka** [comment]
I am wondering if vector database is a relevant solution here?

**Comment by mmuyakwa** [comment]
Unfortunately, I don't know of any code assist solution that solves the token limit using a vector database.
It is actually obvious. Unfortunately, everyone is struggling with it.

**Comment by jtac** [comment]
> I am wondering if vector database is a relevant solution here?

not on the output side of things, it solves more on the context side, for github copilot you can use the @workspace tag and it will try to answer your question based on your workspace contents using a vector comparison.

the output still is limited by the amount of tokens.

theoretically you could code it in such a way that if the answer is cut short due to token limits, it would be continued in the next answer as the context, question and partial answer would still fit the input context and the token prediction could continue from there.

then it's a question of signaling, how do  you know the answer was cut short as llms usually do not cut their answers short, they just make them short enough to fit. 

Perhaps such a model could be trained but that's way outside the scope of claude-dev

**Comment by saoudrizwan** [comment]
v1.1.13 now lets you add custom instructions to the system prompt. This would be a good place to put your "read readme.md, roadmap.md and familiarize with the main project files, the project is a xyz project".

Regarding the RAG concept–one of my biggest frustrations with existing AI tools is when referencing '@workspace', all the semantically "relevant" code was almost always irrelevant for complex enough queries. Claude Dev on the other hand explores projects using [names](https://github.com/saoudrizwan/claude-dev?tab=readme-ov-file#working-in-existing-projects). It looks for relevant files to read into context the same way you or I would, by looking at the names of directories, files, classes, functions, etc. as these tend to encapsulate the project's architecture and relationships between different components. So it's a bit different than traditional RAGs but at least doesn't require vectorizing your entire codebase, which requires an embeddings model (either locally which isn't great, or hosted so another API key).

As for the lazy coding, please see [this comment](https://github.com/saoudrizwan/claude-dev/issues/14#issuecomment-2283482762).

**Comment by JosephShawa** [comment]
Im in the process of making a "save chat" that loads both the saved chat and a summary that is supposed to summarize the essence. I would like the conversation to pick up where it left off as it does on Chatgpt. I also added a regularly updated "where we are now and where are we going file to be read at startup. So much happening and then I run out of tokens. Need that local anthingllm or any local llm as an llm choice.

**Comment by CiberNin** [comment]
It would be nice to store the full history of claude interactions / prompts / actions inside .vscode of each project. To allow for resuming of different tasks.

**Comment by chrisq084** [comment]
defininitly a way to retrive the previous conversations in case, you pc reset or you click new task by mistake you lose your  whole contest that you had going, just an undo btn will be fine or save the contest in a saprete folder some were so we can retrive it.

**Comment by saoudrizwan** [comment]
v1.3.0 now has task history 🎉 Please check it out and let me know what you think!
