### ISSUE TITLE
deepseek coder v2 support

### ISSUE THREAD

**Issue by byildiz78** [saoudrizwan/claude-dev#72]
app is fantastic . but with claude sonnet usage token costs are way to much. Would be great to have deepseek coder v2  support, since the model is as good as sonnet when it comes to coding

**Comment by AyronDevelop** [comment]
it would be great to support models that run on a device or on their own server

**Comment by saoudrizwan** [comment]
v1.1.13 now lets you choose other Claude models (+ GPT-4o, DeepSeek, and Mistral if you use OpenRouter)
