### ISSUE TITLE
command 'claude-dev.settingsButtonTapped' not found

### ISSUE THREAD

**Issue by biznizai** [saoudrizwan/claude-dev#73]
After install in VSCode, the extension logo doesn't show and when I click on the extension settings it just has the loading blue line at the top and this error message in a toast notification:
"command 'claude-dev.settingsButtonTapped' not found "

**Comment by biznizai** [comment]
I moved my vscode from my downloads folder to my applications folder on mac

**Comment by Leand3r** [comment]
For anyone still having the same issue, I fixed it by updating VSCode.
