### ISSUE TITLE
It doesn't run and has some sort of issue with Powershell on Windows

### ISSUE THREAD

**Issue by elhombrejd** [saoudrizwan/claude-dev#78]
I'm running Claude Dev in windows (PT-BR).  
The installation went normal.
After I inserted the API key I ended up with the following error:

```
Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
'powershell' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
```

The error translates as follows:

```
Command failed with exit code 1: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
'powershell' is not recognized as an internal or external command,
operable program, or batch file.
```

Seems to be some bug while trying to use Powershell to get some variable.

Any ideas on how to fix it?

**Comment by saoudrizwan** [comment]
Can you follow the instructions in this [stackoverflow thread](https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr/29778651#29778651) and try again? 

Unrelated, but if you'd like you can tell Claude Dev to respond in Portuguese by opening Settings > Custom Instructions > add "Speak in Portuguese"

**Comment by elhombrejd** [comment]
I'll try it again later today. As soon as I try it I'll update it here.
Thanks!

**Comment by saoudrizwan** [comment]
Feel free to re-open if you're still running into problems

**Comment by elhombrejd** [comment]
@saoudrizwan It worked like a charm!
Sorry for the delay. I just got the time to test it today.
Cheers!

**Comment by saoudrizwan** [comment]
Hey @elhombrejd, I made a troubleshooting doc to help other users experiencing this issue. Can you pls take a look over it and see if it follows what you had to do to resolve the issue? https://github.com/saoudrizwan/claude-dev/wiki/TroubleShooting-%E2%80%90-%22PowerShell-is-not-recognized-as-an-internal-or-external-command%22

**Comment by elhombrejd** [comment]
@saoudrizwan It does. I've followed that exact procedure and it fixed the issue.
