### ISSUE TITLE
OpenRouter

### ISSUE THREAD

**Issue by lars67** [saoudrizwan/claude-dev#79]
Great with OpenRouter support.
I notice that the models supported from OpenRouter is limited to 9 models - any chance of support of Llama or some "free" models supported by OpenRouter

/Lars

**Comment by saoudrizwan** [comment]
OpenRouter only allows tool calling with certain models, and I tested Claude Dev with [each and every one of them](https://openrouter.ai/models?supported_parameters=tools). What I found was most of them either did not have the ability to understand complex system prompts/tools, or OpenRouter hasn't properly configured tool calling for them yet. Unfortunately the llama models fall into the latter category, but I will add these models as soon as they start to work. 

Closing this ticket as there are other open issues asking for additional models.

**Comment by jackiezhangcn** [comment]
llama3.1 enabled with tool calling, would appreciate if it has the option of selecting some models by users, not fixed there
