### ISSUE TITLE
Cancelling action shouldn't lead to restarting conversation

### ISSUE THREAD

**Issue by aizenshtat** [saoudrizwan/claude-dev#8]
If Claude wants to make changes to the file and I don't agree with the changes and click "Cancel" the whole conversation will be reset and I have to start from scratch. More sensible approach would be to let me continue the conversation, while  not taking the action Claude propose.

**Comment by Amnonman** [comment]
I think this enhancement is super useful

**Comment by bzimbelman** [comment]
First, let me say this is a great tool and I have replaced my usage of aider and claude engineer almost completely with this tool. I will say the ability to 'tune' the task and interactions would be a great enhancement. By tune I mean doing things like:
- Giving additional feedback/direction at each prompt, so I don't have just 'cancel' or 'accept', but I could also tell the model, where to find a piece of code it missed, or I'd rather you used this package manager to run commands, or please write that code in typescript not javascript, etc.
- Also being able to adjust the chatter, I love that it steps me through how it is processing the task, but I would also like to be able to watch it and give feedback, but not have to say yes to each and every directory or file read for example. So, maybe the ability to tune how interactive the task is so I can ask it to prompt me for reads & writes, or just for writes, or ??? Something like that?
- Finally, the ability to keep memory about the project and give it some overall constraints on a project. This is a typescript, next.js webapp. We use jest and want a jest test for each component. It has these existing components, uses barrel files, etc. With aider I do that with a .md file that I always include in it's list of files, that way I can also tell human contributors to look at it and follow those conventions as well.
Please note, these are not complaints, and I'm looking at the code with an interest in helping you build this out into an even more fantastic tool. Just some ideas I had as a avid user of the tool.

**Comment by saoudrizwan** [comment]
v1.0.4 now has the ability to reject and provide feedback to tool use.
