### ISSUE TITLE
Running with SH instead of BASH

### ISSUE THREAD

**Issue by flo-ivar** [saoudrizwan/claude-dev#80]
On my Ubuntu machine the extension tries to run using SH instead of BASH. Leading to the error:

Error
Error executing command:
Command failed with exit code 127: 'node server.js'

/bin/sh: line 1: node: command not found

It would be nice if we could manually set this.

**Comment by saoudrizwan** [comment]
Claude Dev uses your system's default shell to execute commands. It looks like you don't have node installed, so either install node before Claude Dev runs these commands or even just ask it to install node for you first.

> It would be nice if we could manually set this.

v1.1.12 now lets you add custom instructions in settings. These instructions override the system prompt, so you can specify a different shell if you'd like.

**Comment by flo-ivar** [comment]
Hi, thank you for the information. The problem ended up being it not loading in my .bashrc. Was able to fix by re-installing vscode.
