### ISSUE TITLE
Add automatic git tracking option

### ISSUE THREAD

**Issue by xavitg** [saoudrizwan/claude-dev#82]
Hello,

When you are working on large apps, if the AI breaks something, the best is to run something like /undo and go back to the last commit. You should implement Git to Claude Dev. The experience is amazing. I use it with Aider a lot.
https://aider.chat/docs/git.html

Thank you

**Comment by saoudrizwan** [comment]
v1.1.13 now lets you add custom instructions which get added to the system prompt sent with every request. This is a good place to add a prompt like "after writing to files, you must run git commands to stage and commit your changes with a message that summarizes your changes". Give that a try and let me know how it goes!

**Comment by xavitg** [comment]
Hello,

I am using the Vscode extension. Where can I edit that?

Also, I just installed the vscode extension and I don't see the option to set up VertexAI. How can I add my vertexai credentials?

Thank you

**Comment by JosephShawa** [comment]
It is in the gear icon "settings" at the top right of the chat window. right below the api choices you can add custom prompts.

**Comment by CiberNin** [comment]
It might be smart to integrate this into the tool directly thought. Fewer round trips. And for context instead of just showing each version of the file claude read or wrote you could show the current version and claudes history of commits.

Maybe with a setting to disable this tool if desired.
