### ISSUE TITLE
Vertex AI Integration into vscode extension

### ISSUE THREAD

**Issue by xavitg** [saoudrizwan/claude-dev#83]
Hello @saoudrizwan I have installed the extension of vscode and it doesnt have the setting to add a vertexai credentials. Can you update this please? Thank you

**Comment by xavitg** [comment]
@saoudrizwan please!

**Comment by saoudrizwan** [comment]
Hi sorry, vertex support is coming–there's an open PR that you can use locally, but I've been looking into ways to authenticate with google without having to install their CLI first, i.e. oauth on a github hosted site.

**Comment by wonderzdh** [comment]
Hi, I am a Cursor user, and I'm very excited about Claude Dev. Cursor allows setting a URL in OpenAI API format, which I think is an excellent method for using custom LLMs.

**Comment by saoudrizwan** [comment]
v1.5.16 now has vertex support! Ollama support is on the roadmap, see https://github.com/saoudrizwan/claude-dev/issues/30#issuecomment-2325005847
