### ISSUE TITLE
Ability to AUTO Test the app/software after editing code

### ISSUE THREAD

**Issue by xavitg** [saoudrizwan/claude-dev#84]
Something amazing *that is possible to do right now* is that Claude Dev checks the website/app once updated some code. That would reduce drastically the waste of time of testing and texting with the chat to resolve a bug. 

It could send an image of how the software looks like for example so it can "see" and also make very easy the process of testing the code of those areas that don't look as expected. 

What do you think?

**Comment by JosephShawa** [comment]
> Something amazing _that is possible to do right now_ is that Claude Dev checks the website/app once updated some code. That would reduce drastically the waste of time of testing and texting with the chat to resolve a bug.
> 
> It could send an image of how the software looks like for example so it can "see" and also make very easy the process of testing the code of those areas that don't look as expected.

I just costs token: )

**Comment by xavitg** [comment]
> > Something amazing _that is possible to do right now_ is that Claude Dev checks the website/app once updated some code. That would reduce drastically the waste of time of testing and texting with the chat to resolve a bug.
> > It could send an image of how the software looks like for example so it can "see" and also make very easy the process of testing the code of those areas that don't look as expected.
> 
> I just costs token: )

If it auto resolves real problems of the web/app, I pay all the tokens needed.

**Comment by CiberNin** [comment]
Claude has access to console output right? You can setup vscode to auto run tests on file save, so in theory it should be possible to directly pipe that output to claude.

**Comment by saoudrizwan** [comment]
There's no way for me to see terminal output from vscode, the command output you see in claude dev is from a shell command i run as a nodejs subprocess right in the extension. Right now the best way to debug with claude dev is to take screenshots of errors and send them back to him to debug. Auto-debugging a browser for example is a bit out of scope for claude dev, although if anyone has suggestions to add this in a non-invasive way I'd love to hear.
