### ISSUE TITLE
I'd love a discord for this, I've made some really cool things already.

### ISSUE THREAD

**Issue by zenchantlive** [saoudrizwan/claude-dev#85]
Anyone feel like making one or running a discord? 

I don't have much knowledge of discord, but i have made some neat things that I would love to share with others.
I would also love to brainstorm ideas. 

Thank you to the DEVs, this is simply astounding and effective. 
I have been trying to find something of this caliber since GPT 4 was released. 

Bravo!

**Comment by mkearl** [comment]
I have created a Claude-Dev channel - https://discord.gg/hqkx2v2V

**Comment by saoudrizwan** [comment]
@zenchantlive thank you for the kind words! I'm so glad you're finding it useful :-)
@mkearl cool! I don't use discord much, but I'll check in every now and then
