### ISSUE TITLE
AWS BedRock Claude Sonnet 3.5 support

### ISSUE THREAD

**Issue by seanphan** [saoudrizwan/claude-dev#86]
Hi,
Thanks for great extension. Like title if we can use aws bedrock claude credits would really helpful.
Thank you

**Comment by mkearl** [comment]
![Screenshot 2024-08-13 at 1 25 28 AM](https://github.com/user-attachments/assets/b7953478-57d1-488d-b2d2-28d392c9c809)

This has already been added.  If you click on the gear icon and API Provider Bedrock is listed.

**Comment by seanphan** [comment]
Awesome, I missed that. Thank you
