### ISSUE TITLE
Add support for dynamic AWS credentials

### ISSUE THREAD

**Issue by tbensonwest** [saoudrizwan/claude-dev#88]
We use AWS session tokens. It would be useful if the tool could pick up credentials from environment variables, or at the very least being able to add the session token as well as the access key and secret key. I cannot use the tool off the shelf as-is right now as I get a 401 for invalid security token.

**Comment by davidgovea** [comment]
Added input in the extension settings: https://github.com/saoudrizwan/claude-dev/pull/188

I agree that env vars would be better

**Comment by saoudrizwan** [comment]
Thank you @davidgovea, going to look into this ASAP

**Comment by saoudrizwan** [comment]
v1.5.19 now supports session tokens and default AWS credential providers, i.e. ~/.aws/credentials or environment variables. Let me know if you guys want anything else!

**Comment by davidgovea** [comment]
Works great, thank you!

With temporary AWS credentials, you end up hitting expiration pretty often, so a `Restart Extension Host` will let claude-dev grab the latest creds from env.

<img width="328" alt="Screenshot 2024-09-04 at 9 07 07 AM" src="https://github.com/user-attachments/assets/8c51adae-3bdb-4259-8f18-ea5a8eb11198">

**Comment by saoudrizwan** [comment]
Good to know, thank you for pointing this out!

**Comment by saoudrizwan** [comment]
@davidgovea are you having trouble using aws with their new inference region changes?
