### ISSUE TITLE
I am trying to change the API key I entered initially and can't find the settings option

### ISSUE THREAD

**Issue by curtzh** [saoudrizwan/claude-dev#89]

**Comment by mkearl** [comment]
![Screenshot 2024-08-13 at 1 41 41 PM](https://github.com/user-attachments/assets/e80122f1-5d78-4c85-8d55-9f97c735f511)
There is a gear icon in the upper right of the extension.  You can make all changes there.

**Comment by curtzh** [comment]
<img width="752" alt="Screenshot 2024-08-13 at 1 47 37 PM" src="https://github.com/user-attachments/assets/5d96030a-0761-4ae8-a177-9387594d01aa">

Unfortunately it's not there :(

**Comment by curtzh** [comment]
Nevermind! I found it lmao. 
For the record I found Claude in the SIDEBAR
<img width="747" alt="image" src="https://github.com/user-attachments/assets/3b772935-3cfb-428d-a6f3-dab9d09370bd">

Whereas following the "Cmd/Ctrl + Shift + P > Claude Dev: Open In New Tab" instruction from the extension will NOT give you the gear icon.

**Comment by curtzh** [comment]
Resolved
