### ISSUE TITLE
Allow granting Claude Dev access to the whole project once

### ISSUE THREAD

**Issue by danielzohar** [saoudrizwan/claude-dev#9]
Instead of approving access to each and every time each time I run a new task, I'd like to give Claude Dev permanent access to all the files in my project. This will significantly speed up tasks and hopefully reduce costs. This should probably be a setting somewhere. Optionally, we can add a "remember this" checkbox when asking for access so the users don't have to discover this in the settings.

**Comment by saoudrizwan** [comment]
Thank you for your suggestion. I'm currently working on making code analysis smarter by looking at an entire git repo's files and using semantic elements within your source code, like symbols and doc comments.

**Comment by aanomm** [comment]
Claude Dev is brillaint thank you! It does seem somewhat insane — and costly — to have to continually grant access to the same files and folders over and over again. I hope a new options becomes available for this quickly.

**Comment by saoudrizwan** [comment]
v1.0.4 now has an `analyze_project` tool that allows Claude to see all the your project's files + source code defintions in one go. Thank you for the feedback!
