### ISSUE TITLE
Limit access before first request

### ISSUE THREAD

**Issue by martin503** [saoudrizwan/claude-dev#94]
Hi, very nice tool!
At first Claude asked me for access to whole repository, which I could not give it access too. Unfortunately after that it started to ask for each directory, even file separately and it did not ask for correct ones, which it should have in context to fulfil task. As an override I simply copied files I could give claude dev access to, and then gave it access to whole directory, but you probably can tell it is not something that is convenient to do each time :D

**Comment by CiberNin** [comment]
Not sure I understand. Are you saying there were files you specifically want to forbid claude from even reading?

**Comment by martin503** [comment]
Yeah, like for example secrets ;)

**Comment by martin503** [comment]
Ok, I get it now, the Claude does not read files at first, it just wants to get list of files in repo, am I right?

**Comment by saoudrizwan** [comment]
Hi @martin503 that's correct, it only looks at filepaths first and then you have to explicitly grant access to read file contents.
