### ISSUE TITLE
Prompt caching support

### ISSUE THREAD

**Issue by aliig** [saoudrizwan/claude-dev#96]
Feature request:

You may have seen the news already, but [Anthropic released prompt caching support](https://www.anthropic.com/news/prompt-caching) within the last couple of hours. This would make development with this tool dramatically less expensive! I might fiddle around and make a PR, but it's possible it's beyond my ability to integrate. :)

**Comment by jkristoph** [comment]
Thank looks incredible

**Comment by saoudrizwan** [comment]
Looking into it! Really exciting stuff

**Comment by saoudrizwan** [comment]
Prompt Caching is now available in v1.2.0 🎉 This is a gamechanger for Claude Dev, costs down by ~90% + response times down by at least half. Make sure you're using the Anthropic API with either Claude 3.5 Sonnet or Claude 3.0 Haiku. You'll now notice a "Prompt Cache" tracker in the task card, which keeps count of tokens written to Anthropic's cache -> tokens read from cache.
