### ISSUE TITLE
Select files/folders/etc with `@` dropdown as you type

### ISSUE THREAD

**Issue by ackoi** [saoudrizwan/claude-dev#97]
Love Claude Dev, a lot of time saving potential.

My request is, instead of waiting on the AI response to "request" to read a file, why not let the user select files to add from a dropdown as they type? Will save on a lot of time and tokens. 

Plus, since the AI only seems to have the file tree in the initial context, it does not actually have as much context as to what does what as the user does.

This change would be much appreciated!

**Comment by saoudrizwan** [comment]
Glad you're finding it useful! 

Referencing files and websites is something I plan on adding in the future! Also maybe a `@workspace` to just send the recrusive files list from the getgo, although this would behave differently than other AI tools that traditionally use this to run a RAQ query.

**Comment by CiberNin** [comment]
In the most common case where all extant files in the project would fit into less that 1/2 memory, could just load them all by default.
Fallback being recursive filenames & asking claude to rank files in order of importance for the current task. 1/4 prompt to full files and 1/4 to summarized files.

**Comment by saoudrizwan** [comment]
Closing as this is now in the latest v1.9.4!
